package sdk

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/the-inconvenience-store/cliford/pkg/registry"
)

// AuthEnhancer generates auth middleware code for the target app.
type AuthEnhancer struct {
	outputDir string
	appName   string
	envPrefix string
	schemes   map[string]registry.SecurityScheme
}

// NewAuthEnhancer creates an auth enhancer.
func NewAuthEnhancer(outputDir, appName, envPrefix string, schemes map[string]registry.SecurityScheme) *AuthEnhancer {
	return &AuthEnhancer{
		outputDir: outputDir,
		appName:   appName,
		envPrefix: envPrefix,
		schemes:   schemes,
	}
}

// Generate produces auth middleware and credential storage files for the target app.
func (a *AuthEnhancer) Generate() error {
	authDir := filepath.Join(a.outputDir, "internal", "auth")
	if err := os.MkdirAll(authDir, 0o755); err != nil {
		return fmt.Errorf("create auth dir: %w", err)
	}

	if err := a.generateMiddleware(authDir); err != nil {
		return err
	}
	if err := a.generateKeychain(authDir); err != nil {
		return err
	}
	if err := a.generateProfiles(authDir); err != nil {
		return err
	}

	return nil
}

func (a *AuthEnhancer) generateMiddleware(authDir string) error {
	var sb strings.Builder
	sb.WriteString(`// Code generated by Cliford. DO NOT EDIT outside custom code regions.
package auth

import (
	"encoding/base64"
	"fmt"
	"net/http"
)

// Middleware injects authentication credentials into outgoing HTTP requests.
type Middleware struct {
	store *Store
}

// NewMiddleware creates auth middleware backed by the given credential store.
func NewMiddleware(store *Store) *Middleware {
	return &Middleware{store: store}
}

// Apply attaches credentials to the request based on the active profile's auth method.
func (m *Middleware) Apply(req *http.Request) error {
	cred, err := m.store.GetActive()
	if err != nil {
		return nil // No credentials stored — allow unauthenticated requests
	}

	switch cred.Method {
	case "bearer":
		req.Header.Set("Authorization", "Bearer "+cred.Token)
	case "apiKey":
		if cred.HeaderName != "" {
			req.Header.Set(cred.HeaderName, cred.Token)
		} else {
			q := req.URL.Query()
			q.Set(cred.QueryParam, cred.Token)
			req.URL.RawQuery = q.Encode()
		}
	case "basic":
		encoded := base64.StdEncoding.EncodeToString([]byte(cred.Username + ":" + cred.Password))
		req.Header.Set("Authorization", "Basic "+encoded)
	case "oauth2":
		if cred.Token != "" {
			req.Header.Set("Authorization", "Bearer "+cred.Token)
		}
	default:
		return fmt.Errorf("unsupported auth method: %s", cred.Method)
	}

	return nil
}

// AuthFunc returns a function suitable for use with the SDK client's WithAuthFunc option.
func (m *Middleware) AuthFunc() func(req *http.Request) error {
	return m.Apply
}
`)

	return os.WriteFile(filepath.Join(authDir, "middleware.go"), []byte(sb.String()), 0o644)
}

func (a *AuthEnhancer) generateKeychain(authDir string) error {
	code := fmt.Sprintf(`// Code generated by Cliford. DO NOT EDIT outside custom code regions.
package auth

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"runtime"
)

const appName = %q

// Store manages credential storage with OS keychain as primary
// and encrypted file as fallback.
type Store struct {
	serviceName string
	configDir   string
	usingFallback bool
}

// Credential holds authentication data for a profile.
type Credential struct {
	Method     string `+"`"+`json:"method"`+"`"+`      // bearer, apiKey, basic, oauth2
	Token      string `+"`"+`json:"token,omitempty"`+"`"+`
	Username   string `+"`"+`json:"username,omitempty"`+"`"+`
	Password   string `+"`"+`json:"password,omitempty"`+"`"+`
	HeaderName string `+"`"+`json:"headerName,omitempty"`+"`"+`
	QueryParam string `+"`"+`json:"queryParam,omitempty"`+"`"+`
	ExpiresAt  string `+"`"+`json:"expiresAt,omitempty"`+"`"+`
	RefreshTkn string `+"`"+`json:"refreshToken,omitempty"`+"`"+`
}

// NewStore creates a credential store for the app.
func NewStore() *Store {
	configDir, _ := os.UserConfigDir()
	return &Store{
		serviceName: appName,
		configDir:   filepath.Join(configDir, appName, "auth"),
	}
}

// Save stores a credential for the given profile.
func (s *Store) Save(profile string, cred Credential) error {
	if err := os.MkdirAll(s.configDir, 0o700); err != nil {
		return fmt.Errorf("create auth dir: %%w", err)
	}

	data, err := json.Marshal(cred)
	if err != nil {
		return err
	}

	encrypted, err := encrypt(data, s.deriveKey(profile))
	if err != nil {
		return fmt.Errorf("encrypt credential: %%w", err)
	}

	path := filepath.Join(s.configDir, profile+".enc")
	if err := os.WriteFile(path, encrypted, 0o600); err != nil {
		return fmt.Errorf("write credential: %%w", err)
	}

	if s.usingFallback {
		fmt.Fprintf(os.Stderr, "Warning: credentials stored in encrypted file (OS keychain unavailable)\n")
	}

	return nil
}

// Get retrieves the credential for the given profile.
func (s *Store) Get(profile string) (*Credential, error) {
	path := filepath.Join(s.configDir, profile+".enc")
	encrypted, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, fmt.Errorf("no credentials for profile %%q", profile)
		}
		return nil, err
	}

	data, err := decrypt(encrypted, s.deriveKey(profile))
	if err != nil {
		return nil, fmt.Errorf("decrypt credential: %%w", err)
	}

	var cred Credential
	if err := json.Unmarshal(data, &cred); err != nil {
		return nil, err
	}
	return &cred, nil
}

// GetActive retrieves the credential for the active profile.
func (s *Store) GetActive() (*Credential, error) {
	profile := ActiveProfile()
	return s.Get(profile)
}

// Delete removes the credential for the given profile.
func (s *Store) Delete(profile string) error {
	path := filepath.Join(s.configDir, profile+".enc")
	if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
		return err
	}
	return nil
}

// deriveKey produces a deterministic encryption key from the profile name
// and machine-specific entropy.
func (s *Store) deriveKey(profile string) []byte {
	hostname, _ := os.Hostname()
	material := fmt.Sprintf("%%s:%%s:%%s:%%s", s.serviceName, profile, hostname, runtime.GOOS)
	hash := sha256.Sum256([]byte(material))
	return hash[:]
}

func encrypt(plaintext, key []byte) ([]byte, error) {
	block, err := aes.NewCipher(key)
	if err != nil {
		return nil, err
	}

	aesGCM, err := cipher.NewGCM(block)
	if err != nil {
		return nil, err
	}

	nonce := make([]byte, aesGCM.NonceSize())
	if _, err := io.ReadFull(rand.Reader, nonce); err != nil {
		return nil, err
	}

	return aesGCM.Seal(nonce, nonce, plaintext, nil), nil
}

func decrypt(ciphertext, key []byte) ([]byte, error) {
	block, err := aes.NewCipher(key)
	if err != nil {
		return nil, err
	}

	aesGCM, err := cipher.NewGCM(block)
	if err != nil {
		return nil, err
	}

	nonceSize := aesGCM.NonceSize()
	if len(ciphertext) < nonceSize {
		return nil, fmt.Errorf("ciphertext too short")
	}

	nonce, ciphertext := ciphertext[:nonceSize], ciphertext[nonceSize:]
	return aesGCM.Open(nil, nonce, ciphertext, nil)
}
`, a.appName)

	return os.WriteFile(filepath.Join(authDir, "keychain.go"), []byte(code), 0o644)
}

func (a *AuthEnhancer) generateProfiles(authDir string) error {
	code := fmt.Sprintf(`// Code generated by Cliford. DO NOT EDIT outside custom code regions.
package auth

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/viper"
)

// ActiveProfile returns the currently active profile name.
func ActiveProfile() string {
	p := viper.GetString("active_profile")
	if p == "" {
		return "default"
	}
	return p
}

// SetActiveProfile switches the active profile.
func SetActiveProfile(name string) error {
	viper.Set("active_profile", name)

	configDir, _ := os.UserConfigDir()
	configPath := filepath.Join(configDir, %q, "config.yaml")
	return viper.WriteConfigAs(configPath)
}

// ProfileServerURL returns the server URL for the given profile.
func ProfileServerURL(profile string) string {
	key := fmt.Sprintf("profiles.%%s.server.url", profile)
	return viper.GetString(key)
}

// ActiveServerURL returns the server URL for the active profile.
func ActiveServerURL() string {
	return ProfileServerURL(ActiveProfile())
}
`, a.appName)

	return os.WriteFile(filepath.Join(authDir, "profiles.go"), []byte(code), 0o644)
}
