package sdk

import (
	"fmt"
	"os"
	"path/filepath"
)

// ClientFactoryGenerator produces the HTTP client factory for the target app.
// The factory assembles a layered http.Client with auth, retry, and verbose transports.
type ClientFactoryGenerator struct {
	outputDir string
	appName   string
	envPrefix string
	pkgPath   string
	hasOAuth  bool
}

// NewClientFactoryGenerator creates a client factory generator.
func NewClientFactoryGenerator(outputDir, appName, envPrefix, pkgPath string) *ClientFactoryGenerator {
	return &ClientFactoryGenerator{
		outputDir: outputDir,
		appName:   appName,
		envPrefix: envPrefix,
		pkgPath:   pkgPath,
	}
}

// SetHasOAuth enables OAuth2 auto-refresh wiring in the generated factory.
// Call this when the spec includes OAuth 2.0 security schemes.
func (g *ClientFactoryGenerator) SetHasOAuth(v bool) {
	g.hasOAuth = v
}

// Generate produces the client factory file for the target app.
func (g *ClientFactoryGenerator) Generate() error {
	clientDir := filepath.Join(g.outputDir, "internal", "client")
	if err := os.MkdirAll(clientDir, 0o755); err != nil {
		return fmt.Errorf("create client dir: %w", err)
	}

	// Conditional OAuth fields in Options and wiring in NewHTTPClient.
	// auth.OAuthConfig only exists in the generated app when OAuth schemes are present.
	oauthOptionsFields := ""
	oauthMiddlewareWiring := ""
	if g.hasOAuth {
		oauthOptionsFields = `

	// OAuthConfig provides OAuth 2.0 configuration for automatic token refresh.
	// When non-nil, the auth middleware refreshes near-expiry tokens transparently.
	OAuthConfig *auth.OAuthConfig

	// CredentialStore persists refreshed OAuth tokens across requests.
	// Required when OAuthConfig is set.
	CredentialStore *auth.Store`
		oauthMiddlewareWiring = `
		if opts.OAuthConfig != nil {
			middleware.SetOAuthConfig(opts.OAuthConfig, opts.CredentialStore)
		}`
	}

	code := fmt.Sprintf(`// Code generated by Cliford. DO NOT EDIT outside custom code regions.
package client

import (
	"net/http"
	"time"

	"%s/internal/auth"
	"%s/internal/hooks"
	"%s/internal/sdk"
)

// Options configures the HTTP client factory.
type Options struct {
	// BaseTimeout is the default request timeout.
	BaseTimeout time.Duration

	// AuthResolver provides 5-tier credential resolution for authenticated requests.
	AuthResolver *auth.Resolver

	// RetryConfig overrides the default retry configuration.
	// If nil, DefaultRetryConfig() is used.
	RetryConfig *sdk.RetryConfig

	// RetryEnabled controls whether retry middleware is active.
	RetryEnabled bool

	// GlobalHeaders are injected into every request (from config global_params.headers).
	GlobalHeaders map[string]string

	// GlobalQueryParams are appended to every request URL (from config global_params.query).
	GlobalQueryParams map[string]string

	// VerboseFlag is a pointer to the --verbose CLI flag.
	// When non-nil and true, request/response details are logged to stderr.
	VerboseFlag *bool

	// HooksEnabled controls whether before/after request hooks are active.
	HooksEnabled bool

	// BeforeRequestHooks are the configured before_request hooks.
	BeforeRequestHooks []hooks.HookDef

	// AfterResponseHooks are the configured after_response hooks.
	AfterResponseHooks []hooks.HookDef%s
}

// DefaultOptions returns sensible default factory options.
func DefaultOptions() Options {
	return Options{
		BaseTimeout:  30 * time.Second,
		RetryEnabled: true,
	}
}

// NewHTTPClient assembles an http.Client with layered transports:
//
//	http.DefaultTransport
//	  → RetryTransport (exponential backoff)
//	    → AuthTransport (credential injection via 5-tier resolver)
//
// The outermost transport is applied last to the request.
func NewHTTPClient(opts Options) *http.Client {
	// Start with the default transport
	var transport http.RoundTripper = http.DefaultTransport

	// Layer 1 (innermost): Retry middleware
	if opts.RetryEnabled {
		retryCfg := sdk.DefaultRetryConfig()
		if opts.RetryConfig != nil {
			retryCfg = *opts.RetryConfig
		}
		transport = &sdk.RetryTransport{
			Base:   transport,
			Config: retryCfg,
		}
	}

	// Layer 2: Auth middleware (uses 5-tier credential resolver)
	if opts.AuthResolver != nil {
		middleware := auth.NewMiddleware(opts.AuthResolver)%s
		transport = &authTransport{
			base:       transport,
			middleware: middleware,
		}
	}

	// Layer 3: Global params injection (headers + query from config)
	if len(opts.GlobalHeaders) > 0 || len(opts.GlobalQueryParams) > 0 {
		transport = &globalParamsTransport{
			base:    transport,
			headers: opts.GlobalHeaders,
			query:   opts.GlobalQueryParams,
		}
	}

	// Layer 4: Hooks (before_request / after_response)
	if opts.HooksEnabled && (len(opts.BeforeRequestHooks) > 0 || len(opts.AfterResponseHooks) > 0) {
		runner := hooks.NewRunner(opts.BeforeRequestHooks, opts.AfterResponseHooks)
		transport = &hooksTransport{
			base:   transport,
			runner: runner,
		}
	}

	// Layer 5 (outermost): Verbose logging
	if opts.VerboseFlag != nil {
		transport = &sdk.VerboseTransport{
			Base:    transport,
			Enabled: opts.VerboseFlag,
		}
	}

	return &http.Client{
		Transport: transport,
		Timeout:   opts.BaseTimeout,
	}
}

// authTransport wraps an http.RoundTripper to inject auth credentials.
type authTransport struct {
	base       http.RoundTripper
	middleware *auth.Middleware
}

func (t *authTransport) RoundTrip(req *http.Request) (*http.Response, error) {
	if err := t.middleware.Apply(req); err != nil {
		return nil, err
	}
	return t.base.RoundTrip(req)
}

// hooksTransport wraps an http.RoundTripper with before/after request hooks.
type hooksTransport struct {
	base   http.RoundTripper
	runner *hooks.Runner
}

func (t *hooksTransport) RoundTrip(req *http.Request) (*http.Response, error) {
	if err := t.runner.RunBefore(req); err != nil {
		return nil, err
	}
	start := time.Now()
	resp, err := t.base.RoundTrip(req)
	elapsed := time.Since(start)
	t.runner.RunAfter(req, resp, elapsed, err)
	return resp, err
}

// globalParamsTransport injects configured global headers and query params into every request.
// Per-operation values take precedence (existing headers/params are not overwritten).
type globalParamsTransport struct {
	base    http.RoundTripper
	headers map[string]string
	query   map[string]string
}

func (t *globalParamsTransport) RoundTrip(req *http.Request) (*http.Response, error) {
	for k, v := range t.headers {
		if req.Header.Get(k) == "" { // Don't overwrite per-operation headers
			req.Header.Set(k, v)
		}
	}
	if len(t.query) > 0 {
		q := req.URL.Query()
		for k, v := range t.query {
			if q.Get(k) == "" { // Don't overwrite per-operation params
				q.Set(k, v)
			}
		}
		req.URL.RawQuery = q.Encode()
	}
	return t.base.RoundTrip(req)
}
`, g.pkgPath, g.pkgPath, g.pkgPath, oauthOptionsFields, oauthMiddlewareWiring)

	return os.WriteFile(filepath.Join(clientDir, "factory.go"), []byte(code), 0o644)
}
