package sdk

import (
	"fmt"
	"os"
	"path/filepath"
)

// ClientFactoryGenerator produces the HTTP client factory for the target app.
// The factory assembles a layered http.Client with auth, retry, and verbose transports.
type ClientFactoryGenerator struct {
	outputDir string
	appName   string
	envPrefix string
	pkgPath   string
}

// NewClientFactoryGenerator creates a client factory generator.
func NewClientFactoryGenerator(outputDir, appName, envPrefix, pkgPath string) *ClientFactoryGenerator {
	return &ClientFactoryGenerator{
		outputDir: outputDir,
		appName:   appName,
		envPrefix: envPrefix,
		pkgPath:   pkgPath,
	}
}

// Generate produces the client factory file for the target app.
func (g *ClientFactoryGenerator) Generate() error {
	clientDir := filepath.Join(g.outputDir, "internal", "client")
	if err := os.MkdirAll(clientDir, 0o755); err != nil {
		return fmt.Errorf("create client dir: %w", err)
	}

	code := fmt.Sprintf(`// Code generated by Cliford. DO NOT EDIT outside custom code regions.
package client

import (
	"net/http"
	"time"

	"%s/internal/auth"
	"%s/internal/hooks"
	"%s/internal/sdk"
)

// Options configures the HTTP client factory.
type Options struct {
	// BaseTimeout is the default request timeout.
	BaseTimeout time.Duration

	// AuthResolver provides 5-tier credential resolution for authenticated requests.
	AuthResolver *auth.Resolver

	// RetryConfig overrides the default retry configuration.
	// If nil, DefaultRetryConfig() is used.
	RetryConfig *sdk.RetryConfig

	// RetryEnabled controls whether retry middleware is active.
	RetryEnabled bool

	// VerboseFlag is a pointer to the --verbose CLI flag.
	// When non-nil and true, request/response details are logged to stderr.
	VerboseFlag *bool

	// HooksEnabled controls whether before/after request hooks are active.
	HooksEnabled bool

	// BeforeRequestHooks are the configured before_request hooks.
	BeforeRequestHooks []hooks.HookDef

	// AfterResponseHooks are the configured after_response hooks.
	AfterResponseHooks []hooks.HookDef
}

// DefaultOptions returns sensible default factory options.
func DefaultOptions() Options {
	return Options{
		BaseTimeout:  30 * time.Second,
		RetryEnabled: true,
	}
}

// NewHTTPClient assembles an http.Client with layered transports:
//
//	http.DefaultTransport
//	  → RetryTransport (exponential backoff)
//	    → AuthTransport (credential injection via 5-tier resolver)
//
// The outermost transport is applied last to the request.
func NewHTTPClient(opts Options) *http.Client {
	// Start with the default transport
	var transport http.RoundTripper = http.DefaultTransport

	// Layer 1 (innermost): Retry middleware
	if opts.RetryEnabled {
		retryCfg := sdk.DefaultRetryConfig()
		if opts.RetryConfig != nil {
			retryCfg = *opts.RetryConfig
		}
		transport = &sdk.RetryTransport{
			Base:   transport,
			Config: retryCfg,
		}
	}

	// Layer 2: Auth middleware (uses 5-tier credential resolver)
	if opts.AuthResolver != nil {
		middleware := auth.NewMiddleware(opts.AuthResolver)
		transport = &authTransport{
			base:       transport,
			middleware: middleware,
		}
	}

	// Layer 3: Hooks (before_request / after_response)
	if opts.HooksEnabled && (len(opts.BeforeRequestHooks) > 0 || len(opts.AfterResponseHooks) > 0) {
		runner := hooks.NewRunner(opts.BeforeRequestHooks, opts.AfterResponseHooks)
		transport = &hooksTransport{
			base:   transport,
			runner: runner,
		}
	}

	// Layer 4 (outermost): Verbose logging
	if opts.VerboseFlag != nil {
		transport = &sdk.VerboseTransport{
			Base:    transport,
			Enabled: opts.VerboseFlag,
		}
	}

	return &http.Client{
		Transport: transport,
		Timeout:   opts.BaseTimeout,
	}
}

// authTransport wraps an http.RoundTripper to inject auth credentials.
type authTransport struct {
	base       http.RoundTripper
	middleware *auth.Middleware
}

func (t *authTransport) RoundTrip(req *http.Request) (*http.Response, error) {
	if err := t.middleware.Apply(req); err != nil {
		return nil, err
	}
	return t.base.RoundTrip(req)
}

// hooksTransport wraps an http.RoundTripper with before/after request hooks.
type hooksTransport struct {
	base   http.RoundTripper
	runner *hooks.Runner
}

func (t *hooksTransport) RoundTrip(req *http.Request) (*http.Response, error) {
	if err := t.runner.RunBefore(req); err != nil {
		return nil, err
	}
	start := time.Now()
	resp, err := t.base.RoundTrip(req)
	elapsed := time.Since(start)
	t.runner.RunAfter(req, resp, elapsed, err)
	return resp, err
}
`, g.pkgPath, g.pkgPath, g.pkgPath)

	return os.WriteFile(filepath.Join(clientDir, "factory.go"), []byte(code), 0o644)
}
