package sdk

import (
	"os"
	"path/filepath"
)

// ErrorEnhancer generates the typed error hierarchy for the target app.
type ErrorEnhancer struct {
	outputDir string
}

// NewErrorEnhancer creates an error enhancer.
func NewErrorEnhancer(outputDir string) *ErrorEnhancer {
	return &ErrorEnhancer{outputDir: outputDir}
}

// Generate produces the error types file for the target app's SDK.
func (e *ErrorEnhancer) Generate() error {
	sdkDir := filepath.Join(e.outputDir, "internal", "sdk")
	if err := os.MkdirAll(sdkDir, 0o755); err != nil {
		return err
	}

	code := `// Code generated by Cliford. DO NOT EDIT outside custom code regions.
package sdk

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"
)

// APIError represents an HTTP error response from the API.
type APIError struct {
	StatusCode int               ` + "`" + `json:"statusCode"` + "`" + `
	Message    string            ` + "`" + `json:"message"` + "`" + `
	Body       json.RawMessage   ` + "`" + `json:"body,omitempty"` + "`" + `
	RequestID  string            ` + "`" + `json:"requestId,omitempty"` + "`" + `
	Operation  string            ` + "`" + `json:"operation"` + "`" + `
	Retried    int               ` + "`" + `json:"retried,omitempty"` + "`" + `
}

func (e *APIError) Error() string {
	msg := fmt.Sprintf("HTTP %d: %s", e.StatusCode, e.Message)
	if e.RequestID != "" {
		msg += fmt.Sprintf(" (request-id: %s)", e.RequestID)
	}
	if e.Retried > 0 {
		msg += fmt.Sprintf(" (retried %d times)", e.Retried)
	}
	return msg
}

// NetworkError represents a connection or DNS failure.
type NetworkError struct {
	Operation string ` + "`" + `json:"operation"` + "`" + `
	Cause     error  ` + "`" + `json:"-"` + "`" + `
	Message   string ` + "`" + `json:"message"` + "`" + `
	Retried   int    ` + "`" + `json:"retried,omitempty"` + "`" + `
}

func (e *NetworkError) Error() string {
	msg := fmt.Sprintf("network error for %s: %s", e.Operation, e.Message)
	if e.Retried > 0 {
		msg += fmt.Sprintf(" (retried %d times)", e.Retried)
	}
	return msg
}

func (e *NetworkError) Unwrap() error { return e.Cause }

// ValidationError represents a 422 response with field-level errors.
type ValidationError struct {
	APIError
	Fields []FieldError ` + "`" + `json:"fields,omitempty"` + "`" + `
}

// FieldError describes a validation failure on a specific field.
type FieldError struct {
	Field   string ` + "`" + `json:"field"` + "`" + `
	Message string ` + "`" + `json:"message"` + "`" + `
}

func (e *ValidationError) Error() string {
	msg := e.APIError.Error()
	for _, f := range e.Fields {
		msg += fmt.Sprintf("\n  - %s: %s", f.Field, f.Message)
	}
	return msg
}

// RateLimitError represents a 429 Too Many Requests response.
type RateLimitError struct {
	APIError
	RetryAfter time.Duration ` + "`" + `json:"retryAfter,omitempty"` + "`" + `
	Limit      int           ` + "`" + `json:"limit,omitempty"` + "`" + `
	Remaining  int           ` + "`" + `json:"remaining,omitempty"` + "`" + `
	Reset      time.Time     ` + "`" + `json:"reset,omitempty"` + "`" + `
}

func (e *RateLimitError) Error() string {
	return fmt.Sprintf("rate limited (retry after %s): %s", e.RetryAfter, e.APIError.Error())
}

// ParseAPIError reads an HTTP response and returns a typed error.
func ParseAPIError(resp *http.Response, operation string) error {
	body, _ := io.ReadAll(resp.Body)

	base := APIError{
		StatusCode: resp.StatusCode,
		Message:    http.StatusText(resp.StatusCode),
		Body:       body,
		RequestID:  resp.Header.Get("X-Request-ID"),
		Operation:  operation,
	}

	// Try to extract message from JSON body
	var jsonBody map[string]any
	if json.Unmarshal(body, &jsonBody) == nil {
		if msg, ok := jsonBody["message"].(string); ok {
			base.Message = msg
		}
	}

	switch resp.StatusCode {
	case 422:
		ve := &ValidationError{APIError: base}
		if jsonBody != nil {
			if fields, ok := jsonBody["fields"].([]any); ok {
				for _, f := range fields {
					if fm, ok := f.(map[string]any); ok {
						ve.Fields = append(ve.Fields, FieldError{
							Field:   fmt.Sprintf("%v", fm["field"]),
							Message: fmt.Sprintf("%v", fm["message"]),
						})
					}
				}
			}
			if details, ok := jsonBody["details"].([]any); ok {
				for _, d := range details {
					if dm, ok := d.(map[string]any); ok {
						ve.Fields = append(ve.Fields, FieldError{
							Field:   fmt.Sprintf("%v", dm["field"]),
							Message: fmt.Sprintf("%v", dm["message"]),
						})
					}
				}
			}
		}
		return ve

	case 429:
		re := &RateLimitError{APIError: base}
		if ra := resp.Header.Get("Retry-After"); ra != "" {
			if secs, err := fmt.Sscanf(ra, "%d"); err == nil && secs > 0 {
				_ = secs
			}
		}
		if limit := resp.Header.Get("X-RateLimit-Limit"); limit != "" {
			fmt.Sscanf(limit, "%d", &re.Limit)
		}
		if remaining := resp.Header.Get("X-RateLimit-Remaining"); remaining != "" {
			fmt.Sscanf(remaining, "%d", &re.Remaining)
		}
		return re

	default:
		return &base
	}
}
`

	return os.WriteFile(filepath.Join(sdkDir, "errors.go"), []byte(code), 0o644)
}
