package sdk

import (
	"fmt"
	"os"
	"path/filepath"
)

// HooksEnhancer generates the runtime hook execution system for the generated app.
// This handles before_request and after_response hooks configured by the end user.
type HooksEnhancer struct {
	outputDir string
	pkgPath   string
}

// NewHooksEnhancer creates a hooks enhancer.
func NewHooksEnhancer(outputDir, pkgPath string) *HooksEnhancer {
	return &HooksEnhancer{outputDir: outputDir, pkgPath: pkgPath}
}

// Generate produces the hooks runner file for the generated app.
func (h *HooksEnhancer) Generate() error {
	hooksDir := filepath.Join(h.outputDir, "internal", "hooks")
	if err := os.MkdirAll(hooksDir, 0o755); err != nil {
		return fmt.Errorf("create hooks dir: %w", err)
	}

	code := `// Code generated by Cliford. DO NOT EDIT outside custom code regions.
package hooks

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/rpc"
	"os"
	"os/exec"
	"strings"
	"sync"
	"time"

	"github.com/hashicorp/go-plugin"
)

// HookType identifies the hook execution mechanism.
type HookType string

const (
	HookTypeShell  HookType = "shell"
	HookTypePlugin HookType = "go-plugin"
)

// HookDef describes a configured hook.
type HookDef struct {
	Type       HookType ` + "`" + `yaml:"type" mapstructure:"type"` + "`" + `
	Command    string   ` + "`" + `yaml:"command" mapstructure:"command"` + "`" + `
	PluginPath string   ` + "`" + `yaml:"plugin_path,omitempty" mapstructure:"plugin_path"` + "`" + `
}

// HookContext is the data passed to hooks as JSON on stdin.
type HookContext struct {
	OperationID     string            ` + "`" + `json:"operation_id"` + "`" + `
	Method          string            ` + "`" + `json:"method"` + "`" + `
	URL             string            ` + "`" + `json:"url"` + "`" + `
	Headers         map[string]string ` + "`" + `json:"headers"` + "`" + `
	Body            string            ` + "`" + `json:"body,omitempty"` + "`" + `
	Timestamp       string            ` + "`" + `json:"timestamp"` + "`" + `
	StatusCode      int               ` + "`" + `json:"status_code,omitempty"` + "`" + `
	ResponseHeaders map[string]string ` + "`" + `json:"response_headers,omitempty"` + "`" + `
	ResponseBody    string            ` + "`" + `json:"response_body,omitempty"` + "`" + `
	ElapsedMs       int64             ` + "`" + `json:"elapsed_ms,omitempty"` + "`" + `
	Error           string            ` + "`" + `json:"error,omitempty"` + "`" + `
}

// HookResponse is returned by executeHook. It carries optional header
// modifications (for before_request) and an optional abort signal.
type HookResponse struct {
	Abort           bool
	AbortReason     string
	ModifiedHeaders map[string]string
}

// GetModifiedHeaders returns ModifiedHeaders safely on a nil receiver.
func (r *HookResponse) GetModifiedHeaders() map[string]string {
	if r == nil {
		return nil
	}
	return r.ModifiedHeaders
}

// Runner executes before_request and after_response hooks.
type Runner struct {
	BeforeRequest []HookDef
	AfterResponse []HookDef
	pluginClients map[string]*plugin.Client
	mu            sync.Mutex
}

// NewRunner creates a hook runner from configuration.
func NewRunner(before, after []HookDef) *Runner {
	return &Runner{
		BeforeRequest: before,
		AfterResponse: after,
	}
}

// RunBefore executes all before_request hooks. Returns an error if any hook
// aborts (non-zero exit code for shell hooks). Plugin hooks may also set
// ModifiedHeaders which are applied to the outgoing request.
func (r *Runner) RunBefore(req *http.Request) error {
	if len(r.BeforeRequest) == 0 {
		return nil
	}

	ctx := buildRequestContext(req)
	for _, hook := range r.BeforeRequest {
		resp, err := r.executeHook(hook, ctx, true)
		if err != nil {
			return fmt.Errorf("before_request hook aborted: %w", err)
		}
		for k, v := range resp.GetModifiedHeaders() {
			req.Header.Set(k, v)
		}
	}
	return nil
}

// RunAfter executes all after_response hooks. Errors are non-fatal.
func (r *Runner) RunAfter(req *http.Request, resp *http.Response, elapsed time.Duration, respErr error) {
	if len(r.AfterResponse) == 0 {
		return
	}

	ctx := buildRequestContext(req)
	if resp != nil {
		ctx.StatusCode = resp.StatusCode
		ctx.ResponseHeaders = flattenHeaders(resp.Header)
	}
	ctx.ElapsedMs = elapsed.Milliseconds()
	if respErr != nil {
		ctx.Error = respErr.Error()
	}

	for _, hook := range r.AfterResponse {
		_, _ = r.executeHook(hook, ctx, false) // after_response errors are non-fatal
	}
}

func buildRequestContext(req *http.Request) HookContext {
	return HookContext{
		Method:    req.Method,
		URL:       req.URL.String(),
		Headers:   flattenHeaders(req.Header),
		Timestamp: time.Now().UTC().Format(time.RFC3339),
	}
}

func flattenHeaders(h http.Header) map[string]string {
	result := make(map[string]string, len(h))
	for k, v := range h {
		// Redact sensitive headers
		lower := strings.ToLower(k)
		if lower == "authorization" || lower == "x-api-key" || strings.Contains(lower, "secret") || strings.Contains(lower, "token") {
			result[k] = "[REDACTED]"
		} else {
			result[k] = strings.Join(v, ", ")
		}
	}
	return result
}

func (r *Runner) executeHook(hook HookDef, ctx HookContext, isBefore bool) (*HookResponse, error) {
	switch hook.Type {
	case HookTypeShell, "":
		return nil, executeShellHook(hook.Command, ctx)
	case HookTypePlugin:
		return r.executePluginHook(hook.PluginPath, ctx, isBefore)
	default:
		return nil, fmt.Errorf("unknown hook type: %s", hook.Type)
	}
}

func executeShellHook(command string, ctx HookContext) error {
	data, err := json.Marshal(ctx)
	if err != nil {
		return fmt.Errorf("marshal hook context: %w", err)
	}

	cmd := exec.Command("sh", "-c", command)
	cmd.Stdin = bytes.NewReader(data)
	cmd.Stdout = os.Stdout

	var stderr bytes.Buffer
	cmd.Stderr = &stderr

	if err := cmd.Run(); err != nil {
		msg := strings.TrimSpace(stderr.String())
		if msg != "" {
			return fmt.Errorf("%s: %s", command, msg)
		}
		return fmt.Errorf("%s: %w", command, err)
	}
	return nil
}

// --- go-plugin integration ---

// handshakeConfig is the magic cookie that prevents arbitrary binaries from
// being loaded as plugins.
var handshakeConfig = plugin.HandshakeConfig{
	ProtocolVersion:  1,
	MagicCookieKey:   "CLIFORD_HOOK_PLUGIN",
	MagicCookieValue: "hook_v1",
}

// pluginMap maps the plugin name to its net/rpc implementation.
var pluginMap = plugin.PluginSet{
	"hook": &HookPlugin{},
}

// HookService is the interface that go-plugin hook binaries must implement.
type HookService interface {
	BeforeRequest(ctx HookContext) (*HookResponse, error)
	AfterResponse(ctx HookContext) (*HookResponse, error)
}

// --- net/rpc scaffolding ---

type hookRPCArgs struct{ Ctx HookContext }
type hookRPCReply struct {
	Resp *HookResponse
	Err  string
}

// hookRPCClient is the client side of the net/rpc bridge (used inside the generated app).
type hookRPCClient struct{ client *rpc.Client }

func (c *hookRPCClient) BeforeRequest(ctx HookContext) (*HookResponse, error) {
	var reply hookRPCReply
	if err := c.client.Call("Plugin.BeforeRequest", hookRPCArgs{Ctx: ctx}, &reply); err != nil {
		return nil, err
	}
	if reply.Err != "" {
		return nil, errors.New(reply.Err)
	}
	return reply.Resp, nil
}

func (c *hookRPCClient) AfterResponse(ctx HookContext) (*HookResponse, error) {
	var reply hookRPCReply
	if err := c.client.Call("Plugin.AfterResponse", hookRPCArgs{Ctx: ctx}, &reply); err != nil {
		return nil, err
	}
	if reply.Err != "" {
		return nil, errors.New(reply.Err)
	}
	return reply.Resp, nil
}

// hookRPCServer is the server side of the net/rpc bridge (implemented by plugin binary).
type hookRPCServer struct{ Impl HookService }

func (s *hookRPCServer) BeforeRequest(args hookRPCArgs, reply *hookRPCReply) error {
	resp, err := s.Impl.BeforeRequest(args.Ctx)
	if err != nil {
		reply.Err = err.Error()
		return nil
	}
	reply.Resp = resp
	return nil
}

func (s *hookRPCServer) AfterResponse(args hookRPCArgs, reply *hookRPCReply) error {
	resp, err := s.Impl.AfterResponse(args.Ctx)
	if err != nil {
		reply.Err = err.Error()
		return nil
	}
	reply.Resp = resp
	return nil
}

// HookPlugin is the hashicorp/go-plugin wrapper for HookService.
// Plugin authors embed this in their plugin binary's main.go.
type HookPlugin struct{ Impl HookService }

func (p *HookPlugin) Server(*plugin.MuxBroker) (interface{}, error) {
	return &hookRPCServer{Impl: p.Impl}, nil
}

func (p *HookPlugin) Client(_ *plugin.MuxBroker, c *rpc.Client) (interface{}, error) {
	return &hookRPCClient{client: c}, nil
}

// executePluginHook launches (or reuses a cached) plugin subprocess and calls
// BeforeRequest or AfterResponse depending on isBefore.
func (r *Runner) executePluginHook(pluginPath string, ctx HookContext, isBefore bool) (*HookResponse, error) {
	r.mu.Lock()
	if r.pluginClients == nil {
		r.pluginClients = make(map[string]*plugin.Client)
	}
	c, ok := r.pluginClients[pluginPath]
	if !ok {
		c = plugin.NewClient(&plugin.ClientConfig{
			HandshakeConfig: handshakeConfig,
			Plugins:         pluginMap,
			Cmd:             exec.Command(pluginPath),
		})
		r.pluginClients[pluginPath] = c
	}
	r.mu.Unlock()

	rpcClient, err := c.Client()
	if err != nil {
		return nil, fmt.Errorf("connect to plugin %q: %w", pluginPath, err)
	}
	raw, err := rpcClient.Dispense("hook")
	if err != nil {
		return nil, fmt.Errorf("dispense plugin %q: %w", pluginPath, err)
	}
	svc := raw.(HookService)
	if isBefore {
		return svc.BeforeRequest(ctx)
	}
	return svc.AfterResponse(ctx)
}
`

	return os.WriteFile(filepath.Join(hooksDir, "runner.go"), []byte(code), 0o644)
}
