package sdk

import (
	"fmt"
	"os"
	"path/filepath"
)

// HooksEnhancer generates the runtime hook execution system for the generated app.
// This handles before_request and after_response hooks configured by the end user.
type HooksEnhancer struct {
	outputDir string
	pkgPath   string
}

// NewHooksEnhancer creates a hooks enhancer.
func NewHooksEnhancer(outputDir, pkgPath string) *HooksEnhancer {
	return &HooksEnhancer{outputDir: outputDir, pkgPath: pkgPath}
}

// Generate produces the hooks runner file for the generated app.
func (h *HooksEnhancer) Generate() error {
	hooksDir := filepath.Join(h.outputDir, "internal", "hooks")
	if err := os.MkdirAll(hooksDir, 0o755); err != nil {
		return fmt.Errorf("create hooks dir: %w", err)
	}

	code := `// Code generated by Cliford. DO NOT EDIT outside custom code regions.
package hooks

import (
	"bytes"
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"os/exec"
	"strings"
	"time"
)

// HookType identifies the hook execution mechanism.
type HookType string

const (
	HookTypeShell  HookType = "shell"
	HookTypePlugin HookType = "go-plugin"
)

// HookDef describes a configured hook.
type HookDef struct {
	Type       HookType ` + "`" + `yaml:"type" mapstructure:"type"` + "`" + `
	Command    string   ` + "`" + `yaml:"command" mapstructure:"command"` + "`" + `
	PluginPath string   ` + "`" + `yaml:"plugin_path,omitempty" mapstructure:"plugin_path"` + "`" + `
}

// HookContext is the data passed to hooks as JSON on stdin.
type HookContext struct {
	OperationID     string            ` + "`" + `json:"operation_id"` + "`" + `
	Method          string            ` + "`" + `json:"method"` + "`" + `
	URL             string            ` + "`" + `json:"url"` + "`" + `
	Headers         map[string]string ` + "`" + `json:"headers"` + "`" + `
	Body            string            ` + "`" + `json:"body,omitempty"` + "`" + `
	Timestamp       string            ` + "`" + `json:"timestamp"` + "`" + `
	StatusCode      int               ` + "`" + `json:"status_code,omitempty"` + "`" + `
	ResponseHeaders map[string]string ` + "`" + `json:"response_headers,omitempty"` + "`" + `
	ResponseBody    string            ` + "`" + `json:"response_body,omitempty"` + "`" + `
	ElapsedMs       int64             ` + "`" + `json:"elapsed_ms,omitempty"` + "`" + `
	Error           string            ` + "`" + `json:"error,omitempty"` + "`" + `
}

// Runner executes before_request and after_response hooks.
type Runner struct {
	BeforeRequest []HookDef
	AfterResponse []HookDef
}

// NewRunner creates a hook runner from configuration.
func NewRunner(before, after []HookDef) *Runner {
	return &Runner{
		BeforeRequest: before,
		AfterResponse: after,
	}
}

// RunBefore executes all before_request hooks. Returns an error if any hook
// aborts (non-zero exit code for shell hooks).
func (r *Runner) RunBefore(req *http.Request) error {
	if len(r.BeforeRequest) == 0 {
		return nil
	}

	ctx := buildRequestContext(req)
	for _, hook := range r.BeforeRequest {
		if err := executeHook(hook, ctx); err != nil {
			return fmt.Errorf("before_request hook aborted: %w", err)
		}
	}
	return nil
}

// RunAfter executes all after_response hooks.
func (r *Runner) RunAfter(req *http.Request, resp *http.Response, elapsed time.Duration, respErr error) {
	if len(r.AfterResponse) == 0 {
		return
	}

	ctx := buildRequestContext(req)
	if resp != nil {
		ctx.StatusCode = resp.StatusCode
		ctx.ResponseHeaders = flattenHeaders(resp.Header)
	}
	ctx.ElapsedMs = elapsed.Milliseconds()
	if respErr != nil {
		ctx.Error = respErr.Error()
	}

	for _, hook := range r.AfterResponse {
		_ = executeHook(hook, ctx) // after_response errors are logged, not fatal
	}
}

func buildRequestContext(req *http.Request) HookContext {
	return HookContext{
		Method:    req.Method,
		URL:       req.URL.String(),
		Headers:   flattenHeaders(req.Header),
		Timestamp: time.Now().UTC().Format(time.RFC3339),
	}
}

func flattenHeaders(h http.Header) map[string]string {
	result := make(map[string]string, len(h))
	for k, v := range h {
		// Redact sensitive headers
		lower := strings.ToLower(k)
		if lower == "authorization" || lower == "x-api-key" || strings.Contains(lower, "secret") || strings.Contains(lower, "token") {
			result[k] = "[REDACTED]"
		} else {
			result[k] = strings.Join(v, ", ")
		}
	}
	return result
}

func executeHook(hook HookDef, ctx HookContext) error {
	switch hook.Type {
	case HookTypeShell, "":
		return executeShellHook(hook.Command, ctx)
	case HookTypePlugin:
		// go-plugin hooks: not yet implemented (requires hashicorp/go-plugin gRPC setup)
		fmt.Fprintf(os.Stderr, "Warning: go-plugin hooks not yet fully implemented, skipping %s\n", hook.PluginPath)
		return nil
	default:
		return fmt.Errorf("unknown hook type: %s", hook.Type)
	}
}

func executeShellHook(command string, ctx HookContext) error {
	data, err := json.Marshal(ctx)
	if err != nil {
		return fmt.Errorf("marshal hook context: %w", err)
	}

	cmd := exec.Command("sh", "-c", command)
	cmd.Stdin = bytes.NewReader(data)
	cmd.Stdout = os.Stdout

	var stderr bytes.Buffer
	cmd.Stderr = &stderr

	if err := cmd.Run(); err != nil {
		msg := strings.TrimSpace(stderr.String())
		if msg != "" {
			return fmt.Errorf("%s: %s", command, msg)
		}
		return fmt.Errorf("%s: %w", command, err)
	}
	return nil
}
`

	return os.WriteFile(filepath.Join(hooksDir, "runner.go"), []byte(code), 0o644)
}
