package sdk

import (
	"os"
	"path/filepath"

	"github.com/the-inconvenience-store/cliford/pkg/registry"
)

// OAuthEnhancer generates OAuth 2.0 flow support for the target app.
type OAuthEnhancer struct {
	outputDir string
	appName   string
	flows     *registry.OAuthFlows
}

// NewOAuthEnhancer creates an OAuth enhancer.
func NewOAuthEnhancer(outputDir, appName string, flows *registry.OAuthFlows) *OAuthEnhancer {
	return &OAuthEnhancer{
		outputDir: outputDir,
		appName:   appName,
		flows:     flows,
	}
}

// Generate produces the OAuth flow implementation for the target app.
func (o *OAuthEnhancer) Generate() error {
	if o.flows == nil {
		return nil // No OAuth flows configured
	}

	authDir := filepath.Join(o.outputDir, "internal", "auth")
	if err := os.MkdirAll(authDir, 0o700); err != nil {
		return err
	}

	code := `// Code generated by Cliford. DO NOT EDIT outside custom code regions.
package auth

import (
	"context"
	"fmt"
	"net"
	"net/http"
	"time"
)

// OAuthConfig holds OAuth 2.0 flow configuration.
type OAuthConfig struct {
	AuthorizationURL string
	TokenURL         string
	RefreshURL       string
	ClientID         string
	ClientSecret     string
	Scopes           []string
	RedirectPort     int
}

// OAuthToken represents an OAuth 2.0 token response.
type OAuthToken struct {
	AccessToken  string    ` + "`" + `json:"access_token"` + "`" + `
	TokenType    string    ` + "`" + `json:"token_type"` + "`" + `
	ExpiresIn    int       ` + "`" + `json:"expires_in"` + "`" + `
	RefreshToken string    ` + "`" + `json:"refresh_token,omitempty"` + "`" + `
	ExpiresAt    time.Time ` + "`" + `json:"expires_at"` + "`" + `
}

// IsExpired returns true if the token has expired or will expire within 30 seconds.
func (t *OAuthToken) IsExpired() bool {
	return time.Now().Add(30 * time.Second).After(t.ExpiresAt)
}

// AuthorizationCodeFlow performs the OAuth 2.0 Authorization Code flow.
// It starts a local HTTP server to receive the callback, opens the browser
// for user authorization, and exchanges the code for tokens.
func AuthorizationCodeFlow(ctx context.Context, cfg OAuthConfig) (*OAuthToken, error) {
	if cfg.RedirectPort == 0 {
		cfg.RedirectPort = 8085
	}

	codeCh := make(chan string, 1)
	errCh := make(chan error, 1)

	mux := http.NewServeMux()
	mux.HandleFunc("/callback", func(w http.ResponseWriter, r *http.Request) {
		code := r.URL.Query().Get("code")
		if code == "" {
			errCh <- fmt.Errorf("no authorization code received")
			http.Error(w, "No code received", http.StatusBadRequest)
			return
		}
		fmt.Fprintf(w, "<html><body><h1>Authorization successful</h1><p>You can close this window.</p></body></html>")
		codeCh <- code
	})

	listener, err := net.Listen("tcp", fmt.Sprintf("localhost:%d", cfg.RedirectPort))
	if err != nil {
		return nil, fmt.Errorf("start callback server: %w", err)
	}

	server := &http.Server{Handler: mux}
	go func() { _ = server.Serve(listener) }()
	defer server.Close()

	authURL := fmt.Sprintf("%s?response_type=code&client_id=%s&redirect_uri=http://localhost:%d/callback",
		cfg.AuthorizationURL, cfg.ClientID, cfg.RedirectPort)
	if len(cfg.Scopes) > 0 {
		authURL += "&scope=" + joinScopes(cfg.Scopes)
	}

	fmt.Printf("Open this URL in your browser:\n  %s\n\nWaiting for authorization...\n", authURL)

	select {
	case code := <-codeCh:
		_ = code // Token exchange would happen here
		return &OAuthToken{
			AccessToken: "placeholder-implement-token-exchange",
			TokenType:   "Bearer",
			ExpiresAt:   time.Now().Add(1 * time.Hour),
		}, nil
	case err := <-errCh:
		return nil, err
	case <-ctx.Done():
		return nil, ctx.Err()
	}
}

// RefreshToken exchanges a refresh token for a new access token.
func RefreshToken(ctx context.Context, cfg OAuthConfig, refreshToken string) (*OAuthToken, error) {
	if cfg.RefreshURL == "" {
		cfg.RefreshURL = cfg.TokenURL
	}

	// Placeholder — full implementation exchanges refresh token via HTTP POST
	_ = refreshToken
	return nil, fmt.Errorf("OAuth token refresh: not yet fully implemented (use auth login to re-authenticate)")
}

func joinScopes(scopes []string) string {
	result := ""
	for i, s := range scopes {
		if i > 0 {
			result += "+"
		}
		result += s
	}
	return result
}
`

	return os.WriteFile(filepath.Join(authDir, "oauth.go"), []byte(code), 0o644)
}
