package sdk

import (
	"os"
	"path/filepath"

	"github.com/the-inconvenience-store/cliford/pkg/registry"
)

// OAuthEnhancer generates OAuth 2.0 flow support for the target app.
type OAuthEnhancer struct {
	outputDir string
	appName   string
	flows     *registry.OAuthFlows
}

// NewOAuthEnhancer creates an OAuth enhancer.
func NewOAuthEnhancer(outputDir, appName string, flows *registry.OAuthFlows) *OAuthEnhancer {
	return &OAuthEnhancer{
		outputDir: outputDir,
		appName:   appName,
		flows:     flows,
	}
}

// Generate produces the OAuth flow implementation for the target app.
func (o *OAuthEnhancer) Generate() error {
	if o.flows == nil {
		return nil // No OAuth flows configured
	}

	authDir := filepath.Join(o.outputDir, "internal", "auth")
	if err := os.MkdirAll(authDir, 0o700); err != nil {
		return err
	}

	code := `// Code generated by Cliford. DO NOT EDIT outside custom code regions.
package auth

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net"
	"net/http"
	"net/url"
	"strings"
	"sync"
	"time"

	"golang.org/x/oauth2"
	"golang.org/x/oauth2/clientcredentials"
)

// OAuthConfig holds OAuth 2.0 flow configuration.
type OAuthConfig struct {
	AuthorizationURL string
	TokenURL         string
	RefreshURL       string
	ClientID         string
	ClientSecret     string
	Scopes           []string
	RedirectPort     int
}

// OAuthToken represents an OAuth 2.0 token response.
type OAuthToken struct {
	AccessToken  string    ` + "`" + `json:"access_token"` + "`" + `
	TokenType    string    ` + "`" + `json:"token_type"` + "`" + `
	ExpiresIn    int       ` + "`" + `json:"expires_in"` + "`" + `
	RefreshToken string    ` + "`" + `json:"refresh_token,omitempty"` + "`" + `
	ExpiresAt    time.Time ` + "`" + `json:"expires_at"` + "`" + `
}

// IsExpired returns true if the token has expired or will expire within 30 seconds.
func (t *OAuthToken) IsExpired() bool {
	return time.Now().Add(30 * time.Second).After(t.ExpiresAt)
}

// AuthorizationCodeFlow performs the OAuth 2.0 Authorization Code flow.
// It starts a local HTTP server to receive the callback, opens the browser
// for user authorization, and exchanges the code for tokens.
func AuthorizationCodeFlow(ctx context.Context, cfg OAuthConfig) (*OAuthToken, error) {
	if cfg.RedirectPort == 0 {
		cfg.RedirectPort = 8085
	}

	codeCh := make(chan string, 1)
	errCh := make(chan error, 1)

	mux := http.NewServeMux()
	mux.HandleFunc("/callback", func(w http.ResponseWriter, r *http.Request) {
		code := r.URL.Query().Get("code")
		if code == "" {
			errCh <- fmt.Errorf("no authorization code received")
			http.Error(w, "No code received", http.StatusBadRequest)
			return
		}
		fmt.Fprintf(w, "<html><body><h1>Authorization successful</h1><p>You can close this window.</p></body></html>")
		codeCh <- code
	})

	listener, err := net.Listen("tcp", fmt.Sprintf("localhost:%d", cfg.RedirectPort))
	if err != nil {
		return nil, fmt.Errorf("start callback server: %w", err)
	}

	server := &http.Server{Handler: mux}
	go func() { _ = server.Serve(listener) }()
	defer server.Close()

	authURL := fmt.Sprintf("%s?response_type=code&client_id=%s&redirect_uri=http://localhost:%d/callback",
		cfg.AuthorizationURL, cfg.ClientID, cfg.RedirectPort)
	if len(cfg.Scopes) > 0 {
		authURL += "&scope=" + joinScopes(cfg.Scopes)
	}

	fmt.Printf("Open this URL in your browser:\n  %s\n\nWaiting for authorization...\n", authURL)

	select {
	case code := <-codeCh:
		// Exchange authorization code for tokens
		data := url.Values{
			"grant_type":   {"authorization_code"},
			"code":         {code},
			"redirect_uri": {fmt.Sprintf("http://localhost:%d/callback", cfg.RedirectPort)},
			"client_id":    {cfg.ClientID},
		}
		if cfg.ClientSecret != "" {
			data.Set("client_secret", cfg.ClientSecret)
		}

		tokenReq, reqErr := http.NewRequestWithContext(ctx, "POST", cfg.TokenURL, strings.NewReader(data.Encode()))
		if reqErr != nil {
			return nil, fmt.Errorf("create token request: %w", reqErr)
		}
		tokenReq.Header.Set("Content-Type", "application/x-www-form-urlencoded")

		tokenResp, doErr := http.DefaultClient.Do(tokenReq)
		if doErr != nil {
			return nil, fmt.Errorf("token exchange failed: %w", doErr)
		}
		defer tokenResp.Body.Close()

		body, _ := io.ReadAll(tokenResp.Body)
		if tokenResp.StatusCode != http.StatusOK {
			return nil, fmt.Errorf("token exchange failed (HTTP %d): %s", tokenResp.StatusCode, string(body))
		}

		var token OAuthToken
		if jsonErr := json.Unmarshal(body, &token); jsonErr != nil {
			return nil, fmt.Errorf("parse token response: %w", jsonErr)
		}
		if token.ExpiresIn > 0 && token.ExpiresAt.IsZero() {
			token.ExpiresAt = time.Now().Add(time.Duration(token.ExpiresIn) * time.Second)
		}
		return &token, nil
	case err := <-errCh:
		return nil, err
	case <-ctx.Done():
		return nil, ctx.Err()
	}
}

// RefreshToken exchanges a refresh token for a new access token.
func RefreshToken(ctx context.Context, cfg OAuthConfig, refreshToken string) (*OAuthToken, error) {
	if refreshToken == "" {
		return nil, fmt.Errorf("no refresh token available; use auth login to re-authenticate")
	}
	tokenURL := cfg.RefreshURL
	if tokenURL == "" {
		tokenURL = cfg.TokenURL
	}
	if tokenURL == "" {
		return nil, fmt.Errorf("no token URL configured for refresh")
	}

	data := url.Values{
		"grant_type":    {"refresh_token"},
		"refresh_token": {refreshToken},
		"client_id":     {cfg.ClientID},
	}
	if cfg.ClientSecret != "" {
		data.Set("client_secret", cfg.ClientSecret)
	}

	req, err := http.NewRequestWithContext(ctx, "POST", tokenURL, strings.NewReader(data.Encode()))
	if err != nil {
		return nil, fmt.Errorf("create refresh request: %w", err)
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("refresh token request failed: %w", err)
	}
	defer resp.Body.Close()

	body, _ := io.ReadAll(resp.Body)
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("token refresh failed (HTTP %d): %s", resp.StatusCode, string(body))
	}

	var token OAuthToken
	if jsonErr := json.Unmarshal(body, &token); jsonErr != nil {
		return nil, fmt.Errorf("parse refresh response: %w", jsonErr)
	}
	if token.ExpiresIn > 0 && token.ExpiresAt.IsZero() {
		token.ExpiresAt = time.Now().Add(time.Duration(token.ExpiresIn) * time.Second)
	}
	return &token, nil
}

// ClientCredentialsManager handles OAuth 2.0 Client Credentials flow
// with automatic token caching and proactive refresh.
type ClientCredentialsManager struct {
	mu          sync.Mutex
	config      *clientcredentials.Config
	cachedToken *oauth2.Token
}

// NewClientCredentialsManager creates a manager for the Client Credentials flow.
func NewClientCredentialsManager(tokenURL, clientID, clientSecret string, scopes []string) *ClientCredentialsManager {
	return &ClientCredentialsManager{
		config: &clientcredentials.Config{
			ClientID:     clientID,
			ClientSecret: clientSecret,
			TokenURL:     tokenURL,
			Scopes:       scopes,
		},
	}
}

// Token returns a valid access token, fetching or refreshing as needed.
// The token is cached in memory and refreshed 60 seconds before expiry.
func (m *ClientCredentialsManager) Token(ctx context.Context) (string, error) {
	m.mu.Lock()
	defer m.mu.Unlock()

	// Return cached token if still valid (with 60s buffer)
	if m.cachedToken != nil && time.Now().Add(60*time.Second).Before(m.cachedToken.Expiry) {
		return m.cachedToken.AccessToken, nil
	}

	// Fetch new token
	token, err := m.config.Token(ctx)
	if err != nil {
		return "", fmt.Errorf("OAuth2 client credentials token exchange failed: %w", err)
	}

	m.cachedToken = token
	return token.AccessToken, nil
}

// Credential returns an auth Credential from the cached or freshly fetched token.
func (m *ClientCredentialsManager) Credential(ctx context.Context) (*Credential, error) {
	token, err := m.Token(ctx)
	if err != nil {
		return nil, err
	}
	return &Credential{
		Method: "oauth2",
		Token:  token,
	}, nil
}

func joinScopes(scopes []string) string {
	result := ""
	for i, s := range scopes {
		if i > 0 {
			result += "+"
		}
		result += s
	}
	return result
}
`

	return os.WriteFile(filepath.Join(authDir, "oauth.go"), []byte(code), 0o644)
}
