package sdk

import (
	"os"
	"path/filepath"
)

// PaginationEnhancer generates pagination helper code for the target app.
type PaginationEnhancer struct {
	outputDir string
}

// NewPaginationEnhancer creates a pagination enhancer.
func NewPaginationEnhancer(outputDir string) *PaginationEnhancer {
	return &PaginationEnhancer{outputDir: outputDir}
}

// Generate produces the pagination helper file for the target app's SDK.
func (p *PaginationEnhancer) Generate() error {
	sdkDir := filepath.Join(p.outputDir, "internal", "sdk")
	if err := os.MkdirAll(sdkDir, 0o755); err != nil {
		return err
	}

	code := `// Code generated by Cliford. DO NOT EDIT outside custom code regions.
package sdk

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"regexp"
	"strconv"
	"strings"
)

// PageIterator provides lazy, memory-efficient iteration over paginated results.
type PageIterator[T any] struct {
	fetch     func(cursor string) ([]T, string, error)
	buffer    []T
	cursor    string
	done      bool
	pageCount int
	maxPages  int
}

// NewPageIterator creates an iterator that calls fetch with a cursor to get each page.
// The fetch function returns (items, nextCursor, error). An empty nextCursor signals the last page.
func NewPageIterator[T any](fetch func(cursor string) ([]T, string, error), maxPages int) *PageIterator[T] {
	mp := maxPages
	if mp <= 0 {
		mp = 1000 // Safety limit
	}
	return &PageIterator[T]{fetch: fetch, maxPages: mp}
}

// Next returns the next item. Returns io.EOF when all pages are exhausted.
func (it *PageIterator[T]) Next() (T, error) {
	for len(it.buffer) == 0 {
		if it.done {
			var zero T
			return zero, io.EOF
		}
		if it.pageCount >= it.maxPages {
			var zero T
			return zero, io.EOF
		}

		items, nextCursor, err := it.fetch(it.cursor)
		if err != nil {
			var zero T
			return zero, err
		}

		it.buffer = items
		it.pageCount++

		if nextCursor == "" || len(items) == 0 {
			it.done = true
		}
		it.cursor = nextCursor
	}

	item := it.buffer[0]
	it.buffer = it.buffer[1:]
	return item, nil
}

// All collects all remaining items into a slice.
func (it *PageIterator[T]) All() ([]T, error) {
	var all []T
	for {
		item, err := it.Next()
		if err == io.EOF {
			return all, nil
		}
		if err != nil {
			return all, err
		}
		all = append(all, item)
	}
}

// PaginateAll fetches all pages from a paginated endpoint and returns combined results.
// This is a convenience function for simple use cases.
func PaginateAll[T any](
	client *http.Client,
	baseURL string,
	buildReq func(cursor string) (*http.Request, error),
	parseResp func(body []byte) (items []T, nextCursor string, err error),
	maxPages int,
) ([]T, error) {
	it := NewPageIterator(func(cursor string) ([]T, string, error) {
		req, err := buildReq(cursor)
		if err != nil {
			return nil, "", err
		}

		resp, err := client.Do(req)
		if err != nil {
			return nil, "", err
		}
		defer resp.Body.Close()

		if resp.StatusCode >= 400 {
			body, _ := io.ReadAll(resp.Body)
			return nil, "", fmt.Errorf("HTTP %d: %s", resp.StatusCode, string(body))
		}

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return nil, "", err
		}

		// Check for Link header pagination
		if linkNext := parseLinkHeader(resp.Header.Get("Link")); linkNext != "" {
			items, _, err := parseResp(body)
			return items, linkNext, err
		}

		return parseResp(body)
	}, maxPages)

	return it.All()
}

// ExtractJSONPath extracts a value from JSON using a simple JSONPath expression.
// Supports: $.field, $.field.nested, $.field[*] (returns array contents).
func ExtractJSONPath(data []byte, path string) (json.RawMessage, error) {
	path = strings.TrimPrefix(path, "$.")
	parts := strings.Split(path, ".")

	var current any
	if err := json.Unmarshal(data, &current); err != nil {
		return nil, err
	}

	for _, part := range parts {
		m, ok := current.(map[string]any)
		if !ok {
			return nil, fmt.Errorf("cannot traverse %q: not an object", part)
		}
		current, ok = m[part]
		if !ok {
			return nil, fmt.Errorf("key %q not found", part)
		}
	}

	return json.Marshal(current)
}

// parseLinkHeader extracts the "next" URL from an RFC 5988 Link header.
func parseLinkHeader(header string) string {
	if header == "" {
		return ""
	}

	re := regexp.MustCompile(` + "`" + `<([^>]+)>;\s*rel="next"` + "`" + `)
	matches := re.FindStringSubmatch(header)
	if len(matches) >= 2 {
		return matches[1]
	}
	return ""
}

// ParseOffsetTotal parses offset pagination metadata from a response.
func ParseOffsetTotal(data []byte, totalPath string) (int, error) {
	raw, err := ExtractJSONPath(data, totalPath)
	if err != nil {
		return 0, err
	}

	var total float64
	if err := json.Unmarshal(raw, &total); err != nil {
		// Try string
		var s string
		if err := json.Unmarshal(raw, &s); err != nil {
			return 0, fmt.Errorf("total is not a number: %w", err)
		}
		n, err := strconv.Atoi(s)
		if err != nil {
			return 0, err
		}
		return n, nil
	}
	return int(total), nil
}
`

	return os.WriteFile(filepath.Join(sdkDir, "pagination.go"), []byte(code), 0o644)
}
