package sdk

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// RedactGenerator produces a credential redaction utility for the target app.
type RedactGenerator struct {
	outputDir string
}

// NewRedactGenerator creates a redaction generator.
func NewRedactGenerator(outputDir string) *RedactGenerator {
	return &RedactGenerator{outputDir: outputDir}
}

// Generate writes the redaction utility file.
func (g *RedactGenerator) Generate() error {
	authDir := filepath.Join(g.outputDir, "internal", "auth")
	if err := os.MkdirAll(authDir, 0o755); err != nil {
		return err
	}

	code := `// Code generated by Cliford. DO NOT EDIT outside custom code regions.
package auth

import (
	"net/http"
	"strings"
)

// sensitiveHeaders lists HTTP headers whose values must be redacted in output.
var sensitiveHeaders = []string{
	"authorization",
	"x-api-key",
	"cookie",
	"set-cookie",
	"proxy-authorization",
}

// sensitivePatterns lists field name patterns that indicate sensitive data.
var sensitivePatterns = []string{
	"token",
	"secret",
	"password",
	"api_key",
	"apikey",
	"access_key",
	"private_key",
	"credential",
}

// RedactHeaders returns a copy of the headers with sensitive values replaced.
func RedactHeaders(h http.Header) http.Header {
	redacted := h.Clone()
	for _, name := range sensitiveHeaders {
		if vals := redacted.Values(name); len(vals) > 0 {
			for i := range vals {
				redacted.Set(name, redactValue(vals[i]))
				if i > 0 {
					redacted.Add(name, redactValue(vals[i]))
				}
			}
		}
	}
	return redacted
}

// RedactString replaces sensitive values in a string with redacted versions.
func RedactString(s string) string {
	result := s
	for _, pattern := range sensitivePatterns {
		if strings.Contains(strings.ToLower(result), pattern) {
			// Simple approach: if the string looks like it contains a secret, truncate
			if len(result) > 12 {
				return result[:4] + "****" + result[len(result)-4:]
			}
			return "****"
		}
	}
	return result
}

func redactValue(v string) string {
	if len(v) <= 8 {
		return "****"
	}
	// Show first 4 and last 4 characters
	return v[:4] + "..." + v[len(v)-4:]
}

// IsSensitiveHeader returns true if the header name is sensitive.
func IsSensitiveHeader(name string) bool {
	lower := strings.ToLower(name)
	for _, h := range sensitiveHeaders {
		if lower == h {
			return true
		}
	}
	return false
}
`

	return os.WriteFile(filepath.Join(authDir, "redact.go"), []byte(code), 0o644)
}

// FormatRedactedRequest returns a string representation of an HTTP request
// with sensitive headers redacted. This is used for debug and dry-run output.
func FormatRedactedRequest(method, url string, headers map[string][]string, body string) string {
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("%s %s\n", method, url))

	sensitive := map[string]bool{
		"authorization":       true,
		"x-api-key":           true,
		"cookie":              true,
		"proxy-authorization": true,
	}

	for k, vals := range headers {
		for _, v := range vals {
			if sensitive[strings.ToLower(k)] {
				if len(v) > 8 {
					v = v[:4] + "..." + v[len(v)-4:]
				} else {
					v = "****"
				}
			}
			sb.WriteString(fmt.Sprintf("%s: %s\n", k, v))
		}
	}

	if body != "" {
		sb.WriteString("\n" + body + "\n")
	}

	return sb.String()
}
