package sdk

import (
	"os"
	"path/filepath"
)

// RetryEnhancer generates retry middleware code for the target app.
type RetryEnhancer struct {
	outputDir string
}

// NewRetryEnhancer creates a retry enhancer.
func NewRetryEnhancer(outputDir string) *RetryEnhancer {
	return &RetryEnhancer{outputDir: outputDir}
}

// Generate produces the retry middleware file for the target app's SDK.
func (r *RetryEnhancer) Generate() error {
	sdkDir := filepath.Join(r.outputDir, "internal", "sdk")
	if err := os.MkdirAll(sdkDir, 0o755); err != nil {
		return err
	}

	code := `// Code generated by Cliford. DO NOT EDIT outside custom code regions.
package sdk

import (
	"fmt"
	"math"
	"math/rand"
	"net/http"
	"strconv"
	"strings"
	"time"
)

// RetryConfig controls retry behavior.
type RetryConfig struct {
	Enabled              bool
	MaxAttempts          int
	InitialInterval      time.Duration
	MaxInterval          time.Duration
	MaxElapsedTime       time.Duration
	Exponent             float64
	Jitter               bool
	StatusCodes          []int
	RetryConnectionErrors bool
}

// DefaultRetryConfig returns sensible retry defaults.
// Defaults: 3 attempts, 1s initial, 30s max interval, no elapsed time cap.
func DefaultRetryConfig() RetryConfig {
	return RetryConfig{
		Enabled:              true,
		MaxAttempts:          3,
		InitialInterval:      1 * time.Second,
		MaxInterval:          30 * time.Second,
		MaxElapsedTime:       0, // 0 = no time limit
		Exponent:             2.0,
		Jitter:               true,
		StatusCodes:          []int{408, 429, 500, 502, 503, 504},
		RetryConnectionErrors: true,
	}
}

// RetryTransport wraps an http.RoundTripper with retry logic.
type RetryTransport struct {
	Base   http.RoundTripper
	Config RetryConfig
}

// RoundTrip implements http.RoundTripper with automatic retries.
func (t *RetryTransport) RoundTrip(req *http.Request) (*http.Response, error) {
	if !t.Config.Enabled {
		return t.base().RoundTrip(req)
	}

	var lastResp *http.Response
	var lastErr error
	startTime := time.Now()

	// Preserve idempotency key across retries
	idempotencyKey := req.Header.Get("Idempotency-Key")

	for attempt := 0; attempt < t.Config.MaxAttempts; attempt++ {
		if attempt > 0 {
			// Check max elapsed time (0 = no limit)
			if t.Config.MaxElapsedTime > 0 && time.Since(startTime) >= t.Config.MaxElapsedTime {
				break
			}

			delay := t.calculateDelay(attempt, lastResp)
			time.Sleep(delay)

			// Restore idempotency key
			if idempotencyKey != "" {
				req.Header.Set("Idempotency-Key", idempotencyKey)
			}
		}

		resp, err := t.base().RoundTrip(req)

		if err != nil {
			lastErr = err
			if !t.Config.RetryConnectionErrors {
				return nil, err
			}
			continue
		}

		if !t.shouldRetry(resp.StatusCode) {
			return resp, nil
		}

		lastResp = resp
		lastErr = fmt.Errorf("HTTP %d after %d attempts", resp.StatusCode, attempt+1)
	}

	if lastResp != nil {
		return lastResp, nil
	}
	return nil, lastErr
}

func (t *RetryTransport) base() http.RoundTripper {
	if t.Base != nil {
		return t.Base
	}
	return http.DefaultTransport
}

func (t *RetryTransport) shouldRetry(statusCode int) bool {
	for _, code := range t.Config.StatusCodes {
		if code == statusCode {
			return true
		}
		// Support wildcard ranges like 5XX
		if code/100 == statusCode/100 && code%100 == 0 {
			return true
		}
	}
	return false
}

func (t *RetryTransport) calculateDelay(attempt int, resp *http.Response) time.Duration {
	// Check Retry-After header first
	if resp != nil {
		if ra := resp.Header.Get("Retry-After"); ra != "" {
			if seconds, err := strconv.Atoi(ra); err == nil {
				return time.Duration(seconds) * time.Second
			}
			if retryTime, err := time.Parse(time.RFC1123, ra); err == nil {
				delay := time.Until(retryTime)
				if delay > 0 {
					return delay
				}
			}
		}

		// Check X-RateLimit-Reset header
		if reset := resp.Header.Get("X-RateLimit-Reset"); reset != "" {
			if resetUnix, err := strconv.ParseInt(reset, 10, 64); err == nil {
				delay := time.Until(time.Unix(resetUnix, 0))
				if delay > 0 && delay <= t.Config.MaxInterval {
					return delay
				}
			}
		}
	}

	// Exponential backoff
	delay := float64(t.Config.InitialInterval) * math.Pow(t.Config.Exponent, float64(attempt))

	// Add jitter (up to 25% randomization)
	if t.Config.Jitter {
		jitter := delay * 0.25 * rand.Float64()
		delay += jitter
	}

	// Cap at max interval
	if time.Duration(delay) > t.Config.MaxInterval {
		delay = float64(t.Config.MaxInterval)
	}

	return time.Duration(delay)
}

// NewRetryClient creates an HTTP client with retry middleware.
func NewRetryClient(cfg RetryConfig) *http.Client {
	return &http.Client{
		Transport: &RetryTransport{
			Base:   http.DefaultTransport,
			Config: cfg,
		},
	}
}

// FormatRetryStatus returns a human-readable retry status string.
func FormatRetryStatus(statusCode, attempts int) string {
	return fmt.Sprintf("HTTP %d (retried %d time%s)",
		statusCode, attempts, pluralize(attempts))
}

func pluralize(n int) string {
	if n == 1 {
		return ""
	}
	return "s"
}

// Ensure unused import is valid
var _ = strings.TrimSpace
`

	return os.WriteFile(filepath.Join(sdkDir, "retry.go"), []byte(code), 0o644)
}
