package sdk

import (
	"fmt"
	"os"
	"path/filepath"
)

// VerboseEnhancer generates the verbose/debug transport for the target app.
type VerboseEnhancer struct {
	outputDir string
	pkgPath   string
}

// NewVerboseEnhancer creates a verbose enhancer.
func NewVerboseEnhancer(outputDir, pkgPath string) *VerboseEnhancer {
	return &VerboseEnhancer{outputDir: outputDir, pkgPath: pkgPath}
}

// Generate produces the verbose transport file for the target app's SDK.
func (v *VerboseEnhancer) Generate() error {
	sdkDir := filepath.Join(v.outputDir, "internal", "sdk")
	if err := os.MkdirAll(sdkDir, 0o755); err != nil {
		return err
	}

	code := fmt.Sprintf(`// Code generated by Cliford. DO NOT EDIT outside custom code regions.
package sdk

import (
	"fmt"
	"io"
	"net/http"
	"net/http/httputil"
	"os"
	"strings"
	"time"
)

// VerboseTransport wraps an http.RoundTripper and logs request/response
// details to stderr when enabled. Sensitive headers are redacted.
type VerboseTransport struct {
	Base    http.RoundTripper
	Enabled *bool // pointer to the --verbose flag variable
}

// RoundTrip implements http.RoundTripper. When verbose mode is enabled,
// it prints the full request and response to stderr with sensitive headers redacted.
func (t *VerboseTransport) RoundTrip(req *http.Request) (*http.Response, error) {
	if t.Enabled == nil || !*t.Enabled {
		return t.base().RoundTrip(req)
	}

	// Print request
	fmt.Fprintf(os.Stderr, "> %%s %%s\n", req.Method, req.URL.String())
	for name, vals := range req.Header {
		for _, v := range vals {
			if isSensitiveHeader(name) {
				v = "[REDACTED]"
			}
			fmt.Fprintf(os.Stderr, "> %%s: %%s\n", name, v)
		}
	}
	if req.Body != nil && req.Body != http.NoBody {
		bodyBytes, err := httputil.DumpRequestOut(req, true)
		if err == nil {
			// Extract just the body (after the double newline)
			parts := strings.SplitN(string(bodyBytes), "\r\n\r\n", 2)
			if len(parts) == 2 && parts[1] != "" {
				fmt.Fprintf(os.Stderr, "> \n> %%s\n", parts[1])
			}
		}
	}
	fmt.Fprintln(os.Stderr, ">")

	start := time.Now()
	resp, err := t.base().RoundTrip(req)
	elapsed := time.Since(start)

	if err != nil {
		fmt.Fprintf(os.Stderr, "< error: %%v (%%s)\n\n", err, elapsed.Round(time.Millisecond))
		return nil, err
	}

	// Print response
	fmt.Fprintf(os.Stderr, "< %%s (%%s)\n", resp.Status, elapsed.Round(time.Millisecond))
	for name, vals := range resp.Header {
		for _, v := range vals {
			fmt.Fprintf(os.Stderr, "< %%s: %%s\n", name, v)
		}
	}

	// Peek at response body for verbose output (without consuming it)
	if resp.Body != nil {
		bodyBytes, readErr := io.ReadAll(resp.Body)
		resp.Body.Close()
		if readErr == nil {
			contentType := resp.Header.Get("Content-Type")
			if strings.Contains(contentType, "octet-stream") || strings.Contains(contentType, "image/") {
				fmt.Fprintf(os.Stderr, "< [binary response, %%d bytes]\n", len(bodyBytes))
			} else if len(bodyBytes) > 0 {
				body := string(bodyBytes)
				if len(body) > 2048 {
					body = body[:2048] + "... (truncated)"
				}
				fmt.Fprintf(os.Stderr, "< \n< %%s\n", body)
			}
			// Restore the body for downstream consumers
			resp.Body = io.NopCloser(strings.NewReader(string(bodyBytes)))
		}
	}
	fmt.Fprintln(os.Stderr)

	return resp, nil
}

func (t *VerboseTransport) base() http.RoundTripper {
	if t.Base != nil {
		return t.Base
	}
	return http.DefaultTransport
}

// isSensitiveHeader returns true if the header value should be redacted.
func isSensitiveHeader(name string) bool {
	lower := strings.ToLower(name)
	sensitiveExact := []string{
		"authorization", "x-api-key", "x-auth-token",
		"proxy-authorization", "cookie", "set-cookie",
	}
	for _, h := range sensitiveExact {
		if lower == h {
			return true
		}
	}
	// Pattern-based: any header containing secret, token, key, or password
	sensitivePatterns := []string{"secret", "token", "key", "password"}
	for _, p := range sensitivePatterns {
		if strings.Contains(lower, p) {
			return true
		}
	}
	return false
}
`)

	return os.WriteFile(filepath.Join(sdkDir, "verbose.go"), []byte(code), 0o644)
}
