// Package tui generates Bubbletea TUI application code from the Operation Registry.
package tui

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/the-inconvenience-store/cliford/pkg/registry"
	"github.com/the-inconvenience-store/cliford/pkg/theme"
)

// Generator produces Bubbletea TUI source files for the generated app.
type Generator struct {
	outputDir string
	appName   string
	pkgPath   string
	theme     theme.Config
}

// NewGenerator creates a TUI generator.
func NewGenerator(outputDir, appName, pkgPath string, thm theme.Config) *Generator {
	return &Generator{
		outputDir: outputDir,
		appName:   appName,
		pkgPath:   pkgPath,
		theme:     thm,
	}
}

// Generate produces all TUI source files.
func (g *Generator) Generate(reg *registry.Registry) error {
	tuiDir := filepath.Join(g.outputDir, "internal", "tui")
	if err := os.MkdirAll(tuiDir, 0o755); err != nil {
		return fmt.Errorf("create TUI dir: %w", err)
	}

	if err := g.generateApp(reg, tuiDir); err != nil {
		return err
	}
	if err := g.generateExplorer(reg, tuiDir); err != nil {
		return err
	}
	if err := g.generateOperation(tuiDir); err != nil {
		return err
	}
	if err := g.generateResponse(tuiDir); err != nil {
		return err
	}
	if err := g.generateTheme(tuiDir); err != nil {
		return err
	}
	if err := g.generateComponents(tuiDir); err != nil {
		return err
	}

	return nil
}

func (g *Generator) generateApp(reg *registry.Registry, tuiDir string) error {
	var sb strings.Builder
	w := func(s string) { sb.WriteString(s + "\n") }

	w("// Code generated by Cliford. DO NOT EDIT outside custom code regions.")
	w("package tui")
	w("")
	w("import (")
	w(`	"fmt"`)
	w("")
	w(`	tea "github.com/charmbracelet/bubbletea"`)
	w(")")
	w("")
	w("// View represents the current screen in the TUI.")
	w("type View int")
	w("")
	w("const (")
	w("	ViewExplorer View = iota")
	w("	ViewOperation")
	w("	ViewResponse")
	w(")")
	w("")
	w("// App is the root Bubbletea model for the TUI application.")
	w("type App struct {")
	w("	currentView View")
	w("	explorer    ExplorerModel")
	w("	operation   OperationModel")
	w("	response    ResponseModel")
	w("	theme       Theme")
	w("	width       int")
	w("	height      int")
	w("	err         error")
	w("}")
	w("")
	w("// NewApp creates a new TUI application.")
	w("func NewApp() App {")
	w("	thm := LoadTheme()")
	w("	return App{")
	w("		currentView: ViewExplorer,")
	w("		explorer:    NewExplorerModel(thm),")
	w("		theme:       thm,")
	w("	}")
	w("}")
	w("")
	w("// Init implements tea.Model.")
	w("func (a App) Init() tea.Cmd {")
	w("	return a.explorer.Init()")
	w("}")
	w("")
	w("// Update implements tea.Model.")
	w("func (a App) Update(msg tea.Msg) (tea.Model, tea.Cmd) {")
	w("	switch msg := msg.(type) {")
	w("	case tea.KeyMsg:")
	w(`		if msg.String() == "q" || msg.String() == "ctrl+c" {`)
	w("			return a, tea.Quit")
	w("		}")
	w(`		if msg.String() == "esc" && a.currentView != ViewExplorer {`)
	w("			a.currentView = ViewExplorer")
	w("			return a, nil")
	w("		}")
	w("	case tea.WindowSizeMsg:")
	w("		a.width = msg.Width")
	w("		a.height = msg.Height")
	w("	case SelectOperationMsg:")
	w("		a.operation = NewOperationModel(msg.Operation, a.theme)")
	w("		a.currentView = ViewOperation")
	w("		return a, a.operation.Init()")
	w("	case ShowResponseMsg:")
	w("		a.response = NewResponseModel(msg.Data, msg.StatusCode, a.theme)")
	w("		a.currentView = ViewResponse")
	w("		return a, nil")
	w("	case ErrorMsg:")
	w("		a.err = msg.Err")
	w("	}")
	w("")
	w("	var cmd tea.Cmd")
	w("	switch a.currentView {")
	w("	case ViewExplorer:")
	w("		var m tea.Model")
	w("		m, cmd = a.explorer.Update(msg)")
	w("		a.explorer = m.(ExplorerModel)")
	w("	case ViewOperation:")
	w("		var m tea.Model")
	w("		m, cmd = a.operation.Update(msg)")
	w("		a.operation = m.(OperationModel)")
	w("	case ViewResponse:")
	w("		var m tea.Model")
	w("		m, cmd = a.response.Update(msg)")
	w("		a.response = m.(ResponseModel)")
	w("	}")
	w("")
	w("	return a, cmd")
	w("}")
	w("")
	w("// View implements tea.Model.")
	w("func (a App) View() string {")
	w("	if a.err != nil {")
	w(`		return a.theme.Error.Render(fmt.Sprintf("Error: %v", a.err))`)
	w("	}")
	w("")
	w("	switch a.currentView {")
	w("	case ViewExplorer:")
	w("		return a.explorer.View()")
	w("	case ViewOperation:")
	w("		return a.operation.View()")
	w("	case ViewResponse:")
	w("		return a.response.View()")
	w("	default:")
	w("		return a.explorer.View()")
	w("	}")
	w("}")
	w("")
	w("// Run starts the TUI application.")
	w("func Run() error {")
	w("	p := tea.NewProgram(NewApp(), tea.WithAltScreen())")
	w("	_, err := p.Run()")
	w("	return err")
	w("}")

	return os.WriteFile(filepath.Join(tuiDir, "app.go"), []byte(sb.String()), 0o644)
}

func (g *Generator) generateExplorer(reg *registry.Registry, tuiDir string) error {
	var sb strings.Builder
	w := func(s string) { sb.WriteString(s + "\n") }

	w("// Code generated by Cliford. DO NOT EDIT outside custom code regions.")
	w("package tui")
	w("")
	w("import (")
	w(`	"strings"`)
	w("")
	w(`	"github.com/charmbracelet/bubbles/list"`)
	w(`	tea "github.com/charmbracelet/bubbletea"`)
	w(")")
	w("")
	w("// OperationItem represents an API operation in the explorer list.")
	w("type OperationItem struct {")
	w("	Name    string")
	w("	Method  string")
	w("	Path    string")
	w("	Summary string")
	w("	Tag     string")
	w("}")
	w("")
	w("func (i OperationItem) Title() string       { return i.Tag + \" > \" + i.Name }")
	w("func (i OperationItem) Description() string { return strings.ToUpper(i.Method) + \" \" + i.Path + \" — \" + i.Summary }")
	w("func (i OperationItem) FilterValue() string { return i.Name + \" \" + i.Tag + \" \" + i.Summary }")
	w("")
	w("// SelectOperationMsg is sent when the user selects an operation.")
	w("type SelectOperationMsg struct {")
	w("	Operation OperationItem")
	w("}")
	w("")
	w("// ExplorerModel is the Bubbletea model for the operation explorer.")
	w("type ExplorerModel struct {")
	w("	list  list.Model")
	w("	theme Theme")
	w("}")
	w("")
	w("// NewExplorerModel creates the explorer with all available operations.")
	w("func NewExplorerModel(thm Theme) ExplorerModel {")
	w("	items := []list.Item{")

	// Generate operation items from registry
	for tag, ops := range reg.TagGroups {
		for _, op := range ops {
			w(fmt.Sprintf("		OperationItem{Name: %q, Method: %q, Path: %q, Summary: %q, Tag: %q},",
				op.CLICommandName, op.Method, op.Path, op.Summary, tag))
		}
	}

	w("	}")
	w("")
	w(fmt.Sprintf("	l := list.New(items, list.NewDefaultDelegate(), 80, 24)"))
	w(fmt.Sprintf("	l.Title = %q", g.appName+" — API Explorer"))
	w("	l.SetShowStatusBar(true)")
	w("	l.SetFilteringEnabled(true)")
	w("")
	w("	return ExplorerModel{list: l, theme: thm}")
	w("}")
	w("")
	w("func (m ExplorerModel) Init() tea.Cmd { return nil }")
	w("")
	w("func (m ExplorerModel) Update(msg tea.Msg) (tea.Model, tea.Cmd) {")
	w("	switch msg := msg.(type) {")
	w("	case tea.KeyMsg:")
	w(`		if msg.String() == "enter" {`)
	w("			if item, ok := m.list.SelectedItem().(OperationItem); ok {")
	w("				return m, func() tea.Msg { return SelectOperationMsg{Operation: item} }")
	w("			}")
	w("		}")
	w("	case tea.WindowSizeMsg:")
	w("		m.list.SetSize(msg.Width, msg.Height-2)")
	w("	}")
	w("")
	w("	var cmd tea.Cmd")
	w("	m.list, cmd = m.list.Update(msg)")
	w("	return m, cmd")
	w("}")
	w("")
	w("func (m ExplorerModel) View() string {")
	w("	return m.list.View()")
	w("}")

	return os.WriteFile(filepath.Join(tuiDir, "explorer.go"), []byte(sb.String()), 0o644)
}

func (g *Generator) generateOperation(tuiDir string) error {
	code := `// Code generated by Cliford. DO NOT EDIT outside custom code regions.
package tui

import (
	"fmt"

	"github.com/charmbracelet/bubbles/textinput"
	tea "github.com/charmbracelet/bubbletea"
)

// ShowResponseMsg is sent when an API response is received.
type ShowResponseMsg struct {
	Data       string
	StatusCode int
}

// ErrorMsg is sent when an error occurs.
type ErrorMsg struct {
	Err error
}

// OperationModel handles parameter input for an operation.
type OperationModel struct {
	operation OperationItem
	inputs    []textinput.Model
	focused   int
	theme     Theme
	submitted bool
}

// NewOperationModel creates a form for the given operation.
func NewOperationModel(op OperationItem, thm Theme) OperationModel {
	// Create a basic text input for demonstration
	ti := textinput.New()
	ti.Placeholder = "Enter parameters as JSON..."
	ti.Focus()
	ti.CharLimit = 1024
	ti.Width = 60

	return OperationModel{
		operation: op,
		inputs:    []textinput.Model{ti},
		theme:     thm,
	}
}

func (m OperationModel) Init() tea.Cmd {
	return textinput.Blink
}

func (m OperationModel) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
	switch msg := msg.(type) {
	case tea.KeyMsg:
		switch msg.String() {
		case "enter":
			if !m.submitted {
				m.submitted = true
				return m, func() tea.Msg {
					return ShowResponseMsg{
						Data:       fmt.Sprintf("{\"message\": \"Request sent to %s %s\"}", m.operation.Method, m.operation.Path),
						StatusCode: 200,
					}
				}
			}
		}
	}

	if len(m.inputs) > 0 {
		var cmd tea.Cmd
		m.inputs[m.focused], cmd = m.inputs[m.focused].Update(msg)
		return m, cmd
	}
	return m, nil
}

func (m OperationModel) View() string {
	s := m.theme.Title.Render(fmt.Sprintf("%s %s", m.operation.Method, m.operation.Path))
	s += "\n" + m.theme.Subtle.Render(m.operation.Summary)
	s += "\n\n"

	if len(m.inputs) > 0 {
		s += m.inputs[m.focused].View()
	}

	s += "\n\n" + m.theme.Subtle.Render("[enter] submit  [esc] back  [q] quit")
	return s
}
`
	return os.WriteFile(filepath.Join(tuiDir, "operation.go"), []byte(code), 0o644)
}

func (g *Generator) generateResponse(tuiDir string) error {
	code := `// Code generated by Cliford. DO NOT EDIT outside custom code regions.
package tui

import (
	"fmt"

	"github.com/charmbracelet/bubbles/viewport"
	tea "github.com/charmbracelet/bubbletea"
)

// ResponseModel displays an API response in a scrollable viewport.
type ResponseModel struct {
	viewport   viewport.Model
	data       string
	statusCode int
	theme      Theme
}

// NewResponseModel creates a response viewer.
func NewResponseModel(data string, statusCode int, thm Theme) ResponseModel {
	vp := viewport.New(80, 20)
	vp.SetContent(data)

	return ResponseModel{
		viewport:   vp,
		data:       data,
		statusCode: statusCode,
		theme:      thm,
	}
}

func (m ResponseModel) Init() tea.Cmd { return nil }

func (m ResponseModel) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
	switch msg := msg.(type) {
	case tea.WindowSizeMsg:
		m.viewport.Width = msg.Width
		m.viewport.Height = msg.Height - 4
	}

	var cmd tea.Cmd
	m.viewport, cmd = m.viewport.Update(msg)
	return m, cmd
}

func (m ResponseModel) View() string {
	statusStyle := m.theme.Success
	if m.statusCode >= 400 {
		statusStyle = m.theme.Error
	}

	header := statusStyle.Render(fmt.Sprintf("HTTP %d", m.statusCode))
	footer := m.theme.Subtle.Render("[↑/↓] scroll  [esc] back  [q] quit")

	return header + "\n\n" + m.viewport.View() + "\n\n" + footer
}
`
	return os.WriteFile(filepath.Join(tuiDir, "response.go"), []byte(code), 0o644)
}

func (g *Generator) generateTheme(tuiDir string) error {
	var sb strings.Builder
	w := func(s string) { sb.WriteString(s + "\n") }

	w("// Code generated by Cliford. DO NOT EDIT outside custom code regions.")
	w("package tui")
	w("")
	w("import (")
	w(`	"github.com/charmbracelet/lipgloss"`)
	w(")")
	w("")
	w("// Theme holds all Lipgloss styles for the TUI.")
	w("type Theme struct {")
	w("	Title   lipgloss.Style")
	w("	Subtle  lipgloss.Style")
	w("	Error   lipgloss.Style")
	w("	Success lipgloss.Style")
	w("	Warning lipgloss.Style")
	w("	Accent  lipgloss.Style")
	w("	Border  lipgloss.Border")
	w("}")
	w("")
	w("// LoadTheme creates a Theme from the configured colors.")
	w("func LoadTheme() Theme {")
	w(fmt.Sprintf("	return Theme{"))
	w(fmt.Sprintf("		Title:   lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color(%q)),", g.theme.Colors.Primary))
	w(fmt.Sprintf("		Subtle:  lipgloss.NewStyle().Foreground(lipgloss.Color(%q)),", g.theme.Colors.Dimmed))
	w(fmt.Sprintf("		Error:   lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color(%q)),", g.theme.Colors.Error))
	w(fmt.Sprintf("		Success: lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color(%q)),", g.theme.Colors.Success))
	w(fmt.Sprintf("		Warning: lipgloss.NewStyle().Foreground(lipgloss.Color(%q)),", g.theme.Colors.Warning))
	w(fmt.Sprintf("		Accent:  lipgloss.NewStyle().Foreground(lipgloss.Color(%q)),", g.theme.Colors.Accent))

	switch g.theme.Borders {
	case theme.BorderRounded:
		w("		Border:  lipgloss.RoundedBorder(),")
	case theme.BorderThick:
		w("		Border:  lipgloss.ThickBorder(),")
	case theme.BorderDouble:
		w("		Border:  lipgloss.DoubleBorder(),")
	default:
		w("		Border:  lipgloss.NormalBorder(),")
	}

	w("	}")
	w("}")

	return os.WriteFile(filepath.Join(tuiDir, "theme.go"), []byte(sb.String()), 0o644)
}

func (g *Generator) generateComponents(tuiDir string) error {
	code := `// Code generated by Cliford. DO NOT EDIT outside custom code regions.
package tui

import (
	"github.com/charmbracelet/lipgloss"
)

// StatusBar renders the bottom status bar showing active profile and server.
func StatusBar(profile, server string, thm Theme) string {
	style := lipgloss.NewStyle().
		Background(lipgloss.Color("#333333")).
		Foreground(lipgloss.Color("#EEEEEE")).
		Padding(0, 1)

	return style.Render("Profile: " + profile + "  |  Server: " + server)
}

// ErrorBar renders an error notification at the bottom of the screen.
func ErrorBar(errMsg string, thm Theme) string {
	style := lipgloss.NewStyle().
		BorderStyle(thm.Border).
		Padding(0, 1)

	return style.Render(thm.Error.Render("Error: " + errMsg))
}

// HelpBar renders the keybinding help bar.
func HelpBar(bindings map[string]string, thm Theme) string {
	s := ""
	for key, desc := range bindings {
		s += thm.Accent.Render("["+key+"]") + " " + thm.Subtle.Render(desc) + "  "
	}
	return s
}
`
	return os.WriteFile(filepath.Join(tuiDir, "components.go"), []byte(code), 0o644)
}
