// Package tui generates Bubbletea TUI application code from the Operation Registry.
package tui

import (
	"fmt"
	goformat "go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/the-inconvenience-store/cliford/pkg/registry"
	"github.com/the-inconvenience-store/cliford/pkg/theme"
)

// Generator produces Bubbletea TUI source files for the generated app.
type Generator struct {
	outputDir string
	appName   string
	pkgPath   string
	theme     theme.Config
}

// NewGenerator creates a TUI generator.
func NewGenerator(outputDir, appName, pkgPath string, thm theme.Config) *Generator {
	return &Generator{
		outputDir: outputDir,
		appName:   appName,
		pkgPath:   pkgPath,
		theme:     thm,
	}
}

// Generate produces all TUI source files.
func (g *Generator) Generate(reg *registry.Registry) error {
	tuiDir := filepath.Join(g.outputDir, "internal", "tui")
	if err := os.MkdirAll(tuiDir, 0o755); err != nil {
		return fmt.Errorf("create TUI dir: %w", err)
	}

	if err := g.generateApp(reg, tuiDir); err != nil {
		return err
	}
	if err := g.generateExplorer(reg, tuiDir); err != nil {
		return err
	}
	if err := g.generateOperation(tuiDir); err != nil {
		return err
	}
	if err := g.generateResponse(tuiDir); err != nil {
		return err
	}
	if err := g.generateTheme(tuiDir); err != nil {
		return err
	}
	if err := g.generateComponents(tuiDir); err != nil {
		return err
	}

	return nil
}

func (g *Generator) generateApp(reg *registry.Registry, tuiDir string) error {
	var sb strings.Builder
	w := func(s string) { sb.WriteString(s + "\n") }

	w("// Code generated by Cliford. DO NOT EDIT outside custom code regions.")
	w("package tui")
	w("")
	w("import (")
	w(`	"fmt"`)
	w("")
	w(`	tea "github.com/charmbracelet/bubbletea"`)
	w(")")
	w("")
	w("// View represents the current screen in the TUI.")
	w("type View int")
	w("")
	w("const (")
	w("	ViewExplorer View = iota")
	w("	ViewOperation")
	w("	ViewResponse")
	w(")")
	w("")
	w("// App is the root Bubbletea model for the TUI application.")
	w("type App struct {")
	w("	currentView View")
	w("	explorer    ExplorerModel")
	w("	operation   OperationModel")
	w("	response    ResponseModel")
	w("	theme       Theme")
	w("	width       int")
	w("	height      int")
	w("	err         error")
	w("}")
	w("")
	w("// NewApp creates a new TUI application.")
	w("func NewApp() App {")
	w("	thm := LoadTheme()")
	w("	return App{")
	w("		currentView: ViewExplorer,")
	w("		explorer:    NewExplorerModel(thm),")
	w("		theme:       thm,")
	w("	}")
	w("}")
	w("")
	w("// Init implements tea.Model.")
	w("func (a App) Init() tea.Cmd {")
	w("	return a.explorer.Init()")
	w("}")
	w("")
	w("// Update implements tea.Model.")
	w("func (a App) Update(msg tea.Msg) (tea.Model, tea.Cmd) {")
	w("	switch msg := msg.(type) {")
	w("	case tea.KeyMsg:")
	w(`		if msg.String() == "q" || msg.String() == "ctrl+c" {`)
	w("			return a, tea.Quit")
	w("		}")
	w(`		if msg.String() == "esc" && a.currentView != ViewExplorer {`)
	w("			a.currentView = ViewExplorer")
	w("			return a, nil")
	w("		}")
	w("	case tea.WindowSizeMsg:")
	w("		a.width = msg.Width")
	w("		a.height = msg.Height")
	w("	case SelectOperationMsg:")
	w("		a.operation = NewOperationModel(msg.Operation, a.theme)")
	w("		a.currentView = ViewOperation")
	w("		return a, a.operation.Init()")
	w("	case ShowResponseMsg:")
	w("		a.response = NewResponseModel(msg.Data, msg.StatusCode, a.theme)")
	w("		a.currentView = ViewResponse")
	w("		return a, nil")
	w("	case ErrorMsg:")
	w("		a.err = msg.Err")
	w("	}")
	w("")
	w("	var cmd tea.Cmd")
	w("	switch a.currentView {")
	w("	case ViewExplorer:")
	w("		var m tea.Model")
	w("		m, cmd = a.explorer.Update(msg)")
	w("		a.explorer = m.(ExplorerModel)")
	w("	case ViewOperation:")
	w("		var m tea.Model")
	w("		m, cmd = a.operation.Update(msg)")
	w("		a.operation = m.(OperationModel)")
	w("	case ViewResponse:")
	w("		var m tea.Model")
	w("		m, cmd = a.response.Update(msg)")
	w("		a.response = m.(ResponseModel)")
	w("	}")
	w("")
	w("	return a, cmd")
	w("}")
	w("")
	w("// View implements tea.Model.")
	w("func (a App) View() string {")
	w("	if a.err != nil {")
	w(`		return a.theme.Error.Render(fmt.Sprintf("Error: %v", a.err))`)
	w("	}")
	w("")
	w("	switch a.currentView {")
	w("	case ViewExplorer:")
	w("		return a.explorer.View()")
	w("	case ViewOperation:")
	w("		return a.operation.View()")
	w("	case ViewResponse:")
	w("		return a.response.View()")
	w("	default:")
	w("		return a.explorer.View()")
	w("	}")
	w("}")
	w("")
	w("// Run starts the TUI application.")
	w("func Run() error {")
	w("	p := tea.NewProgram(NewApp(), tea.WithAltScreen())")
	w("	_, err := p.Run()")
	w("	return err")
	w("}")

	return os.WriteFile(filepath.Join(tuiDir, "app.go"), []byte(sb.String()), 0o644)
}

func (g *Generator) generateExplorer(reg *registry.Registry, tuiDir string) error {
	var sb strings.Builder
	w := func(s string) { sb.WriteString(s + "\n") }

	w("// Code generated by Cliford. DO NOT EDIT outside custom code regions.")
	w("package tui")
	w("")
	w("import (")
	w(`	"strings"`)
	w("")
	w(`	"github.com/charmbracelet/bubbles/list"`)
	w(`	tea "github.com/charmbracelet/bubbletea"`)
	w(")")
	w("")
	w("// OperationItem represents an API operation in the explorer list.")
	w("type OperationItem struct {")
	w("	Name    string")
	w("	Method  string")
	w("	Path    string")
	w("	Summary string")
	w("	Tag     string")
	w("	BaseURL string")
	w("	Fields  []FieldDef")
	w("}")
	w("")
	w("func (i OperationItem) Title() string { return i.Tag + \" > \" + i.Name }")
	w("func (i OperationItem) Description() string {")
	w("	return strings.ToUpper(i.Method) + \" \" + i.Path + \" — \" + i.Summary")
	w("}")
	w("func (i OperationItem) FilterValue() string { return i.Name + \" \" + i.Tag + \" \" + i.Summary }")
	w("")
	w("// SelectOperationMsg is sent when the user selects an operation.")
	w("type SelectOperationMsg struct {")
	w("	Operation OperationItem")
	w("}")
	w("")
	w("// ExplorerModel is the Bubbletea model for the operation explorer.")
	w("type ExplorerModel struct {")
	w("	list  list.Model")
	w("	theme Theme")
	w("}")
	w("")
	w("// NewExplorerModel creates the explorer with all available operations.")
	w("func NewExplorerModel(thm Theme) ExplorerModel {")
	w("	items := []list.Item{")

	// Determine base URL (use first server)
	baseURL := ""
	if len(reg.Servers) > 0 {
		baseURL = reg.Servers[0].URL
	}

	// Sort tags for deterministic output
	tags := make([]string, 0, len(reg.TagGroups))
	for tag := range reg.TagGroups {
		tags = append(tags, tag)
	}
	sort.Strings(tags)

	for _, tag := range tags {
		ops := reg.TagGroups[tag]
		for _, op := range ops {
			fieldDefs := g.buildFieldDefs(op)
			var fieldLiterals []string
			for _, fd := range fieldDefs {
				fieldLiterals = append(fieldLiterals, fd)
			}

			fieldsCode := "nil"
			if len(fieldLiterals) > 0 {
				fieldsCode = "[]FieldDef{\n"
				for _, fl := range fieldLiterals {
					fieldsCode += "\t\t\t" + fl + ",\n"
				}
				fieldsCode += "\t\t}"
			}
			w(fmt.Sprintf("\t\tOperationItem{Name: %q, Method: %q, Path: %q, Summary: %q, Tag: %q, BaseURL: %q, Fields: %s},",
				op.CLICommandName, op.Method, op.Path, op.Summary, tag, baseURL, fieldsCode))
		}
	}

	w("	}")
	w("")
	w(fmt.Sprintf("	l := list.New(items, list.NewDefaultDelegate(), 80, 24)"))
	w(fmt.Sprintf("	l.Title = %q", g.appName+" — API Explorer"))
	w("	l.SetShowStatusBar(true)")
	w("	l.SetFilteringEnabled(true)")
	w("")
	w("	return ExplorerModel{list: l, theme: thm}")
	w("}")
	w("")
	w("func (m ExplorerModel) Init() tea.Cmd { return nil }")
	w("")
	w("func (m ExplorerModel) Update(msg tea.Msg) (tea.Model, tea.Cmd) {")
	w("	switch msg := msg.(type) {")
	w("	case tea.KeyMsg:")
	w(`		if msg.String() == "enter" {`)
	w("			if item, ok := m.list.SelectedItem().(OperationItem); ok {")
	w("				return m, func() tea.Msg { return SelectOperationMsg{Operation: item} }")
	w("			}")
	w("		}")
	w("	case tea.WindowSizeMsg:")
	w("		m.list.SetSize(msg.Width, msg.Height-2)")
	w("	}")
	w("")
	w("	var cmd tea.Cmd")
	w("	m.list, cmd = m.list.Update(msg)")
	w("	return m, cmd")
	w("}")
	w("")
	w("func (m ExplorerModel) View() string {")
	w("	return m.list.View()")
	w("}")

	return writeTUIFormatted(filepath.Join(tuiDir, "explorer.go"), sb.String())
}

// buildFieldDefs builds the FieldDef Go literals for an operation's parameters and body.
func (g *Generator) buildFieldDefs(op registry.OperationMeta) []string {
	var defs []string

	// Parameters (path, query, header — skip cookie for TUI)
	for _, p := range op.Parameters {
		if p.In == registry.ParamLocationCookie {
			continue
		}
		label := toTUILabel(p.Name)
		kind := tuiFieldKind(p.Schema, p.Enum)
		loc := tuiFieldLocation(p.In)
		placeholder := p.Description
		required := p.Required

		var opts []string
		for _, e := range p.Enum {
			opts = append(opts, fmt.Sprintf("%v", e))
		}
		defVal := ""
		if p.Default != nil {
			defVal = fmt.Sprintf("%v", p.Default)
		}
		defs = append(defs, fmtFieldDef(p.Name, label, kind, loc, required, placeholder, opts, defVal))
	}

	// Body properties
	if op.RequestBody != nil && len(op.RequestBody.Schema.Properties) > 0 {
		props := op.RequestBody.Schema.Properties
		requiredSet := make(map[string]bool)
		for _, r := range op.RequestBody.Schema.Required {
			requiredSet[r] = true
		}

		// Sort keys for deterministic output
		propNames := make([]string, 0, len(props))
		for k := range props {
			propNames = append(propNames, k)
		}
		sort.Strings(propNames)

		for _, propName := range propNames {
			propSchema := props[propName]
			label := toTUILabel(propName)
			kind := tuiFieldKind(propSchema, propSchema.Enum)
			placeholder := propSchema.Description
			req := requiredSet[propName]

			var opts []string
			for _, e := range propSchema.Enum {
				opts = append(opts, fmt.Sprintf("%v", e))
			}
			defs = append(defs, fmtFieldDef(propName, label, kind, "FieldInBody", req, placeholder, opts, ""))
		}
	}

	return defs
}

// fmtFieldDef returns a Go struct literal for a FieldDef.
func fmtFieldDef(name, label, kind, location string, required bool, placeholder string, options []string, defaultVal string) string {
	optStr := "nil"
	if len(options) > 0 {
		quoted := make([]string, len(options))
		for i, o := range options {
			quoted[i] = fmt.Sprintf("%q", o)
		}
		optStr = "[]string{" + strings.Join(quoted, ", ") + "}"
	}
	return fmt.Sprintf(`{Name: %q, Label: %q, Kind: %s, Location: %s, Required: %v, Placeholder: %q, Options: %s, Default: %q}`,
		name, label, kind, location, required, placeholder, optStr, defaultVal)
}

// tuiFieldKind maps a schema type/format to a FieldKind constant name.
func tuiFieldKind(schema registry.SchemaMeta, enumVals []any) string {
	if len(enumVals) > 0 || len(schema.Enum) > 0 {
		return "FieldKindEnum"
	}
	switch schema.Type {
	case "integer", "number":
		return "FieldKindNumber"
	case "boolean":
		return "FieldKindBool"
	default: // string
		switch schema.Format {
		case "email":
			return "FieldKindEmail"
		case "date", "date-time":
			return "FieldKindDate"
		}
		return "FieldKindText"
	}
}

// tuiFieldLocation maps a ParamLocation to a FieldLocation constant name.
func tuiFieldLocation(in registry.ParamLocation) string {
	switch in {
	case registry.ParamLocationPath:
		return "FieldInPath"
	case registry.ParamLocationQuery:
		return "FieldInQuery"
	case registry.ParamLocationHeader:
		return "FieldInHeader"
	default:
		return "FieldInQuery"
	}
}

// toTUILabel converts a property/param name to a human-readable label.
func toTUILabel(name string) string {
	if len(name) == 0 {
		return name
	}
	var result strings.Builder
	result.WriteByte(strings.ToUpper(name[:1])[0])
	for i := 1; i < len(name); i++ {
		c := name[i]
		if c == '_' || c == '-' {
			result.WriteByte(' ')
			if i+1 < len(name) {
				result.WriteByte(strings.ToUpper(string(name[i+1]))[0])
				i++
			}
		} else if c >= 'A' && c <= 'Z' {
			result.WriteByte(' ')
			result.WriteByte(c)
		} else {
			result.WriteByte(c)
		}
	}
	return result.String()
}

func (g *Generator) generateOperation(tuiDir string) error {
	var sb strings.Builder
	w := func(s string) { sb.WriteString(s + "\n") }

	w("// Code generated by Cliford. DO NOT EDIT outside custom code regions.")
	w("package tui")
	w("")
	w("import (")
	w(`	"bytes"`)
	w(`	"encoding/json"`)
	w(`	"fmt"`)
	w(`	"io"`)
	w(`	"net/http"`)
	w(`	"net/url"`)
	w(`	"strings"`)
	w(`	"time"`)
	w("")
	w(`	"github.com/charmbracelet/bubbles/textinput"`)
	w(`	tea "github.com/charmbracelet/bubbletea"`)
	w(`	"github.com/spf13/viper"`)
	w(")")
	w("")
	w("// FieldKind describes the type of a form field.")
	w("type FieldKind int")
	w("")
	w("const (")
	w("	FieldKindText     FieldKind = iota // plain string")
	w("	FieldKindNumber                    // integer or number")
	w("	FieldKindBool                      // boolean (true/false)")
	w("	FieldKindEnum                      // string with allowed values")
	w("	FieldKindEmail                     // string with email format")
	w("	FieldKindDate                      // string with date/date-time format")
	w(")")
	w("")
	w("// FieldLocation indicates where a parameter is sent in the request.")
	w("type FieldLocation int")
	w("")
	w("const (")
	w("	FieldInPath   FieldLocation = iota")
	w("	FieldInQuery")
	w("	FieldInBody")
	w("	FieldInHeader")
	w(")")
	w("")
	w("// FieldDef describes a single form field.")
	w("type FieldDef struct {")
	w("	Name        string")
	w("	Label       string")
	w("	Kind        FieldKind")
	w("	Location    FieldLocation")
	w("	Required    bool")
	w("	Placeholder string")
	w("	Options     []string // non-nil for FieldKindEnum")
	w("	Default     string")
	w("}")
	w("")
	w("// FormField is a form field with its current textinput state.")
	w("type FormField struct {")
	w("	def   FieldDef")
	w("	input textinput.Model")
	w("}")
	w("")
	w("// ShowResponseMsg is sent when an API response is received.")
	w("type ShowResponseMsg struct {")
	w("	Data       string")
	w("	StatusCode int")
	w("}")
	w("")
	w("// ErrorMsg is sent when an error occurs.")
	w("type ErrorMsg struct {")
	w("	Err error")
	w("}")
	w("")
	w("// OperationModel handles parameter input for an operation.")
	w("type OperationModel struct {")
	w("	operation OperationItem")
	w("	fields    []FormField")
	w("	focused   int")
	w("	theme     Theme")
	w("	validErr  string")
	w("}")
	w("")
	w("// NewOperationModel creates a form for the given operation.")
	w("func NewOperationModel(op OperationItem, thm Theme) OperationModel {")
	w("	fields := make([]FormField, len(op.Fields))")
	w("	for i, def := range op.Fields {")
	w("		ti := textinput.New()")
	w("		ti.Width = 60")
	w("		ti.CharLimit = 512")
	w("		switch def.Kind {")
	w("		case FieldKindEnum:")
	w(`			ti.Placeholder = strings.Join(def.Options, " | ")`)
	w("		case FieldKindBool:")
	w(`			ti.Placeholder = "true | false"`)
	w("		case FieldKindNumber:")
	w(`			ti.Placeholder = "number"`)
	w("		case FieldKindEmail:")
	w(`			ti.Placeholder = "email@example.com"`)
	w("		case FieldKindDate:")
	w(`			ti.Placeholder = "YYYY-MM-DD"`)
	w("		default:")
	w("			if def.Placeholder != \"\" {")
	w("				ti.Placeholder = def.Placeholder")
	w("			} else {")
	w(`				ti.Placeholder = "Enter " + def.Label`)
	w("			}")
	w("		}")
	w("		if def.Default != \"\" {")
	w("			ti.SetValue(def.Default)")
	w("		}")
	w("		fields[i] = FormField{def: def, input: ti}")
	w("	}")
	w("	if len(fields) > 0 {")
	w("		fields[0].input.Focus()")
	w("	}")
	w("	return OperationModel{operation: op, fields: fields, theme: thm}")
	w("}")
	w("")
	w("func (m OperationModel) Init() tea.Cmd {")
	w("	return textinput.Blink")
	w("}")
	w("")
	w("func (m OperationModel) Update(msg tea.Msg) (tea.Model, tea.Cmd) {")
	w("	switch msg := msg.(type) {")
	w("	case tea.KeyMsg:")
	w("		switch msg.String() {")
	w(`		case "tab", "down":`)
	w("			if len(m.fields) > 0 {")
	w("				m.fields[m.focused].input.Blur()")
	w("				m.focused = (m.focused + 1) % len(m.fields)")
	w("				m.fields[m.focused].input.Focus()")
	w("			}")
	w("			return m, textinput.Blink")
	w(`		case "shift+tab", "up":`)
	w("			if len(m.fields) > 0 {")
	w("				m.fields[m.focused].input.Blur()")
	w("				m.focused = (m.focused - 1 + len(m.fields)) % len(m.fields)")
	w("				m.fields[m.focused].input.Focus()")
	w("			}")
	w("			return m, textinput.Blink")
	w(`		case "enter":`)
	w("			if len(m.fields) > 0 && m.focused < len(m.fields)-1 {")
	w("				// advance to next field")
	w("				m.fields[m.focused].input.Blur()")
	w("				m.focused++")
	w("				m.fields[m.focused].input.Focus()")
	w("				return m, textinput.Blink")
	w("			}")
	w("			// on last field (or no fields): submit")
	w("			if err := m.validate(); err != nil {")
	w("				m.validErr = err.Error()")
	w("				return m, nil")
	w("			}")
	w("			m.validErr = \"\"")
	w("			return m, m.submitCmd()")
	w(`		case "ctrl+s":`)
	w("			if err := m.validate(); err != nil {")
	w("				m.validErr = err.Error()")
	w("				return m, nil")
	w("			}")
	w("			m.validErr = \"\"")
	w("			return m, m.submitCmd()")
	w("		}")
	w("	}")
	w("")
	w("	if len(m.fields) > 0 {")
	w("		var cmd tea.Cmd")
	w("		m.fields[m.focused].input, cmd = m.fields[m.focused].input.Update(msg)")
	w("		return m, cmd")
	w("	}")
	w("	return m, nil")
	w("}")
	w("")
	w("func (m OperationModel) validate() error {")
	w("	for _, f := range m.fields {")
	w("		val := strings.TrimSpace(f.input.Value())")
	w("		if f.def.Required && val == \"\" {")
	w(`			return fmt.Errorf("%s is required", f.def.Label)`)
	w("		}")
	w("		if f.def.Kind == FieldKindEnum && val != \"\" {")
	w("			found := false")
	w("			for _, opt := range f.def.Options {")
	w("				if opt == val {")
	w("					found = true")
	w("					break")
	w("				}")
	w("			}")
	w("			if !found {")
	w(`				return fmt.Errorf("%s must be one of: %s", f.def.Label, strings.Join(f.def.Options, ", "))`)
	w("			}")
	w("		}")
	w("	}")
	w("	return nil")
	w("}")
	w("")
	w("func (m OperationModel) submitCmd() tea.Cmd {")
	w("	// Capture field values for the goroutine")
	w("	fields := make([]FormField, len(m.fields))")
	w("	copy(fields, m.fields)")
	w("	op := m.operation")
	w("")
	w("	return func() tea.Msg {")
	w("		// Build URL with path params substituted")
	w("		reqPath := op.Path")
	w("		for _, f := range fields {")
	w("			if f.def.Location == FieldInPath && f.input.Value() != \"\" {")
	w(`				reqPath = strings.ReplaceAll(reqPath, "{"+f.def.Name+"}", f.input.Value())`)
	w("			}")
	w("		}")
	w("")
	w("		baseURL := op.BaseURL")
	w(`		if override := viper.GetString("server_url"); override != "" {`)
	w("			baseURL = override")
	w("		}")
	w("		reqURL, err := url.Parse(baseURL + reqPath)")
	w("		if err != nil {")
	w(`			return ErrorMsg{Err: fmt.Errorf("invalid URL: %w", err)}`)
	w("		}")
	w("")
	w("		// Add query params")
	w("		q := reqURL.Query()")
	w("		for _, f := range fields {")
	w("			if f.def.Location == FieldInQuery && f.input.Value() != \"\" {")
	w("				q.Set(f.def.Name, f.input.Value())")
	w("			}")
	w("		}")
	w("		reqURL.RawQuery = q.Encode()")
	w("")
	w("		// Build request body from body fields")
	w("		var reqBody io.Reader")
	w("		bodyFields := map[string]any{}")
	w("		for _, f := range fields {")
	w("			if f.def.Location == FieldInBody && f.input.Value() != \"\" {")
	w("				bodyFields[f.def.Name] = f.input.Value()")
	w("			}")
	w("		}")
	w("		if len(bodyFields) > 0 {")
	w("			b, _ := json.Marshal(bodyFields)")
	w("			reqBody = bytes.NewReader(b)")
	w("		}")
	w("")
	w("		req, err := http.NewRequest(op.Method, reqURL.String(), reqBody)")
	w("		if err != nil {")
	w(`			return ErrorMsg{Err: fmt.Errorf("create request: %w", err)}`)
	w("		}")
	w("		if reqBody != nil {")
	w(`			req.Header.Set("Content-Type", "application/json")`)
	w("		}")
	w("		for _, f := range fields {")
	w("			if f.def.Location == FieldInHeader && f.input.Value() != \"\" {")
	w("				req.Header.Set(f.def.Name, f.input.Value())")
	w("			}")
	w("		}")
	w("")
	w("		client := &http.Client{Timeout: 30 * time.Second}")
	w("		resp, err := client.Do(req)")
	w("		if err != nil {")
	w(`			return ErrorMsg{Err: fmt.Errorf("request failed: %w", err)}`)
	w("		}")
	w("		defer resp.Body.Close()")
	w("")
	w("		respBody, _ := io.ReadAll(resp.Body)")
	w("		return ShowResponseMsg{Data: string(respBody), StatusCode: resp.StatusCode}")
	w("	}")
	w("}")
	w("")
	w("func (m OperationModel) View() string {")
	w(`	s := m.theme.Title.Render(strings.ToUpper(m.operation.Method) + " " + m.operation.Path)`)
	w("	if m.operation.Summary != \"\" {")
	w("		s += \"\\n\" + m.theme.Subtle.Render(m.operation.Summary)")
	w("	}")
	w("	s += \"\\n\\n\"")
	w("")
	w("	if len(m.fields) == 0 {")
	w(`		s += m.theme.Subtle.Render("No parameters required.")`)
	w(`		s += "\n\n" + m.theme.Subtle.Render("[enter] submit  [esc] back  [q] quit")`)
	w("		return s")
	w("	}")
	w("")
	w("	for i, f := range m.fields {")
	w("		label := f.def.Label")
	w("		if f.def.Required {")
	w(`			label += " *"`)
	w("		}")
	w("		if f.def.Kind == FieldKindEnum && len(f.def.Options) > 0 {")
	w(`			label += "  (" + strings.Join(f.def.Options, " | ") + ")"`)
	w("		}")
	w("		if i == m.focused {")
	w(`			s += m.theme.Accent.Render("› "+label) + "\n"`)
	w("		} else {")
	w(`			s += m.theme.Subtle.Render("  "+label) + "\n"`)
	w("		}")
	w(`		s += "  " + f.input.View() + "\n\n"`)
	w("	}")
	w("")
	w("	if m.validErr != \"\" {")
	w(`		s += m.theme.Error.Render("✗ "+m.validErr) + "\n\n"`)
	w("	}")
	w("")
	w(`	hints := "[tab/↓] next  [shift+tab/↑] prev  [enter] next/submit  [ctrl+s] submit  [esc] back"`)
	w("	s += m.theme.Subtle.Render(hints)")
	w("	return s")
	w("}")

	return writeTUIFormatted(filepath.Join(tuiDir, "operation.go"), sb.String())
}

func (g *Generator) generateResponse(tuiDir string) error {
	code := `// Code generated by Cliford. DO NOT EDIT outside custom code regions.
package tui

import (
	"fmt"

	"github.com/charmbracelet/bubbles/viewport"
	tea "github.com/charmbracelet/bubbletea"
)

// ResponseModel displays an API response in a scrollable viewport.
type ResponseModel struct {
	viewport   viewport.Model
	data       string
	statusCode int
	theme      Theme
}

// NewResponseModel creates a response viewer.
func NewResponseModel(data string, statusCode int, thm Theme) ResponseModel {
	vp := viewport.New(80, 20)
	vp.SetContent(data)

	return ResponseModel{
		viewport:   vp,
		data:       data,
		statusCode: statusCode,
		theme:      thm,
	}
}

func (m ResponseModel) Init() tea.Cmd { return nil }

func (m ResponseModel) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
	switch msg := msg.(type) {
	case tea.WindowSizeMsg:
		m.viewport.Width = msg.Width
		m.viewport.Height = msg.Height - 4
	}

	var cmd tea.Cmd
	m.viewport, cmd = m.viewport.Update(msg)
	return m, cmd
}

func (m ResponseModel) View() string {
	statusStyle := m.theme.Success
	if m.statusCode >= 400 {
		statusStyle = m.theme.Error
	}

	header := statusStyle.Render(fmt.Sprintf("HTTP %d", m.statusCode))
	footer := m.theme.Subtle.Render("[↑/↓] scroll  [esc] back  [q] quit")

	return header + "\n\n" + m.viewport.View() + "\n\n" + footer
}
`
	return os.WriteFile(filepath.Join(tuiDir, "response.go"), []byte(code), 0o644)
}

func (g *Generator) generateTheme(tuiDir string) error {
	var sb strings.Builder
	w := func(s string) { sb.WriteString(s + "\n") }

	w("// Code generated by Cliford. DO NOT EDIT outside custom code regions.")
	w("package tui")
	w("")
	w("import (")
	w(`	"github.com/charmbracelet/lipgloss"`)
	w(")")
	w("")
	w("// Theme holds all Lipgloss styles for the TUI.")
	w("type Theme struct {")
	w("	Title   lipgloss.Style")
	w("	Subtle  lipgloss.Style")
	w("	Error   lipgloss.Style")
	w("	Success lipgloss.Style")
	w("	Warning lipgloss.Style")
	w("	Accent  lipgloss.Style")
	w("	Border  lipgloss.Border")
	w("}")
	w("")
	w("// LoadTheme creates a Theme from the configured colors.")
	w("func LoadTheme() Theme {")
	w(fmt.Sprintf("	return Theme{"))
	w(fmt.Sprintf("		Title:   lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color(%q)),", g.theme.Colors.Primary))
	w(fmt.Sprintf("		Subtle:  lipgloss.NewStyle().Foreground(lipgloss.Color(%q)),", g.theme.Colors.Dimmed))
	w(fmt.Sprintf("		Error:   lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color(%q)),", g.theme.Colors.Error))
	w(fmt.Sprintf("		Success: lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color(%q)),", g.theme.Colors.Success))
	w(fmt.Sprintf("		Warning: lipgloss.NewStyle().Foreground(lipgloss.Color(%q)),", g.theme.Colors.Warning))
	w(fmt.Sprintf("		Accent:  lipgloss.NewStyle().Foreground(lipgloss.Color(%q)),", g.theme.Colors.Accent))

	switch g.theme.Borders {
	case theme.BorderRounded:
		w("		Border:  lipgloss.RoundedBorder(),")
	case theme.BorderThick:
		w("		Border:  lipgloss.ThickBorder(),")
	case theme.BorderDouble:
		w("		Border:  lipgloss.DoubleBorder(),")
	default:
		w("		Border:  lipgloss.NormalBorder(),")
	}

	w("	}")
	w("}")

	return os.WriteFile(filepath.Join(tuiDir, "theme.go"), []byte(sb.String()), 0o644)
}

func (g *Generator) generateComponents(tuiDir string) error {
	code := `// Code generated by Cliford. DO NOT EDIT outside custom code regions.
package tui

import (
	"github.com/charmbracelet/lipgloss"
)

// StatusBar renders the bottom status bar showing active profile and server.
func StatusBar(profile, server string, thm Theme) string {
	style := lipgloss.NewStyle().
		Background(lipgloss.Color("#333333")).
		Foreground(lipgloss.Color("#EEEEEE")).
		Padding(0, 1)

	return style.Render("Profile: " + profile + "  |  Server: " + server)
}

// ErrorBar renders an error notification at the bottom of the screen.
func ErrorBar(errMsg string, thm Theme) string {
	style := lipgloss.NewStyle().
		BorderStyle(thm.Border).
		Padding(0, 1)

	return style.Render(thm.Error.Render("Error: " + errMsg))
}

// HelpBar renders the keybinding help bar.
func HelpBar(bindings map[string]string, thm Theme) string {
	s := ""
	for key, desc := range bindings {
		s += thm.Accent.Render("["+key+"]") + " " + thm.Subtle.Render(desc) + "  "
	}
	return s
}
`
	return os.WriteFile(filepath.Join(tuiDir, "components.go"), []byte(code), 0o644)
}

// writeTUIFormatted formats Go source with gofmt and writes it.
func writeTUIFormatted(path, content string) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("create dir %s: %w", dir, err)
	}
	formatted, err := goformat.Source([]byte(content))
	if err != nil {
		// Write unformatted for debugging
		_ = os.WriteFile(path, []byte(content), 0o644)
		return fmt.Errorf("gofmt %s: %w", path, err)
	}
	return os.WriteFile(path, formatted, 0o644)
}
