package cli

import (
	"os"
	"path/filepath"
)

// AliasCmdGenerator produces the alias management command file for the generated app.
// It also emits the ResolveAliases function that main.go calls before Execute().
type AliasCmdGenerator struct {
	outputDir string
	appName   string
}

// NewAliasCmdGenerator creates an alias command generator.
func NewAliasCmdGenerator(outputDir, appName string) *AliasCmdGenerator {
	return &AliasCmdGenerator{outputDir: outputDir, appName: appName}
}

// Generate produces the alias command file for the generated app.
func (g *AliasCmdGenerator) Generate() error {
	cliDir := filepath.Join(g.outputDir, "internal", "cli")
	if err := os.MkdirAll(cliDir, 0o755); err != nil {
		return err
	}

	var sb StringBuilder
	sb.Line("// Code generated by Cliford. DO NOT EDIT outside custom code regions.")
	sb.Line("package cli")
	sb.Line("")
	sb.Line("import (")
	sb.Line(`	"fmt"`)
	sb.Line(`	"os"`)
	sb.Line(`	"path/filepath"`)
	sb.Line(`	"sort"`)
	sb.Line(`	"strings"`)
	sb.Line("")
	sb.Line(`	"github.com/spf13/cobra"`)
	sb.Line(`	"github.com/spf13/viper"`)
	sb.Line(")")
	sb.Line("")

	// ResolveAliases — exported function called from main.go
	sb.Line("// aliasEntry holds a single alias name and its expansion for structured output.")
	sb.Line("type aliasEntry struct {")
	sb.Line("	Name      string `json:\"name\" yaml:\"name\"`")
	sb.Line("	Expansion string `json:\"expansion\" yaml:\"expansion\"`")
	sb.Line("}")
	sb.Line("")
	sb.Line("// ResolveAliases checks os.Args[1] against configured aliases and expands it.")
	sb.Line("// If args[1] matches a configured alias, its expansion tokens replace it and")
	sb.Line("// any extra user args are appended after. Returns args unchanged when no alias")
	sb.Line("// matches or when args has fewer than 2 elements.")
	sb.Line("// Call this with os.Args before rootCmd.Execute().")
	sb.Line("func ResolveAliases(args []string) []string {")
	sb.Line("	if len(args) < 2 {")
	sb.Line("		return args")
	sb.Line("	}")
	sb.Line("	aliases := viper.GetStringMapString(\"aliases\")")
	sb.Line("	expansion, ok := aliases[args[1]]")
	sb.Line("	if !ok {")
	sb.Line("		return args")
	sb.Line("	}")
	sb.Line("	expanded := strings.Fields(expansion)")
	sb.Line("	if len(expanded) == 0 {")
	sb.Line("		return args")
	sb.Line("	}")
	sb.Line("	result := make([]string, 0, 1+len(expanded)+len(args[2:]))")
	sb.Line("	result = append(result, args[0])")
	sb.Line("	result = append(result, expanded...)")
	sb.Line("	result = append(result, args[2:]...)")
	sb.Line("	return result")
	sb.Line("}")
	sb.Line("")

	// aliasCmd — parent command
	sb.Line("// aliasCmd returns the alias management command.")
	sb.Line("func aliasCmd() *cobra.Command {")
	sb.Line("	cmd := &cobra.Command{")
	sb.Line(`		Use:   "alias",`)
	sb.Line(`		Short: "Manage command aliases",`)
	sb.Line(`		Long:  "Create, list, and delete command aliases stored in your configuration file.\n\nAliases let you define short names for longer commands with default flags.\nThey are stored under the 'aliases' key in ~/.config/<app>/config.yaml.",`)
	sb.Line("	}")
	sb.Line("	cmd.AddCommand(aliasSetCmd())")
	sb.Line("	cmd.AddCommand(aliasDeleteCmd())")
	sb.Line("	cmd.AddCommand(aliasListCmd())")
	sb.Line("	return cmd")
	sb.Line("}")
	sb.Line("")

	// alias set
	sb.Line("// aliasSetCmd defines or updates an alias.")
	sb.Line("func aliasSetCmd() *cobra.Command {")
	sb.Line("	return &cobra.Command{")
	sb.Line(`		Use:   "set <name> <expansion>",`)
	sb.Line(`		Short: "Define or update an alias",`)
	sb.Line("		Args:  cobra.ExactArgs(2),")
	sb.Line(`		Example: "  alias set lp \"pets list --limit 10\"\n  alias set new-cat \"pets create --name Whiskers\"",`)
	sb.Line("		RunE: func(cmd *cobra.Command, args []string) error {")
	sb.Line("			name, expansion := args[0], args[1]")
	sb.Line("			aliases := viper.GetStringMapString(\"aliases\")")
	sb.Line("			if aliases == nil {")
	sb.Line("				aliases = map[string]string{}")
	sb.Line("			}")
	sb.Line("			aliases[name] = expansion")
	sb.Line("			viper.Set(\"aliases\", aliases)")
	sb.Line("			configDir, err := os.UserConfigDir()")
	sb.Line("			if err != nil {")
	sb.Line(`				return fmt.Errorf("find config directory: %w", err)`)
	sb.Line("			}")
	sb.Linef("			configPath := filepath.Join(configDir, %q, \"config.yaml\")", g.appName)
	sb.Line("			if err := viper.WriteConfigAs(configPath); err != nil {")
	sb.Line(`				return fmt.Errorf("write config: %w", err)`)
	sb.Line("			}")
	sb.Line(`			fmt.Fprintf(cmd.OutOrStdout(), "Alias %q = %q added.\n", name, expansion)`)
	sb.Line("			return nil")
	sb.Line("		},")
	sb.Line("	}")
	sb.Line("}")
	sb.Line("")

	// alias delete
	sb.Line("// aliasDeleteCmd removes an alias.")
	sb.Line("func aliasDeleteCmd() *cobra.Command {")
	sb.Line("	return &cobra.Command{")
	sb.Line(`		Use:   "delete <name>",`)
	sb.Line(`		Short: "Remove an alias",`)
	sb.Line("		Args:  cobra.ExactArgs(1),")
	sb.Line("		RunE: func(cmd *cobra.Command, args []string) error {")
	sb.Line("			name := args[0]")
	sb.Line("			aliases := viper.GetStringMapString(\"aliases\")")
	sb.Line("			if _, ok := aliases[name]; !ok {")
	sb.Line(`				return fmt.Errorf("alias %q not found", name)`)
	sb.Line("			}")
	sb.Line("			delete(aliases, name)")
	sb.Line("			viper.Set(\"aliases\", aliases)")
	sb.Line("			configDir, err := os.UserConfigDir()")
	sb.Line("			if err != nil {")
	sb.Line(`				return fmt.Errorf("find config directory: %w", err)`)
	sb.Line("			}")
	sb.Linef("			configPath := filepath.Join(configDir, %q, \"config.yaml\")", g.appName)
	sb.Line("			if err := viper.WriteConfigAs(configPath); err != nil {")
	sb.Line(`				return fmt.Errorf("write config: %w", err)`)
	sb.Line("			}")
	sb.Line(`			fmt.Fprintf(cmd.OutOrStdout(), "Alias %q removed.\n", name)`)
	sb.Line("			return nil")
	sb.Line("		},")
	sb.Line("	}")
	sb.Line("}")
	sb.Line("")

	// alias list
	sb.Line("// aliasListCmd lists all configured aliases using the standard FormatOutput.")
	sb.Line("func aliasListCmd() *cobra.Command {")
	sb.Line("	return &cobra.Command{")
	sb.Line(`		Use:   "list",`)
	sb.Line(`		Short: "List all aliases",`)
	sb.Line("		RunE: func(cmd *cobra.Command, args []string) error {")
	sb.Line("			raw := viper.GetStringMapString(\"aliases\")")
	sb.Line("			if len(raw) == 0 {")
	sb.Line(`				fmt.Fprintln(cmd.OutOrStdout(), "No aliases configured.")`)
	sb.Line("				return nil")
	sb.Line("			}")
	sb.Line("			names := make([]string, 0, len(raw))")
	sb.Line("			for name := range raw {")
	sb.Line("				names = append(names, name)")
	sb.Line("			}")
	sb.Line("			sort.Strings(names)")
	sb.Line("			entries := make([]aliasEntry, 0, len(names))")
	sb.Line("			for _, name := range names {")
	sb.Line("				entries = append(entries, aliasEntry{Name: name, Expansion: raw[name]})")
	sb.Line("			}")
	sb.Line("			return FormatOutput(entries, outputFormat)")
	sb.Line("		},")
	sb.Line("	}")
	sb.Line("}")
	sb.Line("")

	return writeFormatted(filepath.Join(cliDir, "alias.go"), sb.String())
}
