package cli

import (
	"os"
	"path/filepath"
	"strings"

	"github.com/the-inconvenience-store/cliford/pkg/registry"
)

// AuthGenerator produces auth CLI commands for the generated app.
type AuthGenerator struct {
	outputDir string
	appName   string
	pkgPath   string
	envPrefix string
	schemes   map[string]registry.SecurityScheme
}

// NewAuthGenerator creates an auth command generator.
func NewAuthGenerator(outputDir, appName string, schemes map[string]registry.SecurityScheme) *AuthGenerator {
	return &AuthGenerator{
		outputDir: outputDir,
		appName:   appName,
		schemes:   schemes,
	}
}

// SetPackagePath sets the Go module path for import statements.
func (g *AuthGenerator) SetPackagePath(pkgPath string) {
	g.pkgPath = pkgPath
}

// SetEnvPrefix sets the environment variable prefix used to name env vars in the generated refresh command.
func (g *AuthGenerator) SetEnvPrefix(prefix string) {
	g.envPrefix = prefix
}

// oauthEnvVars returns the env var names for the first OAuth2 scheme, or ("", "", "", false).
func (g *AuthGenerator) oauthEnvVars() (tokenURL, clientID, clientSecret string, ok bool) {
	pfx := strings.ToUpper(strings.NewReplacer("-", "_", " ", "_").Replace(g.envPrefix))
	if pfx == "" {
		pfx = strings.ToUpper(strings.NewReplacer("-", "_", " ", "_").Replace(g.appName))
	}
	for name, s := range g.schemes {
		if s.Type == registry.SecurityTypeOAuth2 || s.Type == registry.SecurityTypeOpenIDConnect {
			seg := strings.ToUpper(strings.NewReplacer("-", "_", " ", "_").Replace(name))
			return pfx + "_" + seg + "_TOKEN_URL",
				pfx + "_" + seg + "_CLIENT_ID",
				pfx + "_" + seg + "_CLIENT_SECRET",
				true
		}
	}
	return "", "", "", false
}

// Generate produces the auth command file for the generated app.
func (g *AuthGenerator) Generate() error {
	cliDir := filepath.Join(g.outputDir, "internal", "cli")
	if err := os.MkdirAll(cliDir, 0o755); err != nil {
		return err
	}

	_, _, _, hasOAuth := g.oauthEnvVars()

	var sb StringBuilder
	sb.Line("// Code generated by Cliford. DO NOT EDIT outside custom code regions.")
	sb.Line("package cli")
	sb.Line("")
	sb.Line("import (")
	sb.Line(`	"bufio"`)
	sb.Line(`	"fmt"`)
	sb.Line(`	"os"`)
	sb.Line(`	"strings"`)
	if hasOAuth {
		sb.Line(`	"time"`)
	}
	sb.Line("")
	sb.Linef("	\"%s\"", g.packagePath())
	sb.Line("")
	sb.Line(`	"github.com/spf13/cobra"`)
	sb.Line(")")
	sb.Line("")

	// Auth parent command
	sb.Line("func authCmd() *cobra.Command {")
	sb.Line("	cmd := &cobra.Command{")
	sb.Line(`		Use:   "auth",`)
	sb.Line(`		Short: "Manage authentication",`)
	sb.Line("	}")
	sb.Line("")
	sb.Line("	cmd.AddCommand(authLoginCmd())")
	sb.Line("	cmd.AddCommand(authLogoutCmd())")
	sb.Line("	cmd.AddCommand(authStatusCmd())")
	sb.Line("	cmd.AddCommand(authSwitchCmd())")
	sb.Line("	cmd.AddCommand(authRefreshCmd())")
	sb.Line("")
	sb.Line("	return cmd")
	sb.Line("}")
	sb.Line("")

	// Login command
	sb.Line("func authLoginCmd() *cobra.Command {")
	sb.Line("	var (")
	sb.Line("		method  string")
	sb.Line("		profile string")
	sb.Line("		token   string")
	sb.Line("		apiKey  string")
	sb.Line("		user    string")
	sb.Line("		pass    string")
	sb.Line("	)")
	sb.Line("")
	sb.Line("	cmd := &cobra.Command{")
	sb.Line(`		Use:   "login",`)
	sb.Line(`		Short: "Authenticate with the API",`)
	sb.Line("		RunE: func(cmd *cobra.Command, args []string) error {")
	sb.Line("			store := auth.NewStore()")
	sb.Line("")
	sb.Line("			// Auto-detect method if not specified")
	sb.Line(`			if method == "" {`)

	// Default to the first scheme found
	methods := g.availableMethods()
	if len(methods) > 0 {
		sb.Linef("				method = %q", methods[0])
	} else {
		sb.Line(`				method = "bearer"`)
	}
	sb.Line("			}")
	sb.Line("")
	sb.Line(`			if profile == "" {`)
	sb.Line(`				profile = auth.ActiveProfile()`)
	sb.Line("			}")
	sb.Line("")
	sb.Line("			cred := auth.Credential{Method: method}")
	sb.Line("")
	sb.Line(`			switch method {`)
	sb.Line(`			case "bearer":`)
	sb.Line(`				if token == "" && !yesMode {`)
	sb.Line(`					token = prompt("Bearer token: ")`)
	sb.Line("				}")
	sb.Line(`				if token == "" {`)
	sb.Line(`					return fmt.Errorf("--token is required")`)
	sb.Line("				}")
	sb.Line("				cred.Token = token")
	sb.Line(`			case "apiKey":`)
	sb.Line(`				if apiKey == "" && !yesMode {`)
	sb.Line(`					apiKey = prompt("API key: ")`)
	sb.Line("				}")
	sb.Line(`				if apiKey == "" {`)
	sb.Line(`					return fmt.Errorf("--api-key is required")`)
	sb.Line("				}")
	sb.Line("				cred.Token = apiKey")

	// Set header name from scheme
	for _, s := range g.schemes {
		if s.Type == registry.SecurityTypeAPIKey {
			if s.In == registry.ParamLocationHeader {
				sb.Linef("				cred.HeaderName = %q", s.Name)
			} else {
				sb.Linef("				cred.QueryParam = %q", s.Name)
			}
			break
		}
	}

	sb.Line(`			case "basic":`)
	sb.Line(`				if user == "" && !yesMode {`)
	sb.Line(`					user = prompt("Username: ")`)
	sb.Line("				}")
	sb.Line(`				if pass == "" && !yesMode {`)
	sb.Line(`					pass = prompt("Password: ")`)
	sb.Line("				}")
	sb.Line(`				if user == "" || pass == "" {`)
	sb.Line(`					return fmt.Errorf("--username and --password are required")`)
	sb.Line("				}")
	sb.Line("				cred.Username = user")
	sb.Line("				cred.Password = pass")
	sb.Line(`			case "oauth2":`)
	sb.Line(`				if token == "" && !yesMode {`)
	sb.Line(`					token = prompt("OAuth2 access token: ")`)
	sb.Line("				}")
	sb.Line("				cred.Token = token")
	sb.Line("			}")
	sb.Line("")
	sb.Line("			if err := store.Save(profile, cred); err != nil {")
	sb.Line("				return err")
	sb.Line("			}")
	sb.Line("")
	sb.Line(`			fmt.Printf("Logged in to profile %q using %s\n", profile, method)`)
	sb.Line("			return nil")
	sb.Line("		},")
	sb.Line("	}")
	sb.Line("")
	sb.Linef("	cmd.Flags().StringVar(&method, \"method\", \"\", \"Auth method: %s\")", strings.Join(methods, ", "))
	sb.Line(`	cmd.Flags().StringVar(&profile, "profile", "", "Profile name (default: active profile)")`)
	sb.Line(`	cmd.Flags().StringVar(&token, "token", "", "Bearer token or OAuth2 access token")`)
	sb.Line(`	cmd.Flags().StringVar(&apiKey, "api-key", "", "API key value")`)
	sb.Line(`	cmd.Flags().StringVar(&user, "username", "", "Username for basic auth")`)
	sb.Line(`	cmd.Flags().StringVar(&pass, "password", "", "Password for basic auth")`)
	sb.Line("")
	sb.Line("	return cmd")
	sb.Line("}")
	sb.Line("")

	// Logout command
	sb.Line("func authLogoutCmd() *cobra.Command {")
	sb.Line("	var profile string")
	sb.Line("	cmd := &cobra.Command{")
	sb.Line(`		Use:   "logout",`)
	sb.Line(`		Short: "Clear stored credentials",`)
	sb.Line("		RunE: func(cmd *cobra.Command, args []string) error {")
	sb.Line("			store := auth.NewStore()")
	sb.Line(`			if profile == "" {`)
	sb.Line("				profile = auth.ActiveProfile()")
	sb.Line("			}")
	sb.Line("			if err := store.Delete(profile); err != nil {")
	sb.Line("				return err")
	sb.Line("			}")
	sb.Line(`			fmt.Printf("Logged out of profile %q\n", profile)`)
	sb.Line("			return nil")
	sb.Line("		},")
	sb.Line("	}")
	sb.Line(`	cmd.Flags().StringVar(&profile, "profile", "", "Profile name")`)
	sb.Line("	return cmd")
	sb.Line("}")
	sb.Line("")

	// Status command
	sb.Line("func authStatusCmd() *cobra.Command {")
	sb.Line("	return &cobra.Command{")
	sb.Line(`		Use:   "status",`)
	sb.Line(`		Short: "Show current authentication state",`)
	sb.Line("		RunE: func(cmd *cobra.Command, args []string) error {")
	sb.Line("			store := auth.NewStore()")
	sb.Line("			profile := auth.ActiveProfile()")
	sb.Line("			cred, err := store.Get(profile)")
	sb.Line("			if err != nil {")
	sb.Line(`				fmt.Printf("Profile: %s\nStatus: not authenticated\n", profile)`)
	sb.Line("				return nil")
	sb.Line("			}")
	sb.Line(`			fmt.Printf("Profile: %s\n", profile)`)
	sb.Line(`			fmt.Printf("Method:  %s\n", cred.Method)`)
	sb.Line("			if cred.Token != \"\" {")
	sb.Line(`				fmt.Printf("Token:   %s...%s\n", cred.Token[:4], cred.Token[len(cred.Token)-4:])`)
	sb.Line("			}")
	sb.Line("			if cred.Username != \"\" {")
	sb.Line(`				fmt.Printf("User:    %s\n", cred.Username)`)
	sb.Line("			}")
	sb.Line("			serverURL := auth.ActiveServerURL()")
	sb.Line("			if serverURL != \"\" {")
	sb.Line(`				fmt.Printf("Server:  %s\n", serverURL)`)
	sb.Line("			}")
	sb.Line("			return nil")
	sb.Line("		},")
	sb.Line("	}")
	sb.Line("}")
	sb.Line("")

	// Switch command
	sb.Line("func authSwitchCmd() *cobra.Command {")
	sb.Line("	return &cobra.Command{")
	sb.Line(`		Use:   "switch [profile]",`)
	sb.Line(`		Short: "Switch active profile",`)
	sb.Line(`		Args:  cobra.ExactArgs(1),`)
	sb.Line("		RunE: func(cmd *cobra.Command, args []string) error {")
	sb.Line("			if err := auth.SetActiveProfile(args[0]); err != nil {")
	sb.Line("				return err")
	sb.Line("			}")
	sb.Line(`			fmt.Printf("Switched to profile %q\n", args[0])`)
	sb.Line("			return nil")
	sb.Line("		},")
	sb.Line("	}")
	sb.Line("}")
	sb.Line("")

	// Refresh command
	if hasOAuth {
		tokenURLVar, clientIDVar, clientSecretVar, _ := g.oauthEnvVars()
		sb.Line("func authRefreshCmd() *cobra.Command {")
		sb.Line("	var profile string")
		sb.Line("	cmd := &cobra.Command{")
		sb.Line(`		Use:   "refresh",`)
		sb.Line(`		Short: "Force refresh OAuth2 token for the active profile",`)
		sb.Line("		RunE: func(cmd *cobra.Command, args []string) error {")
		sb.Line("			store := auth.NewStore()")
		sb.Line(`			if profile == "" {`)
		sb.Line("				profile = auth.ActiveProfile()")
		sb.Line("			}")
		sb.Line("			cred, err := store.Get(profile)")
		sb.Line("			if err != nil {")
		sb.Linef(`				return fmt.Errorf("no credentials for profile %%q: run 'auth login' first", profile)`)
		sb.Line("			}")
		sb.Line(`			if cred.Method != "oauth2" {`)
		sb.Linef(`				return fmt.Errorf("profile %%q uses %%s authentication (not OAuth2)", profile, cred.Method)`)
		sb.Line("			}")
		sb.Line(`			if cred.RefreshTkn == "" {`)
		sb.Linef(`				return fmt.Errorf("no refresh token stored for profile %%q: run 'auth login' to re-authenticate", profile)`)
		sb.Line("			}")
		sb.Linef(`			tokenURL := os.Getenv(%q)`, tokenURLVar)
		sb.Linef(`			clientID := os.Getenv(%q)`, clientIDVar)
		sb.Line(`			if tokenURL == "" || clientID == "" {`)
		sb.Linef(`				return fmt.Errorf("OAuth2 configuration required: set %%s and %%s", %q, %q)`, tokenURLVar, clientIDVar)
		sb.Line("			}")
		sb.Line("			cfg := auth.OAuthConfig{")
		sb.Line("				TokenURL:     tokenURL,")
		sb.Line("				ClientID:     clientID,")
		sb.Linef(`				ClientSecret: os.Getenv(%q),`, clientSecretVar)
		sb.Line("			}")
		sb.Linef(`			fmt.Printf("Refreshing OAuth2 token for profile %%q...\n", profile)`)
		sb.Line("			newTok, refreshErr := auth.RefreshToken(cmd.Context(), cfg, cred.RefreshTkn)")
		sb.Line("			if refreshErr != nil {")
		sb.Linef(`				return fmt.Errorf("token refresh failed: %%w", refreshErr)`)
		sb.Line("			}")
		sb.Line("			cred.Token = newTok.AccessToken")
		sb.Line("			if !newTok.ExpiresAt.IsZero() {")
		sb.Line("				cred.ExpiresAt = newTok.ExpiresAt.Format(time.RFC3339)")
		sb.Line("			}")
		sb.Line(`			if newTok.RefreshToken != "" {`)
		sb.Line("				cred.RefreshTkn = newTok.RefreshToken")
		sb.Line("			}")
		sb.Line("			if saveErr := store.Save(profile, *cred); saveErr != nil {")
		sb.Linef(`				return fmt.Errorf("save refreshed token: %%w", saveErr)`)
		sb.Line("			}")
		sb.Line(`			if cred.ExpiresAt != "" {`)
		sb.Linef(`				fmt.Printf("Token refreshed. Expires: %%s\n", cred.ExpiresAt)`)
		sb.Line("			} else {")
		sb.Linef(`				fmt.Println("Token refreshed successfully.")`)
		sb.Line("			}")
		sb.Line("			return nil")
		sb.Line("		},")
		sb.Line("	}")
		sb.Line(`	cmd.Flags().StringVar(&profile, "profile", "", "Profile to refresh (default: active profile)")`)
		sb.Line("	return cmd")
		sb.Line("}")
	} else {
		sb.Line("func authRefreshCmd() *cobra.Command {")
		sb.Line("	return &cobra.Command{")
		sb.Line(`		Use:   "refresh",`)
		sb.Line(`		Short: "Refresh OAuth2 token",`)
		sb.Line("		RunE: func(cmd *cobra.Command, args []string) error {")
		sb.Linef(`			return fmt.Errorf("this app does not use OAuth2 authentication")`)
		sb.Line("		},")
		sb.Line("	}")
		sb.Line("}")
	}
	sb.Line("")

	// Prompt helper
	sb.Line("func prompt(label string) string {")
	sb.Line("	fmt.Print(label)")
	sb.Line("	scanner := bufio.NewScanner(os.Stdin)")
	sb.Line("	if scanner.Scan() {")
	sb.Line("		return strings.TrimSpace(scanner.Text())")
	sb.Line("	}")
	sb.Line(`	return ""`)
	sb.Line("}")

	return writeFormatted(filepath.Join(cliDir, "auth.go"), sb.String())
}

func (g *AuthGenerator) packagePath() string {
	if g.pkgPath != "" {
		return g.pkgPath
	}
	return g.appName + "/internal/auth"
}

func (g *AuthGenerator) availableMethods() []string {
	seen := make(map[string]bool)
	var methods []string

	for _, s := range g.schemes {
		var m string
		switch s.Type {
		case registry.SecurityTypeHTTP:
			m = s.Scheme // "bearer" or "basic"
		case registry.SecurityTypeAPIKey:
			m = "apiKey"
		case registry.SecurityTypeOAuth2:
			m = "oauth2"
		case registry.SecurityTypeOpenIDConnect:
			m = "oauth2"
		}
		if m != "" && !seen[m] {
			seen[m] = true
			methods = append(methods, m)
		}
	}

	if len(methods) == 0 {
		methods = []string{"bearer"}
	}
	return methods
}
