package cli

import (
	"os"
	"path/filepath"
)

// ConfigCmdGenerator produces config management commands for the generated app.
type ConfigCmdGenerator struct {
	outputDir string
	appName   string
}

// NewConfigCmdGenerator creates a config command generator.
func NewConfigCmdGenerator(outputDir, appName string) *ConfigCmdGenerator {
	return &ConfigCmdGenerator{outputDir: outputDir, appName: appName}
}

// Generate produces the config command file for the generated app.
func (g *ConfigCmdGenerator) Generate() error {
	cliDir := filepath.Join(g.outputDir, "internal", "cli")
	if err := os.MkdirAll(cliDir, 0o755); err != nil {
		return err
	}

	var sb StringBuilder
	sb.Line("// Code generated by Cliford. DO NOT EDIT outside custom code regions.")
	sb.Line("package cli")
	sb.Line("")
	sb.Line("import (")
	sb.Line(`	"fmt"`)
	sb.Line(`	"os"`)
	sb.Line(`	"os/exec"`)
	sb.Line(`	"path/filepath"`)
	sb.Line("")
	sb.Line(`	"github.com/spf13/cobra"`)
	sb.Line(`	"github.com/spf13/viper"`)
	sb.Line(")")
	sb.Line("")

	// Config parent command
	sb.Line("func configCmd() *cobra.Command {")
	sb.Line("	cmd := &cobra.Command{")
	sb.Line(`		Use:   "config",`)
	sb.Line(`		Short: "Manage app configuration",`)
	sb.Line("	}")
	sb.Line("")
	sb.Line("	cmd.AddCommand(configShowCmd())")
	sb.Line("	cmd.AddCommand(configSetCmd())")
	sb.Line("	cmd.AddCommand(configGetCmd())")
	sb.Line("	cmd.AddCommand(configResetCmd())")
	sb.Line("	cmd.AddCommand(configEditCmd())")
	sb.Line("	cmd.AddCommand(configPathCmd())")
	sb.Line("")
	sb.Line("	return cmd")
	sb.Line("}")
	sb.Line("")

	// Show
	sb.Line("func configShowCmd() *cobra.Command {")
	sb.Line("	return &cobra.Command{")
	sb.Line(`		Use:   "show",`)
	sb.Line(`		Short: "Display current configuration",`)
	sb.Line("		RunE: func(cmd *cobra.Command, args []string) error {")
	sb.Line("			settings := viper.AllSettings()")
	sb.Line("			return FormatOutput(settings, outputFormat)")
	sb.Line("		},")
	sb.Line("	}")
	sb.Line("}")
	sb.Line("")

	// Set
	sb.Line("func configSetCmd() *cobra.Command {")
	sb.Line("	return &cobra.Command{")
	sb.Line(`		Use:   "set [key] [value]",`)
	sb.Line(`		Short: "Set a configuration value",`)
	sb.Line(`		Args:  cobra.ExactArgs(2),`)
	sb.Line("		RunE: func(cmd *cobra.Command, args []string) error {")
	sb.Line("			viper.Set(args[0], args[1])")
	sb.Line("			configDir, _ := os.UserConfigDir()")
	sb.Linef("			configPath := filepath.Join(configDir, %q, \"config.yaml\")", g.appName)
	sb.Line("			if err := viper.WriteConfigAs(configPath); err != nil {")
	sb.Line("				return err")
	sb.Line("			}")
	sb.Line(`			fmt.Printf("Set %s = %s\n", args[0], args[1])`)
	sb.Line("			return nil")
	sb.Line("		},")
	sb.Line("	}")
	sb.Line("}")
	sb.Line("")

	// Get
	sb.Line("func configGetCmd() *cobra.Command {")
	sb.Line("	return &cobra.Command{")
	sb.Line(`		Use:   "get [key]",`)
	sb.Line(`		Short: "Get a configuration value",`)
	sb.Line(`		Args:  cobra.ExactArgs(1),`)
	sb.Line("		RunE: func(cmd *cobra.Command, args []string) error {")
	sb.Line("			val := viper.Get(args[0])")
	sb.Line("			if val == nil {")
	sb.Line(`				return fmt.Errorf("key %q not found", args[0])`)
	sb.Line("			}")
	sb.Line(`			fmt.Println(val)`)
	sb.Line("			return nil")
	sb.Line("		},")
	sb.Line("	}")
	sb.Line("}")
	sb.Line("")

	// Reset
	sb.Line("func configResetCmd() *cobra.Command {")
	sb.Line("	return &cobra.Command{")
	sb.Line(`		Use:   "reset",`)
	sb.Line(`		Short: "Reset configuration to defaults",`)
	sb.Line("		RunE: func(cmd *cobra.Command, args []string) error {")
	sb.Line("			configDir, _ := os.UserConfigDir()")
	sb.Linef("			configPath := filepath.Join(configDir, %q, \"config.yaml\")", g.appName)
	sb.Line("			if err := os.Remove(configPath); err != nil && !os.IsNotExist(err) {")
	sb.Line("				return err")
	sb.Line("			}")
	sb.Line(`			fmt.Println("Configuration reset to defaults")`)
	sb.Line("			return nil")
	sb.Line("		},")
	sb.Line("	}")
	sb.Line("}")
	sb.Line("")

	// Edit
	sb.Line("func configEditCmd() *cobra.Command {")
	sb.Line("	return &cobra.Command{")
	sb.Line(`		Use:   "edit",`)
	sb.Line(`		Short: "Open config file in $EDITOR",`)
	sb.Line("		RunE: func(cmd *cobra.Command, args []string) error {")
	sb.Line(`			editor := os.Getenv("EDITOR")`)
	sb.Line(`			if editor == "" {`)
	sb.Line(`				editor = "vi"`)
	sb.Line("			}")
	sb.Line("			configDir, _ := os.UserConfigDir()")
	sb.Linef("			configPath := filepath.Join(configDir, %q, \"config.yaml\")", g.appName)
	sb.Line("			c := exec.Command(editor, configPath)")
	sb.Line("			c.Stdin = os.Stdin")
	sb.Line("			c.Stdout = os.Stdout")
	sb.Line("			c.Stderr = os.Stderr")
	sb.Line("			return c.Run()")
	sb.Line("		},")
	sb.Line("	}")
	sb.Line("}")
	sb.Line("")

	// Path
	sb.Line("func configPathCmd() *cobra.Command {")
	sb.Line("	return &cobra.Command{")
	sb.Line(`		Use:   "path",`)
	sb.Line(`		Short: "Show config file location",`)
	sb.Line("		Run: func(cmd *cobra.Command, args []string) {")
	sb.Line("			configDir, _ := os.UserConfigDir()")
	sb.Linef("			fmt.Println(filepath.Join(configDir, %q, \"config.yaml\"))", g.appName)
	sb.Line("		},")
	sb.Line("	}")
	sb.Line("}")

	return writeFormatted(filepath.Join(cliDir, "config_cmd.go"), sb.String())
}
