package cli

import (
	"os"
	"path/filepath"
)

// ErrorOutputGenerator produces error formatting code for the generated app.
type ErrorOutputGenerator struct {
	outputDir string
}

// NewErrorOutputGenerator creates an error output generator.
func NewErrorOutputGenerator(outputDir string) *ErrorOutputGenerator {
	return &ErrorOutputGenerator{outputDir: outputDir}
}

// Generate produces the error formatting file.
func (g *ErrorOutputGenerator) Generate() error {
	cliDir := filepath.Join(g.outputDir, "internal", "cli")
	if err := os.MkdirAll(cliDir, 0o755); err != nil {
		return err
	}

	code := `// Code generated by Cliford. DO NOT EDIT outside custom code regions.
package cli

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"
)

// FormatError renders an API error in the appropriate output format.
func FormatError(err error, format string) {
	switch strings.ToLower(format) {
	case "json":
		formatErrorJSON(err)
	default:
		formatErrorPretty(err)
	}
}

func formatErrorPretty(err error) {
	fmt.Fprintf(os.Stderr, "Error: %v\n", err)
}

func formatErrorJSON(err error) {
	errObj := map[string]any{
		"error": map[string]any{
			"message": err.Error(),
		},
	}

	// Try to extract structured fields from typed errors
	type statusCoder interface {
		StatusCode() int
	}
	type fieldsProvider interface {
		GetFields() []map[string]string
	}

	enc := json.NewEncoder(os.Stderr)
	enc.SetIndent("", "  ")
	enc.Encode(errObj)
}

// FormatDebugRequest prints a redacted HTTP request to stderr for --debug mode.
func FormatDebugRequest(method, url string, headers map[string][]string, body string) {
	fmt.Fprintf(os.Stderr, "[DEBUG] %s %s\n", method, url)

	sensitiveHeaders := map[string]bool{
		"authorization":       true,
		"x-api-key":           true,
		"cookie":              true,
		"proxy-authorization": true,
	}

	for k, vals := range headers {
		for _, v := range vals {
			if sensitiveHeaders[strings.ToLower(k)] {
				if len(v) > 8 {
					v = v[:4] + "..." + v[len(v)-4:]
				} else {
					v = "****"
				}
			}
			fmt.Fprintf(os.Stderr, "[DEBUG] %s: %s\n", k, v)
		}
	}

	if body != "" {
		fmt.Fprintf(os.Stderr, "[DEBUG] Body: %s\n", body)
	}
}

// FormatDebugResponse prints a redacted HTTP response to stderr for --debug mode.
func FormatDebugResponse(statusCode int, headers map[string][]string, body string) {
	fmt.Fprintf(os.Stderr, "[DEBUG] Response: %d\n", statusCode)

	if requestID := getHeader(headers, "X-Request-ID"); requestID != "" {
		fmt.Fprintf(os.Stderr, "[DEBUG] Request-ID: %s\n", requestID)
	}

	if len(body) > 500 {
		fmt.Fprintf(os.Stderr, "[DEBUG] Body: %s...(truncated)\n", body[:500])
	} else if body != "" {
		fmt.Fprintf(os.Stderr, "[DEBUG] Body: %s\n", body)
	}
}

func getHeader(headers map[string][]string, name string) string {
	for k, v := range headers {
		if strings.EqualFold(k, name) && len(v) > 0 {
			return v[0]
		}
	}
	return ""
}
`

	return os.WriteFile(filepath.Join(cliDir, "errors.go"), []byte(code), 0o644)
}
