// Package cli generates Cobra command trees from the Operation Registry.
package cli

import (
	"fmt"
	goformat "go/format"
	"os"
	"path/filepath"
	"strings"

	"github.com/cliford/cliford/internal/codegen"
	"github.com/cliford/cliford/pkg/registry"
)

// Generator produces Cobra CLI code from the Operation Registry.
type Generator struct {
	engine            *codegen.Engine
	outputDir         string
	appName           string
	envPrefix         string
	customCodeRegions bool
}

// NewGenerator creates a CLI generator.
func NewGenerator(engine *codegen.Engine, outputDir, appName, envPrefix string) *Generator {
	return &Generator{
		engine:    engine,
		outputDir: outputDir,
		appName:   appName,
		envPrefix: envPrefix,
	}
}

// SetCustomCodeRegions enables custom code region markers in generated output.
func (g *Generator) SetCustomCodeRegions(enabled bool) {
	g.customCodeRegions = enabled
}

// Generate produces all CLI source files from the registry.
// It generates the files directly using Go string building rather than
// Go text/template, because the generated output IS Go source code and
// template-in-template is error-prone.
func (g *Generator) Generate(reg *registry.Registry) error {
	cliDir := filepath.Join(g.outputDir, "internal", "cli")

	if err := os.MkdirAll(cliDir, 0o755); err != nil {
		return fmt.Errorf("create CLI dir: %w", err)
	}

	// Generate root command with all global flags
	if err := g.generateRoot(reg, cliDir); err != nil {
		return fmt.Errorf("generate root: %w", err)
	}

	// Generate one file per tag group with operation commands
	for tag, ops := range reg.TagGroups {
		if err := g.generateGroup(tag, ops, reg, cliDir); err != nil {
			return fmt.Errorf("generate group %s: %w", tag, err)
		}
	}

	return nil
}

func (g *Generator) generateRoot(reg *registry.Registry, cliDir string) error {
	var sb StringBuilder
	sb.Line("// Code generated by Cliford. DO NOT EDIT outside custom code regions.")
	sb.Line("package cli")
	sb.Line("")
	sb.Line("import (")
	sb.Line(`	"encoding/json"`)
	sb.Line(`	"os"`)
	sb.Line(`	"strings"`)
	sb.Line("")
	sb.Line(`	"github.com/spf13/cobra"`)
	sb.Line(`	"gopkg.in/yaml.v3"`)
	sb.Line(")")
	sb.Line("")
	sb.Line("var (")
	sb.Line(`	outputFormat  string`)
	sb.Line(`	serverURL     string`)
	sb.Line(`	debugMode     bool`)
	sb.Line(`	dryRunMode    bool`)
	sb.Line(`	yesMode       bool`)
	sb.Line(`	agentMode     bool`)
	sb.Line(`	noInteractive bool`)
	sb.Line(`	tuiMode       bool`)
	sb.Line(`	timeout       string`)
	sb.Line(")")
	sb.Line("")
	sb.Linef("// RootCmd returns the root Cobra command for %s.", g.appName)
	sb.Line("func RootCmd(appName string, version string) *cobra.Command {")
	sb.Line("	root := &cobra.Command{")
	sb.Linef("		Use:   %q,", g.appName)
	sb.Linef("		Short: %q,", reg.Description)
	sb.Line("		Version: version,")
	sb.Line("		SilenceUsage:  true,")
	sb.Line("		SilenceErrors: true,")
	sb.Line("	}")
	sb.Line("")
	sb.Line("	pf := root.PersistentFlags()")
	sb.Line(`	pf.StringVarP(&outputFormat, "output-format", "o", "pretty", "Output format: pretty, json, yaml, table")`)
	sb.Line(`	pf.StringVar(&serverURL, "server", "", "Override API server URL")`)
	sb.Line(`	pf.StringVar(&timeout, "timeout", "30s", "Request timeout")`)
	sb.Line(`	pf.BoolVar(&debugMode, "debug", false, "Log request/response to stderr (secrets redacted)")`)
	sb.Line(`	pf.BoolVar(&dryRunMode, "dry-run", false, "Display HTTP request without executing")`)
	sb.Line(`	pf.BoolVarP(&yesMode, "yes", "y", false, "Skip all confirmations, use defaults")`)
	sb.Line(`	pf.BoolVar(&agentMode, "agent", false, "Force agent mode (structured JSON, no interactive)")`)
	sb.Line(`	pf.BoolVar(&noInteractive, "no-interactive", false, "Disable interactive prompts")`)
	sb.Line(`	pf.BoolVar(&tuiMode, "tui", false, "Launch full TUI mode")`)
	sb.Line("")

	for tag := range reg.TagGroups {
		sb.Linef("	root.AddCommand(%sCmd())", toCamelCase(tag))
	}
	sb.Line("	root.AddCommand(authCmd())")
	sb.Line("	root.AddCommand(configCmd())")

	if g.customCodeRegions {
		sb.Line("")
		sb.Line("	// --- CUSTOM CODE START: root:init ---")
		sb.Line("	// --- CUSTOM CODE END: root:init ---")
	}

	// Add server info to help if servers defined
	if len(reg.Servers) > 1 {
		sb.Line("")
		sb.Line(`	root.Long = root.Short + "\n\nAvailable servers:"`)
		for _, s := range reg.Servers {
			desc := s.Description
			if desc == "" {
				desc = s.URL
			}
			sb.Linef("	root.Long += %q", fmt.Sprintf("\n  --server %s  (%s)", s.URL, desc))
		}
	}

	sb.Line("")
	sb.Line("	return root")
	sb.Line("}")
	sb.Line("")

	// FormatOutput helper
	sb.Line("// FormatOutput renders data in the requested output format.")
	sb.Line("func FormatOutput(data any, format string) error {")
	sb.Line(`	switch strings.ToLower(format) {`)
	sb.Line(`	case "json":`)
	sb.Line("		enc := json.NewEncoder(os.Stdout)")
	sb.Line(`		enc.SetIndent("", "  ")`)
	sb.Line("		return enc.Encode(data)")
	sb.Line(`	case "yaml":`)
	sb.Line("		enc := yaml.NewEncoder(os.Stdout)")
	sb.Line("		return enc.Encode(data)")
	sb.Line("	default:")
	sb.Line("		enc := json.NewEncoder(os.Stdout)")
	sb.Line(`		enc.SetIndent("", "  ")`)
	sb.Line("		return enc.Encode(data)")
	sb.Line("	}")
	sb.Line("}")

	return writeFormatted(filepath.Join(cliDir, "root.go"), sb.String())
}

func (g *Generator) generateGroup(tag string, ops []registry.OperationMeta, reg *registry.Registry, cliDir string) error {
	// Determine which imports are needed
	needsBytes := false
	for _, op := range ops {
		if op.RequestBody != nil {
			needsBytes = true
		}
	}

	var sb StringBuilder
	sb.Line("// Code generated by Cliford. DO NOT EDIT outside custom code regions.")
	sb.Line("package cli")
	sb.Line("")
	sb.Line("import (")
	if needsBytes {
		sb.Line(`	"bytes"`)
	}
	sb.Line(`	"context"`)
	sb.Line(`	"encoding/json"`)
	sb.Line(`	"fmt"`)
	sb.Line(`	"io"`)
	sb.Line(`	"net/http"`)
	sb.Line(`	"net/url"`)
	sb.Line(`	"os"`)
	sb.Line(`	"strings"`)
	sb.Line(`	"time"`)
	sb.Line("")
	sb.Line(`	"github.com/spf13/cobra"`)
	sb.Line(")")
	sb.Line("")

	// Tag group command
	tagPrefix := toCamelCase(tag)
	sb.Linef("func %sCmd() *cobra.Command {", tagPrefix)
	sb.Line("	cmd := &cobra.Command{")
	sb.Linef("		Use:   %q,", strings.ToLower(tag))
	sb.Linef("		Short: %q,", tag+" operations")
	sb.Line("	}")
	sb.Line("")
	for _, op := range ops {
		sb.Linef("	cmd.AddCommand(%s%sCmd())", tagPrefix, toPascalCase(op.CLICommandName))
	}
	sb.Line("")
	sb.Line("	return cmd")
	sb.Line("}")
	sb.Line("")

	// Each operation command - prefixed with tag name to avoid collisions
	for _, op := range ops {
		g.generateOperationCmd(&sb, op, reg, tagPrefix)
	}

	return writeFormatted(filepath.Join(cliDir, toSnakeCase(tag)+".go"), sb.String())
}

func (g *Generator) generateOperationCmd(sb *StringBuilder, op registry.OperationMeta, reg *registry.Registry, tagPrefix string) {
	funcName := tagPrefix + toPascalCase(op.CLICommandName)

	sb.Linef("func %sCmd() *cobra.Command {", funcName)

	// Flag variables
	for _, p := range op.Parameters {
		goType := flagGoType(p.Schema)
		sb.Linef("	var flag%s %s", toPascalCase(p.FlagName), goType)
	}
	if op.RequestBody != nil {
		sb.Line("	var bodyJSON string")
	}
	sb.Line("")

	sb.Line("	cmd := &cobra.Command{")
	sb.Linef("		Use:   %q,", op.CLICommandName)
	sb.Linef("		Short: %q,", op.Summary)
	if op.Description != "" {
		sb.Linef("		Long:  %q,", op.Description)
	}
	if len(op.CLIAliases) > 0 {
		sb.Linef("		Aliases: []string{%s},", quoteJoin(op.CLIAliases))
	}
	if op.CLIHidden {
		sb.Line("		Hidden: true,")
	}

	sb.Line("		RunE: func(cmd *cobra.Command, args []string) error {")

	// Determine base URL
	defaultURL := "http://localhost:8080"
	if len(reg.Servers) > 0 {
		defaultURL = reg.Servers[0].URL
	}
	sb.Linef("			baseURL := %q", defaultURL)
	sb.Line("			if serverURL != \"\" {")
	sb.Line("				baseURL = serverURL")
	sb.Line("			}")
	sb.Line("")

	// Build path with parameter substitution
	sb.Linef("			reqPath := %q", op.Path)
	for _, p := range op.Parameters {
		if p.In == registry.ParamLocationPath {
			sb.Linef(`			reqPath = strings.Replace(reqPath, "{%s}", fmt.Sprintf("%%v", flag%s), 1)`, p.Name, toPascalCase(p.FlagName))
		}
	}
	sb.Line("")

	sb.Line("			reqURL, err := url.Parse(baseURL + reqPath)")
	sb.Line("			if err != nil {")
	sb.Line(`				return fmt.Errorf("invalid URL: %w", err)`)
	sb.Line("			}")
	sb.Line("")

	// Query parameters
	hasQuery := false
	for _, p := range op.Parameters {
		if p.In == registry.ParamLocationQuery {
			hasQuery = true
			break
		}
	}
	if hasQuery {
		sb.Line("			q := reqURL.Query()")
		for _, p := range op.Parameters {
			if p.In != registry.ParamLocationQuery {
				continue
			}
			goType := flagGoType(p.Schema)
			flagVar := "flag" + toPascalCase(p.FlagName)
			switch goType {
			case "string":
				sb.Linef("			if %s != \"\" {", flagVar)
				sb.Linef("				q.Set(%q, %s)", p.Name, flagVar)
				sb.Line("			}")
			case "int", "int64":
				sb.Linef("			if cmd.Flags().Changed(%q) {", p.FlagName)
				sb.Linef("				q.Set(%q, fmt.Sprintf(\"%%d\", %s))", p.Name, flagVar)
				sb.Line("			}")
			case "bool":
				sb.Linef("			if cmd.Flags().Changed(%q) {", p.FlagName)
				sb.Linef("				q.Set(%q, fmt.Sprintf(\"%%t\", %s))", p.Name, flagVar)
				sb.Line("			}")
			}
		}
		sb.Line("			reqURL.RawQuery = q.Encode()")
		sb.Line("")
	}

	// Request body
	sb.Line("			var reqBody io.Reader")
	if op.RequestBody != nil {
		sb.Line("			if bodyJSON != \"\" {")
		sb.Line("				reqBody = strings.NewReader(bodyJSON)")
		sb.Line("			} else {")
		sb.Line("				stat, _ := os.Stdin.Stat()")
		sb.Line("				if stat != nil && (stat.Mode()&os.ModeCharDevice) == 0 {")
		sb.Line("					data, err := io.ReadAll(os.Stdin)")
		sb.Line("					if err == nil && len(data) > 0 {")
		sb.Line("						reqBody = bytes.NewReader(data)")
		sb.Line("					}")
		sb.Line("				}")
		sb.Line("			}")
	}
	sb.Line("")

	// Create request
	sb.Linef("			req, err := http.NewRequestWithContext(context.Background(), %q, reqURL.String(), reqBody)", op.Method)
	sb.Line("			if err != nil {")
	sb.Line(`				return fmt.Errorf("create request: %w", err)`)
	sb.Line("			}")

	// Header parameters
	for _, p := range op.Parameters {
		if p.In == registry.ParamLocationHeader {
			flagVar := "flag" + toPascalCase(p.FlagName)
			sb.Linef("			if %s != \"\" {", flagVar)
			sb.Linef("				req.Header.Set(%q, %s)", p.Name, flagVar)
			sb.Line("			}")
		}
	}
	if op.RequestBody != nil {
		sb.Line("			if reqBody != nil {")
		sb.Line(`				req.Header.Set("Content-Type", "application/json")`)
		sb.Line("			}")
	}
	sb.Line("")

	// Custom code region: pre-request
	if g.customCodeRegions {
		sb.Linef("			// --- CUSTOM CODE START: %s:pre ---", op.OperationID)
		sb.Linef("			// --- CUSTOM CODE END: %s:pre ---", op.OperationID)
		sb.Line("")
	}

	// Dry-run
	sb.Line("			if dryRunMode {")
	sb.Line(`				fmt.Fprintf(os.Stdout, "%s %s\n", req.Method, req.URL.String())`)
	sb.Line("				for k, v := range req.Header {")
	sb.Line(`					fmt.Fprintf(os.Stdout, "%s: %s\n", k, strings.Join(v, ", "))`)
	sb.Line("				}")
	sb.Line("				return nil")
	sb.Line("			}")
	sb.Line("")

	// Execute
	sb.Line("			client := &http.Client{Timeout: 30 * time.Second}")
	sb.Line("			resp, err := client.Do(req)")
	sb.Line("			if err != nil {")
	sb.Line(`				return fmt.Errorf("request failed: %w", err)`)
	sb.Line("			}")
	sb.Line("			defer resp.Body.Close()")
	sb.Line("")
	sb.Line("			respBody, err := io.ReadAll(resp.Body)")
	sb.Line("			if err != nil {")
	sb.Line(`				return fmt.Errorf("read response: %w", err)`)
	sb.Line("			}")
	sb.Line("")

	// Handle errors
	sb.Line("			if resp.StatusCode >= 400 {")
	sb.Line(`				return fmt.Errorf("HTTP %d: %s", resp.StatusCode, string(respBody))`)
	sb.Line("			}")
	sb.Line("")

	// Handle 204 No Content
	sb.Line("			if resp.StatusCode == 204 || len(respBody) == 0 {")
	sb.Line(`				fmt.Println("OK")`)
	sb.Line("				return nil")
	sb.Line("			}")
	sb.Line("")

	// Format output
	sb.Line("			var data any")
	sb.Line("			if err := json.Unmarshal(respBody, &data); err != nil {")
	sb.Line("				fmt.Println(string(respBody))")
	sb.Line("				return nil")
	sb.Line("			}")
	// Custom code region: post-response
	if g.customCodeRegions {
		sb.Line("")
		sb.Linef("			// --- CUSTOM CODE START: %s:post ---", op.OperationID)
		sb.Linef("			// --- CUSTOM CODE END: %s:post ---", op.OperationID)
	}

	sb.Line("			return FormatOutput(data, outputFormat)")

	sb.Line("		},")
	sb.Line("	}")
	sb.Line("")

	// Register flags
	for _, p := range op.Parameters {
		goType := flagGoType(p.Schema)
		flagVar := "flag" + toPascalCase(p.FlagName)
		desc := p.Description
		if len(p.Enum) > 0 {
			var vals []string
			for _, e := range p.Enum {
				vals = append(vals, fmt.Sprintf("%v", e))
			}
			desc += " (" + strings.Join(vals, ", ") + ")"
		}

		switch goType {
		case "string":
			defVal := ""
			if p.Default != nil {
				defVal = fmt.Sprintf("%v", p.Default)
			}
			sb.Linef("	cmd.Flags().StringVar(&%s, %q, %q, %q)", flagVar, p.FlagName, defVal, desc)
		case "int":
			defVal := 0
			if p.Default != nil {
				if f, ok := p.Default.(float64); ok {
					defVal = int(f)
				}
			}
			sb.Linef("	cmd.Flags().IntVar(&%s, %q, %d, %q)", flagVar, p.FlagName, defVal, desc)
		case "int64":
			defVal := int64(0)
			if p.Default != nil {
				if f, ok := p.Default.(float64); ok {
					defVal = int64(f)
				}
			}
			sb.Linef("	cmd.Flags().Int64Var(&%s, %q, %d, %q)", flagVar, p.FlagName, defVal, desc)
		case "bool":
			sb.Linef("	cmd.Flags().BoolVar(&%s, %q, false, %q)", flagVar, p.FlagName, desc)
		case "[]string":
			sb.Linef("	cmd.Flags().StringSliceVar(&%s, %q, nil, %q)", flagVar, p.FlagName, desc)
		}

		if p.Required {
			sb.Linef("	_ = cmd.MarkFlagRequired(%q)", p.FlagName)
		}
	}

	if op.RequestBody != nil {
		sb.Line(`	cmd.Flags().StringVar(&bodyJSON, "body", "", "Request body as JSON")`)
	}

	// Pagination flags for paginated operations
	if op.Pagination != nil {
		sb.Line("")
		sb.Line("	// Pagination flags")
		sb.Line(`	cmd.Flags().Bool("all", false, "Fetch all pages")`)
		sb.Line(`	cmd.Flags().Int("max-pages", 0, "Maximum pages to fetch (with --all, 0=unlimited)")`)
	}

	// Retry flags on all commands
	sb.Line("")
	sb.Line("	// Retry flags")
	sb.Line(`	cmd.Flags().Bool("no-retries", false, "Disable retries for this request")`)
	sb.Line(`	cmd.Flags().Int("retry-max-attempts", 0, "Override max retry attempts")`)
	sb.Line(`	cmd.Flags().String("retry-max-elapsed", "", "Override max elapsed retry time (e.g. 5m)")`)

	sb.Line("")
	sb.Line("	return cmd")
	sb.Line("}")
	sb.Line("")
}

// --- String builder helper ---

// StringBuilder is a convenience wrapper for building Go source code.
type StringBuilder struct {
	buf strings.Builder
}

func (s *StringBuilder) Line(line string) {
	s.buf.WriteString(line)
	s.buf.WriteByte('\n')
}

func (s *StringBuilder) Linef(format string, args ...any) {
	s.buf.WriteString(fmt.Sprintf(format, args...))
	s.buf.WriteByte('\n')
}

func (s *StringBuilder) String() string {
	return s.buf.String()
}

// --- Helpers ---

func toCamelCase(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool {
		return r == '-' || r == '_' || r == ' '
	})
	if len(parts) == 0 {
		return s
	}
	result := strings.ToLower(parts[0])
	for _, p := range parts[1:] {
		if len(p) > 0 {
			result += strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return result
}

func toPascalCase(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool {
		return r == '-' || r == '_' || r == ' '
	})
	var result string
	for _, p := range parts {
		if len(p) > 0 {
			result += strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return result
}

func flagGoType(s registry.SchemaMeta) string {
	switch s.Type {
	case "integer":
		if s.Format == "int64" {
			return "int64"
		}
		return "int"
	case "number":
		return "float64"
	case "boolean":
		return "bool"
	case "array":
		return "[]string"
	default:
		return "string"
	}
}

func quoteJoin(ss []string) string {
	var parts []string
	for _, s := range ss {
		parts = append(parts, fmt.Sprintf("%q", s))
	}
	return strings.Join(parts, ", ")
}

func writeFormatted(path string, content string) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("create dir %s: %w", dir, err)
	}

	// Try gofmt
	formatted, err := goformat.Source([]byte(content))
	if err != nil {
		// Write unformatted for debugging
		_ = os.WriteFile(path, []byte(content), 0o644)
		return fmt.Errorf("gofmt %s: %w", path, err)
	}

	return os.WriteFile(path, formatted, 0o644)
}

// RootData holds template data for the root command.
type RootData struct {
	AppName     string
	EnvPrefix   string
	Description string
	Servers     []registry.ServerConfig
}

// GroupData holds template data for a tag-group command file.
type GroupData struct {
	Tag        string
	AppName    string
	Operations []registry.OperationMeta
}

func toSnakeCase(s string) string {
	var result []byte
	for i, r := range s {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				result = append(result, '_')
			}
			result = append(result, byte(r+32))
		} else if r == '-' || r == ' ' {
			result = append(result, '_')
		} else {
			result = append(result, byte(r))
		}
	}
	return string(result)
}
