// Package cli generates Cobra command trees from the Operation Registry.
package cli

import (
	"fmt"
	goformat "go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/the-inconvenience-store/cliford/internal/codegen"
	"github.com/the-inconvenience-store/cliford/pkg/registry"
)

// SpinnerConfig controls the loading spinner in generated apps.
type SpinnerConfig struct {
	Enabled    bool
	Frames     []string
	IntervalMs int
}

// DefaultSpinnerConfig returns the default spinner settings.
func DefaultSpinnerConfig() SpinnerConfig {
	return SpinnerConfig{
		Enabled:    true,
		Frames:     []string{"⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"},
		IntervalMs: 80,
	}
}

// Generator produces Cobra CLI code from the Operation Registry.
type Generator struct {
	engine            *codegen.Engine
	outputDir         string
	appName           string
	pkgPath           string
	envPrefix         string
	customCodeRegions bool
	generateTUI       bool
	spinner           SpinnerConfig
}

// NewGenerator creates a CLI generator.
func NewGenerator(engine *codegen.Engine, outputDir, appName, envPrefix string) *Generator {
	return &Generator{
		engine:    engine,
		outputDir: outputDir,
		appName:   appName,
		envPrefix: envPrefix,
		spinner:   DefaultSpinnerConfig(),
	}
}

// SetSpinnerConfig sets the loading spinner configuration.
func (g *Generator) SetSpinnerConfig(cfg SpinnerConfig) {
	g.spinner = cfg
}

// SetCustomCodeRegions enables custom code region markers in generated output.
func (g *Generator) SetCustomCodeRegions(enabled bool) {
	g.customCodeRegions = enabled
}

// SetGenerateTUI enables TUI launch wiring in the root command.
func (g *Generator) SetGenerateTUI(enabled bool) {
	g.generateTUI = enabled
}

// SetPackagePath sets the Go module path for import statements.
func (g *Generator) SetPackagePath(pkgPath string) {
	g.pkgPath = pkgPath
}

// Generate produces all CLI source files from the registry.
// It generates the files directly using Go string building rather than
// Go text/template, because the generated output IS Go source code and
// template-in-template is error-prone.
func (g *Generator) Generate(reg *registry.Registry) error {
	cliDir := filepath.Join(g.outputDir, "internal", "cli")

	if err := os.MkdirAll(cliDir, 0o755); err != nil {
		return fmt.Errorf("create CLI dir: %w", err)
	}

	// Generate root command with all global flags
	if err := g.generateRoot(reg, cliDir); err != nil {
		return fmt.Errorf("generate root: %w", err)
	}

	// Generate one file per tag group with operation commands
	for tag, ops := range reg.TagGroups {
		if err := g.generateGroup(tag, ops, reg, cliDir); err != nil {
			return fmt.Errorf("generate group %s: %w", tag, err)
		}
	}

	return nil
}

func (g *Generator) generateRoot(reg *registry.Registry, cliDir string) error {
	var sb StringBuilder
	sb.Line("// Code generated by Cliford. DO NOT EDIT outside custom code regions.")
	sb.Line("package cli")
	sb.Line("")
	sb.Line("import (")
	sb.Line(`	"encoding/json"`)
	sb.Line(`	"fmt"`)
	sb.Line(`	"net/http"`)
	sb.Line(`	"os"`)
	sb.Line(`	"sort"`)
	sb.Line(`	"strings"`)
	sb.Line(`	"text/tabwriter"`)
	sb.Line(`	"time"`)
	sb.Line("")
	sb.Line(`	"github.com/spf13/cobra"`)
	sb.Line(`	"gopkg.in/yaml.v3"`)
	if g.generateTUI && g.pkgPath != "" {
		sb.Line("")
		sb.Linef("	\"%s/internal/tui\"", g.pkgPath)
	}
	sb.Line(")")
	sb.Line("")
	sb.Line("var (")
	sb.Line(`	outputFormat  string`)
	sb.Line(`	serverURL     string`)
	sb.Line(`	debugMode     bool`)
	sb.Line(`	dryRunMode    bool`)
	sb.Line(`	yesMode       bool`)
	sb.Line(`	agentMode     bool`)
	sb.Line(`	noInteractive bool`)
	sb.Line(`	tuiMode       bool`)
	sb.Line(`	timeout       string`)
	sb.Line("")
	sb.Line("	// apiClient is the shared HTTP client with auth, retry, and verbose transports.")
	sb.Line("	// Set via SetAPIClient() from main.go; falls back to a default client if nil.")
	sb.Line(`	apiClient *http.Client`)

	// Per-variable string vars for server URL template substitution
	if len(reg.Servers) > 0 && len(reg.Servers[0].Variables) > 0 {
		sb.Line("")
		sb.Line("	// Server URL template variables (from OpenAPI servers[0].variables).")
		sb.Line("	// Set via --server-<varname> persistent flags.")
		varNames := sortedStringKeys(reg.Servers[0].Variables)
		for _, varName := range varNames {
			sv := reg.Servers[0].Variables[varName]
			sb.Linef("	serverVar%s string // default: %q", toPascalCase(varName), sv.Default)
		}
	}

	sb.Line(")")
	sb.Line("")
	sb.Linef("// RootCmd returns the root Cobra command for %s.", g.appName)
	sb.Line("func RootCmd(appName string, version string) *cobra.Command {")
	sb.Line("	root := &cobra.Command{")
	sb.Linef("		Use:   %q,", g.appName)
	sb.Linef("		Short: %q,", reg.Description)
	sb.Line("		Version: version,")
	sb.Line("		SilenceUsage:  true,")
	sb.Line("		SilenceErrors: true,")
	if g.generateTUI {
		sb.Line("		PersistentPreRunE: func(cmd *cobra.Command, args []string) error {")
		sb.Line("			if tuiMode {")
		sb.Line("				if err := tui.Run(); err != nil {")
		sb.Line(`					return fmt.Errorf("TUI error: %w", err)`)
		sb.Line("				}")
		sb.Line("				os.Exit(0)")
		sb.Line("			}")
		sb.Line("			return nil")
		sb.Line("		},")
	}
	sb.Line("	}")
	sb.Line("")
	sb.Line("	pf := root.PersistentFlags()")
	sb.Line(`	pf.StringVarP(&outputFormat, "output-format", "o", "pretty", "Output format: pretty, json, yaml, table")`)
	sb.Line(`	pf.StringVar(&serverURL, "server", "", "Override API server URL")`)

	// Per-variable --server-<varname> flags
	if len(reg.Servers) > 0 && len(reg.Servers[0].Variables) > 0 {
		varNames := sortedStringKeys(reg.Servers[0].Variables)
		for _, varName := range varNames {
			sv := reg.Servers[0].Variables[varName]
			flagName := "server-" + toKebabCase(varName)
			goVar := "serverVar" + toPascalCase(varName)
			desc := sv.Description
			if desc == "" {
				desc = "Server URL variable: " + varName
			}
			sb.Linef("	pf.StringVar(&%s, %q, %q, %q)", goVar, flagName, sv.Default, desc)
		}
	}

	sb.Line(`	pf.StringVar(&timeout, "timeout", "30s", "Request timeout")`)
	sb.Line(`	pf.BoolVarP(&debugMode, "verbose", "v", false, "Log request/response to stderr (secrets redacted)")`)
	sb.Line(`	_ = pf.Bool("debug", false, "Alias for --verbose")`)
	sb.Line(`	_ = root.RegisterFlagCompletionFunc("debug", cobra.NoFileCompletions)`)
	sb.Line(`	pf.BoolVar(&dryRunMode, "dry-run", false, "Display HTTP request without executing")`)
	sb.Line(`	pf.BoolVarP(&yesMode, "yes", "y", false, "Skip all confirmations, use defaults")`)
	sb.Line(`	pf.BoolVar(&agentMode, "agent", false, "Force agent mode (structured JSON, no interactive)")`)
	sb.Line(`	pf.BoolVar(&noInteractive, "no-interactive", false, "Disable interactive prompts")`)
	sb.Line(`	pf.BoolVar(&tuiMode, "tui", false, "Launch full TUI mode")`)
	sb.Line("")

	// Sort tags for deterministic output
	var sortedTags []string
	for tag := range reg.TagGroups {
		sortedTags = append(sortedTags, tag)
	}
	sort.Strings(sortedTags)
	for _, tag := range sortedTags {
		sb.Linef("	root.AddCommand(%sCmd())", toCamelCase(tag))
	}
	sb.Line("	root.AddCommand(authCmd())")
	sb.Line("	root.AddCommand(configCmd())")
	sb.Line("	root.AddCommand(GenerateDocsCmd())")

	if g.customCodeRegions {
		sb.Line("")
		sb.Line("	// --- CUSTOM CODE START: root:init ---")
		sb.Line("	// --- CUSTOM CODE END: root:init ---")
	}

	// Add server info to help if servers defined
	if len(reg.Servers) > 1 {
		sb.Line("")
		sb.Line(`	root.Long = root.Short + "\n\nAvailable servers:"`)
		for _, s := range reg.Servers {
			desc := s.Description
			if desc == "" {
				desc = s.URL
			}
			sb.Linef("	root.Long += %q", fmt.Sprintf("\n  --server %s  (%s)", s.URL, desc))
		}
	}

	sb.Line("")
	sb.Line("	return root")
	sb.Line("}")
	sb.Line("")

	// FormatOutput helper
	sb.Line("// FormatOutput renders data in the requested output format.")
	sb.Line("func FormatOutput(data any, format string) error {")
	sb.Line(`	switch strings.ToLower(format) {`)
	sb.Line(`	case "json":`)
	sb.Line("		enc := json.NewEncoder(os.Stdout)")
	sb.Line(`		enc.SetIndent("", "  ")`)
	sb.Line("		return enc.Encode(data)")
	sb.Line(`	case "yaml":`)
	sb.Line("		enc := yaml.NewEncoder(os.Stdout)")
	sb.Line("		return enc.Encode(data)")
	sb.Line(`	case "table":`)
	sb.Line("		return formatTable(data)")
	sb.Line("	default:")
	sb.Line("		enc := json.NewEncoder(os.Stdout)")
	sb.Line(`		enc.SetIndent("", "  ")`)
	sb.Line("		return enc.Encode(data)")
	sb.Line("	}")
	sb.Line("}")
	sb.Line("")
	sb.Line("// formatTable renders an array of objects as a text table.")
	sb.Line("func formatTable(data any) error {")
	sb.Line("	items, ok := data.([]any)")
	sb.Line("	if !ok {")
	sb.Line("		// Not an array — fall back to JSON")
	sb.Line("		enc := json.NewEncoder(os.Stdout)")
	sb.Line(`		enc.SetIndent("", "  ")`)
	sb.Line("		return enc.Encode(data)")
	sb.Line("	}")
	sb.Line("	if len(items) == 0 {")
	sb.Line(`		fmt.Println("No results.")`)
	sb.Line("		return nil")
	sb.Line("	}")
	sb.Line("")
	sb.Line("	// Collect column headers from the first row")
	sb.Line("	firstRow, ok := items[0].(map[string]any)")
	sb.Line("	if !ok {")
	sb.Line("		enc := json.NewEncoder(os.Stdout)")
	sb.Line(`		enc.SetIndent("", "  ")`)
	sb.Line("		return enc.Encode(data)")
	sb.Line("	}")
	sb.Line("	var headers []string")
	sb.Line("	for k := range firstRow {")
	sb.Line("		headers = append(headers, k)")
	sb.Line("	}")
	sb.Line("	sort.Strings(headers)")
	sb.Line("")
	sb.Line("	w := tabwriter.NewWriter(os.Stdout, 0, 0, 2, ' ', 0)")
	sb.Line("	// Print headers")
	sb.Line(`	fmt.Fprintln(w, strings.Join(headers, "\t"))`)
	sb.Line("	// Print separator")
	sb.Line("	seps := make([]string, len(headers))")
	sb.Line("	for i, h := range headers {")
	sb.Line("		seps[i] = strings.Repeat(\"-\", len(h))")
	sb.Line("	}")
	sb.Line(`	fmt.Fprintln(w, strings.Join(seps, "\t"))`)
	sb.Line("	// Print rows")
	sb.Line("	for _, item := range items {")
	sb.Line("		row, ok := item.(map[string]any)")
	sb.Line("		if !ok { continue }")
	sb.Line("		vals := make([]string, len(headers))")
	sb.Line("		for i, h := range headers {")
	sb.Line(`			vals[i] = fmt.Sprintf("%v", row[h])`)
	sb.Line("		}")
	sb.Line(`		fmt.Fprintln(w, strings.Join(vals, "\t"))`)
	sb.Line("	}")
	sb.Line("	return w.Flush()")
	sb.Line("}")

	// SetAPIClient function
	sb.Line("")
	sb.Line("// SetAPIClient sets the shared HTTP client used by all generated commands.")
	sb.Line("// The client should be pre-configured with auth, retry, and verbose transport layers.")
	sb.Line("func SetAPIClient(c *http.Client) {")
	sb.Line("	apiClient = c")
	sb.Line("}")
	sb.Line("")
	sb.Line("// GetAPIClient returns the shared HTTP client, falling back to a default if not configured.")
	sb.Line("func GetAPIClient() *http.Client {")
	sb.Line("	if apiClient != nil {")
	sb.Line("		return apiClient")
	sb.Line("	}")
	sb.Line(`	return &http.Client{Timeout: 30 * time.Second}`)
	sb.Line("}")
	sb.Line("")
	sb.Line("// SetDefaultServerURL sets the server URL from config/env.")
	sb.Line("// This is overridden by the --server CLI flag if provided.")
	sb.Line("func SetDefaultServerURL(url string) {")
	sb.Line("	if serverURL == \"\" {")
	sb.Line("		serverURL = url")
	sb.Line("	}")
	sb.Line("}")
	sb.Line("")
	sb.Line("// VerboseFlag returns a pointer to the verbose/debug mode flag.")
	sb.Line("// Pass this to client.Options.VerboseFlag to enable request/response logging.")
	sb.Line("func VerboseFlag() *bool {")
	sb.Line("	return &debugMode")
	sb.Line("}")
	sb.Line("")
	sb.Line("// promptValue prompts the user for a value on stdin.")
	sb.Line("// Returns empty string if stdin is not a terminal.")
	sb.Line("func promptValue(label string) string {")
	sb.Line("	fi, _ := os.Stdin.Stat()")
	sb.Line("	if fi != nil && (fi.Mode()&os.ModeCharDevice) == 0 {")
	sb.Line(`		return "" // not a TTY — skip prompt`)
	sb.Line("	}")
	sb.Line("	fmt.Fprint(os.Stderr, label)")
	sb.Line("	var line string")
	sb.Line("	fmt.Scanln(&line)")
	sb.Line("	return strings.TrimSpace(line)")
	sb.Line("}")
	// Spinner: configurable loading animation
	if g.spinner.Enabled {
		// Build frames literal
		var frameParts []string
		for _, f := range g.spinner.Frames {
			frameParts = append(frameParts, fmt.Sprintf("%q", f))
		}
		framesLiteral := strings.Join(frameParts, ", ")

		sb.Line("")
		sb.Line("// withSpinner displays a loading indicator on stderr while a function runs.")
		sb.Line("// It only shows when stderr is a terminal. Returns the function's results.")
		sb.Line("func withSpinner[T any](label string, fn func() (T, error)) (T, error) {")
		sb.Line("	fi, _ := os.Stderr.Stat()")
		sb.Line("	if fi == nil || (fi.Mode()&os.ModeCharDevice) == 0 || noInteractive || agentMode {")
		sb.Line("		return fn()")
		sb.Line("	}")
		sb.Line("")
		sb.Linef("	frames := []string{%s}", framesLiteral)
		sb.Line("	done := make(chan struct{})")
		sb.Line("	go func() {")
		sb.Line("		i := 0")
		sb.Line("		for {")
		sb.Line("			select {")
		sb.Line("			case <-done:")
		sb.Line(`				fmt.Fprintf(os.Stderr, "\r%s\r", strings.Repeat(" ", len(label)+4))`)
		sb.Line("				return")
		sb.Line("			default:")
		sb.Line(`				fmt.Fprintf(os.Stderr, "\r%s %s", frames[i%len(frames)], label)`)
		sb.Line("				i++")
		sb.Linef("				time.Sleep(%d * time.Millisecond)", g.spinner.IntervalMs)
		sb.Line("			}")
		sb.Line("		}")
		sb.Line("	}()")
		sb.Line("")
		sb.Line("	result, err := fn()")
		sb.Line("	close(done)")
		sb.Line("	return result, err")
		sb.Line("}")
	} else {
		// When spinner is disabled, generate a pass-through withSpinner
		sb.Line("")
		sb.Line("// withSpinner is a no-op when spinner is disabled in cliford.yaml.")
		sb.Line("func withSpinner[T any](_ string, fn func() (T, error)) (T, error) {")
		sb.Line("	return fn()")
		sb.Line("}")
	}

	return writeFormatted(filepath.Join(cliDir, "root.go"), sb.String())
}

func (g *Generator) generateGroup(tag string, ops []registry.OperationMeta, reg *registry.Registry, cliDir string) error {
	// Determine which imports are needed
	needsBytes := false
	needsContext := false
	for _, op := range ops {
		if op.RequestBody != nil {
			needsBytes = true
		}
		if op.Timeout != nil {
			needsContext = true
		}
	}

	// needsSlices is true when any server variable defines an enum — we emit
	// slices.Contains validation in every operation RunE for those variables.
	needsSlices := false
	if len(reg.Servers) > 0 {
		for _, sv := range reg.Servers[0].Variables {
			if len(sv.Enum) > 0 {
				needsSlices = true
				break
			}
		}
	}

	var sb StringBuilder
	sb.Line("// Code generated by Cliford. DO NOT EDIT outside custom code regions.")
	sb.Line("package cli")
	sb.Line("")
	sb.Line("import (")
	if needsBytes {
		sb.Line(`	"bytes"`)
	}
	if needsContext {
		sb.Line(`	"context"`)
	}
	sb.Line(`	"encoding/json"`)
	sb.Line(`	"fmt"`)
	sb.Line(`	"io"`)
	sb.Line(`	"net/http"`)
	sb.Line(`	"net/url"`)
	sb.Line(`	"os"`)
	if needsSlices {
		sb.Line(`	"slices"`)
	}
	sb.Line(`	"strings"`)
	if needsContext {
		sb.Line(`	"time"`)
	}
	sb.Line("")
	sb.Line(`	"github.com/spf13/cobra"`)
	sb.Line(")")
	sb.Line("")

	// Tag group command
	tagPrefix := toCamelCase(tag)
	sb.Linef("func %sCmd() *cobra.Command {", tagPrefix)
	sb.Line("	cmd := &cobra.Command{")
	sb.Linef("		Use:   %q,", strings.ToLower(tag))
	sb.Linef("		Short: %q,", tag+" operations")
	sb.Line("	}")
	sb.Line("")
	for _, op := range ops {
		sb.Linef("	cmd.AddCommand(%s%sCmd())", tagPrefix, toPascalCase(op.CLICommandName))
	}
	sb.Line("")
	sb.Line("	return cmd")
	sb.Line("}")
	sb.Line("")

	// Each operation command - prefixed with tag name to avoid collisions
	for _, op := range ops {
		g.generateOperationCmd(&sb, op, reg, tagPrefix)
	}

	return writeFormatted(filepath.Join(cliDir, toSnakeCase(tag)+".go"), sb.String())
}

func (g *Generator) generateOperationCmd(sb *StringBuilder, op registry.OperationMeta, reg *registry.Registry, tagPrefix string) {
	funcName := tagPrefix + toPascalCase(op.CLICommandName)

	// Build existing param flag name set for collision detection
	existingParamFlags := make(map[string]bool)
	for _, p := range op.Parameters {
		existingParamFlags[p.FlagName] = true
	}
	// Also reserve "body" flag name to avoid collision with --body JSON flag
	if op.RequestBody != nil {
		existingParamFlags["body"] = true
	}

	// Determine if we have body properties to expand
	hasBodyProps := op.RequestBody != nil && len(op.RequestBody.Schema.Properties) > 0
	sortedProps := sortedSchemaKeys(func() map[string]registry.SchemaMeta {
		if op.RequestBody != nil {
			return op.RequestBody.Schema.Properties
		}
		return nil
	}())

	sb.Linef("func %sCmd() *cobra.Command {", funcName)

	// Flag variables for path/query/header params
	for _, p := range op.Parameters {
		goType := flagGoType(p.Schema)
		sb.Linef("	var flag%s %s", toPascalCase(p.FlagName), goType)
	}
	// Body: individual property flags or fallback JSON
	if hasBodyProps {
		for _, propName := range sortedProps {
			propSchema := op.RequestBody.Schema.Properties[propName]
			varName := "bodyProp" + toPascalCase(propName)
			sb.Linef("	var %s %s", varName, flagGoType(propSchema))
		}
	}
	if op.RequestBody != nil {
		sb.Line("	var bodyJSON string")
	}
	sb.Line("")

	sb.Line("	cmd := &cobra.Command{")
	sb.Linef("		Use:   %q,", op.CLICommandName)
	sb.Linef("		Short: %q,", op.Summary)
	if op.Description != "" {
		sb.Linef("		Long:  %q,", wrapText(op.Description, 80))
	}
	if len(op.CLIAliases) > 0 {
		sb.Linef("		Aliases: []string{%s},", quoteJoin(op.CLIAliases))
	}
	if op.CLIHidden {
		sb.Line("		Hidden: true,")
	}

	sb.Line("		RunE: func(cmd *cobra.Command, args []string) error {")

	// Prompt for missing required parameters (interactive TTY only)
	requiredParams := []registry.ParamMeta{}
	for _, p := range op.Parameters {
		if p.Required {
			requiredParams = append(requiredParams, p)
		}
	}
	if len(requiredParams) > 0 {
		sb.Line("			// Interactive prompts for missing required args")
		sb.Line("			if !noInteractive && !agentMode {")
		for _, p := range requiredParams {
			flagVar := "flag" + toPascalCase(p.FlagName)
			goType := flagGoType(p.Schema)
			if goType == "string" {
				sb.Linef("				if !cmd.Flags().Changed(%q) && %s == \"\" {", p.FlagName, flagVar)
				sb.Linef("					%s = promptValue(%q)", flagVar, p.FlagName+": ")
				sb.Linef("					if %s == \"\" {", flagVar)
				sb.Linef("						return fmt.Errorf(\"required flag --%s not provided\")", p.FlagName)
				sb.Line("					}")
				sb.Line("				}")
			}
		}
		sb.Line("			}")
		sb.Line("")
	}

	// Confirmation prompt for destructive operations
	needsConfirm := op.CLIConfirm || op.Method == "DELETE"
	if needsConfirm {
		confirmMsg := op.CLIConfirmMsg
		if confirmMsg == "" {
			confirmMsg = fmt.Sprintf("Are you sure you want to %s?", op.CLICommandName)
		}
		sb.Line("			// Confirm destructive operation")
		sb.Line("			if !yesMode {")
		sb.Linef("				answer := promptValue(%q)", confirmMsg+" [y/N]: ")
		sb.Line("				if answer != \"y\" && answer != \"Y\" && answer != \"yes\" {")
		sb.Line(`					fmt.Fprintln(os.Stderr, "Aborted.")`)
		sb.Line("					return nil")
		sb.Line("				}")
		sb.Line("			}")
		sb.Line("")
	}

	// Apply per-operation timeout via context if configured
	if op.Timeout != nil {
		sb.Linef("			ctx, cancel := context.WithTimeout(cmd.Context(), %d*time.Nanosecond)", op.Timeout.Nanoseconds())
		sb.Line("			defer cancel()")
	}
	sb.Line("")

	// Determine base URL
	defaultURL := "http://localhost:8080"
	if len(reg.Servers) > 0 {
		defaultURL = reg.Servers[0].URL
	}
	sb.Linef("			baseURL := %q", defaultURL)
	sb.Line("			if serverURL != \"\" {")
	sb.Line("				baseURL = serverURL")
	sb.Line("			} else {")
	if len(reg.Servers) > 0 && len(reg.Servers[0].Variables) > 0 {
		sb.Line("				// Apply server URL template variable substitution")
		sb.Line("				baseURL = strings.NewReplacer(")
		varNames := sortedStringKeys(reg.Servers[0].Variables)
		for _, varName := range varNames {
			goVar := "serverVar" + toPascalCase(varName)
			sb.Linef("					%q, %s,", "{"+varName+"}", goVar)
		}
		sb.Line("				).Replace(baseURL)")
	}
	sb.Line("			}")
	sb.Line("")

	// Enum validation for server URL template variables
	if len(reg.Servers) > 0 && len(reg.Servers[0].Variables) > 0 {
		varNames := sortedStringKeys(reg.Servers[0].Variables)
		for _, varName := range varNames {
			sv := reg.Servers[0].Variables[varName]
			if len(sv.Enum) > 0 {
				goVar := "serverVar" + toPascalCase(varName)
				flagName := "server-" + toKebabCase(varName)
				sb.Linef("			if !slices.Contains([]string{%s}, %s) {", quoteJoin(sv.Enum), goVar)
				sb.Linef("				return fmt.Errorf(\"invalid --%s value %%q: allowed values are %v\", %s)", flagName, sv.Enum, goVar)
				sb.Line("			}")
		}
		}
		sb.Line("")
	}

	// Build path with parameter substitution
	sb.Linef("			reqPath := %q", op.Path)
	for _, p := range op.Parameters {
		if p.In == registry.ParamLocationPath {
			sb.Linef(`			reqPath = strings.Replace(reqPath, "{%s}", fmt.Sprintf("%%v", flag%s), 1)`, p.Name, toPascalCase(p.FlagName))
		}
	}
	sb.Line("")

	sb.Line("			reqURL, err := url.Parse(baseURL + reqPath)")
	sb.Line("			if err != nil {")
	sb.Line(`				return fmt.Errorf("invalid URL: %w", err)`)
	sb.Line("			}")
	sb.Line("")

	// Query parameters
	hasQuery := false
	for _, p := range op.Parameters {
		if p.In == registry.ParamLocationQuery {
			hasQuery = true
			break
		}
	}
	if hasQuery {
		sb.Line("			q := reqURL.Query()")
		for _, p := range op.Parameters {
			if p.In != registry.ParamLocationQuery {
				continue
			}
			goType := flagGoType(p.Schema)
			flagVar := "flag" + toPascalCase(p.FlagName)
			switch goType {
			case "string":
				sb.Linef("			if %s != \"\" {", flagVar)
				sb.Linef("				q.Set(%q, %s)", p.Name, flagVar)
				sb.Line("			}")
			case "int", "int64":
				sb.Linef("			if cmd.Flags().Changed(%q) {", p.FlagName)
				sb.Linef("				q.Set(%q, fmt.Sprintf(\"%%d\", %s))", p.Name, flagVar)
				sb.Line("			}")
			case "bool":
				sb.Linef("			if cmd.Flags().Changed(%q) {", p.FlagName)
				sb.Linef("				q.Set(%q, fmt.Sprintf(\"%%t\", %s))", p.Name, flagVar)
				sb.Line("			}")
			}
		}
		sb.Line("			reqURL.RawQuery = q.Encode()")
		sb.Line("")
	}

	// Request body
	sb.Line("			var reqBody io.Reader")
	if hasBodyProps {
		// Merge stdin → --body → individual flags, then validate
		sb.Line("			{")
		sb.Line("				bodyFields := make(map[string]any)")
		sb.Line("				// stdin base layer")
		sb.Line("				{")
		sb.Line("					stat, _ := os.Stdin.Stat()")
		sb.Line("					if stat != nil && (stat.Mode()&os.ModeCharDevice) == 0 {")
		sb.Line("						if data, err := io.ReadAll(os.Stdin); err == nil && len(data) > 0 {")
		sb.Line("							_ = json.Unmarshal(data, &bodyFields)")
		sb.Line("						}")
		sb.Line("					}")
		sb.Line("				}")
		sb.Line("				// --body JSON override")
		sb.Line("				if bodyJSON != \"\" {")
		sb.Line("					var override map[string]any")
		sb.Line("					if err := json.Unmarshal([]byte(bodyJSON), &override); err != nil {")
		sb.Line(`					    return fmt.Errorf("invalid --body JSON: %w", err)`)
		sb.Line("					}")
		sb.Line("					for k, v := range override {")
		sb.Line("						bodyFields[k] = v")
		sb.Line("					}")
		sb.Line("				}")
		sb.Line("				// individual flags (highest priority)")
		for _, propName := range sortedProps {
			propSchema := op.RequestBody.Schema.Properties[propName]
			flagName := bodyPropFlagName(propName, existingParamFlags)
			varName := "bodyProp" + toPascalCase(propName)
			if len(propSchema.Enum) > 0 {
				enumVals := enumStrings(propSchema.Enum)
				sb.Linef("				if cmd.Flags().Changed(%q) {", flagName)
				sb.Linef("					valid%s := []string{%s}", toPascalCase(propName), quoteJoin(enumVals))
				sb.Line("					found := false")
				sb.Linef("					for _, v := range valid%s {", toPascalCase(propName))
				sb.Linef("						if v == %s { found = true; break }", varName)
				sb.Line("					}")
				sb.Line("					if !found {")
				sb.Linef("						return fmt.Errorf(%q+\": must be one of: %%s\", strings.Join(valid%s, \", \"))", propName, toPascalCase(propName))
				sb.Line("					}")
				sb.Linef("					bodyFields[%q] = %s", propName, varName)
				sb.Line("				}")
			} else {
				sb.Linef("				if cmd.Flags().Changed(%q) { bodyFields[%q] = %s }", flagName, propName, varName)
			}
		}
		// Validate required fields after merge
		if len(op.RequestBody.Schema.Required) > 0 {
			sb.Line("				// validate required fields")
			for _, reqProp := range op.RequestBody.Schema.Required {
				flagName := bodyPropFlagName(reqProp, existingParamFlags)
				sb.Linef("				if _, ok := bodyFields[%q]; !ok {", reqProp)
				sb.Linef("					return fmt.Errorf(\"required field --%s is missing; use --%s or --body\")", flagName, flagName)
				sb.Line("				}")
			}
		}
		sb.Line("				if len(bodyFields) > 0 {")
		sb.Line("					b, err := json.Marshal(bodyFields)")
		sb.Line("					if err != nil {")
		sb.Line(`						return fmt.Errorf("marshal body: %w", err)`)
		sb.Line("					}")
		sb.Line("					reqBody = bytes.NewReader(b)")
		sb.Line("				}")
		sb.Line("			}")
	} else if op.RequestBody != nil {
		// No schema properties: accept raw --body JSON or stdin
		sb.Line("			if bodyJSON != \"\" {")
		sb.Line("				reqBody = strings.NewReader(bodyJSON)")
		sb.Line("			} else {")
		sb.Line("				stat, _ := os.Stdin.Stat()")
		sb.Line("				if stat != nil && (stat.Mode()&os.ModeCharDevice) == 0 {")
		sb.Line("					data, err := io.ReadAll(os.Stdin)")
		sb.Line("					if err == nil && len(data) > 0 {")
		sb.Line("						reqBody = bytes.NewReader(data)")
		sb.Line("					}")
		sb.Line("				}")
		sb.Line("			}")
	}
	sb.Line("")

	// Create request with context (carries per-operation timeout if set)
	if op.Timeout != nil {
		sb.Linef("			req, err := http.NewRequestWithContext(ctx, %q, reqURL.String(), reqBody)", op.Method)
	} else {
		sb.Linef("			req, err := http.NewRequestWithContext(cmd.Context(), %q, reqURL.String(), reqBody)", op.Method)
	}
	sb.Line("			if err != nil {")
	sb.Line(`				return fmt.Errorf("create request: %w", err)`)
	sb.Line("			}")

	// Header parameters
	for _, p := range op.Parameters {
		if p.In == registry.ParamLocationHeader {
			flagVar := "flag" + toPascalCase(p.FlagName)
			sb.Linef("			if %s != \"\" {", flagVar)
			sb.Linef("				req.Header.Set(%q, %s)", p.Name, flagVar)
			sb.Line("			}")
		}
	}
	if op.RequestBody != nil {
		sb.Line("			if reqBody != nil {")
		sb.Line(`				req.Header.Set("Content-Type", "application/json")`)
		sb.Line("			}")
	}
	sb.Line("")

	// Custom code region: pre-request
	if g.customCodeRegions {
		sb.Linef("			// --- CUSTOM CODE START: %s:pre ---", op.OperationID)
		sb.Linef("			// --- CUSTOM CODE END: %s:pre ---", op.OperationID)
		sb.Line("")
	}

	// Dry-run
	sb.Line("			if dryRunMode {")
	sb.Line(`				fmt.Fprintf(os.Stdout, "%s %s\n", req.Method, req.URL.String())`)
	sb.Line("				for k, v := range req.Header {")
	sb.Line(`					fmt.Fprintf(os.Stdout, "%s: %s\n", k, strings.Join(v, ", "))`)
	sb.Line("				}")
	sb.Line("				return nil")
	sb.Line("			}")
	sb.Line("")

	// Pagination: --all fetch loop (early return path for paginated operations)
	if op.Pagination != nil && op.Pagination.OutputResults != "" {
		sb.Line(`			fetchAll, _ := cmd.Flags().GetBool("all")`)
		sb.Line(`			maxPages, _ := cmd.Flags().GetInt("max-pages")`)
		sb.Line("			if fetchAll {")
		sb.Line("				if maxPages <= 0 { maxPages = 1000 }")
		sb.Line("				var allResults []any")
		sb.Line("				cursor := \"\"")
		sb.Line("				for page := 0; page < maxPages; page++ {")
		sb.Line("					pageReq := req.Clone(req.Context())")
		sb.Line("					if cursor != \"\" {")
		sb.Linef("						q := pageReq.URL.Query()")
		sb.Linef("						q.Set(%q, cursor)", op.Pagination.InputCursor.Name)
		sb.Line("						pageReq.URL.RawQuery = q.Encode()")
		sb.Line("					}")
		sb.Line("					resp, err := GetAPIClient().Do(pageReq)")
		sb.Line("					if err != nil {")
		sb.Line(`						return fmt.Errorf("request failed on page %d: %w", page+1, err)`)
		sb.Line("					}")
		sb.Line("					body, _ := io.ReadAll(resp.Body)")
		sb.Line("					resp.Body.Close()")
		sb.Line("					if resp.StatusCode >= 400 {")
		sb.Line(`						return fmt.Errorf("HTTP %d: %s", resp.StatusCode, string(body))`)
		sb.Line("					}")
		sb.Line("					var pageData map[string]any")
		sb.Line("					if err := json.Unmarshal(body, &pageData); err != nil {")
		sb.Line("						break")
		sb.Line("					}")
		// Extract results array
		resultField := strings.TrimPrefix(op.Pagination.OutputResults, "$.")
		sb.Linef("					if items, ok := pageData[%q]; ok {", resultField)
		sb.Line("						if arr, ok := items.([]any); ok {")
		sb.Line("							allResults = append(allResults, arr...)")
		sb.Line("						}")
		sb.Line("					}")
		// Extract next cursor
		if op.Pagination.OutputNextKey != "" {
			nextField := strings.TrimPrefix(op.Pagination.OutputNextKey, "$.")
			sb.Linef("					if next, ok := pageData[%q]; ok && next != nil {", nextField)
			sb.Line("						if s, ok := next.(string); ok && s != \"\" {")
			sb.Line("							cursor = s")
			sb.Line("							continue")
			sb.Line("						}")
			sb.Line("					}")
		}
		sb.Line("					break // No more pages")
		sb.Line("				}")
		sb.Line("				return FormatOutput(allResults, outputFormat)")
		sb.Line("			}")
		sb.Line("")
	}

	// Execute using shared API client (pre-configured with auth/retry/verbose transports)
	sb.Line("			resp, err := withSpinner(\"Loading...\", func() (*http.Response, error) {")
	sb.Line("				return GetAPIClient().Do(req)")
	sb.Line("			})")
	sb.Line("			if err != nil {")
	sb.Line(`				return fmt.Errorf("request failed: %w", err)`)
	sb.Line("			}")
	sb.Line("			defer resp.Body.Close()")
	sb.Line("")
	sb.Line("			respBody, err := io.ReadAll(resp.Body)")
	sb.Line("			if err != nil {")
	sb.Line(`				return fmt.Errorf("read response: %w", err)`)
	sb.Line("			}")
	sb.Line("")

	// Handle errors
	sb.Line("			if resp.StatusCode >= 400 {")
	sb.Line(`				return fmt.Errorf("HTTP %d: %s", resp.StatusCode, string(respBody))`)
	sb.Line("			}")
	sb.Line("")

	// Handle 204 No Content
	sb.Line("			if resp.StatusCode == 204 || len(respBody) == 0 {")
	sb.Line(`				fmt.Println("OK")`)
	sb.Line("				return nil")
	sb.Line("			}")
	sb.Line("")

	// Format output
	sb.Line("			var data any")
	sb.Line("			if err := json.Unmarshal(respBody, &data); err != nil {")
	sb.Line("				fmt.Println(string(respBody))")
	sb.Line("				return nil")
	sb.Line("			}")
	// Custom code region: post-response
	if g.customCodeRegions {
		sb.Line("")
		sb.Linef("			// --- CUSTOM CODE START: %s:post ---", op.OperationID)
		sb.Linef("			// --- CUSTOM CODE END: %s:post ---", op.OperationID)
	}

	sb.Line("			return FormatOutput(data, outputFormat)")

	sb.Line("		},")
	sb.Line("	}")
	sb.Line("")

	// Register path/query/header flags
	for _, p := range op.Parameters {
		goType := flagGoType(p.Schema)
		flagVar := "flag" + toPascalCase(p.FlagName)
		desc := p.Description
		if len(p.Enum) > 0 {
			var vals []string
			for _, e := range p.Enum {
				vals = append(vals, fmt.Sprintf("%v", e))
			}
			desc += " (" + strings.Join(vals, ", ") + ")"
		}

		switch goType {
		case "string":
			defVal := ""
			if p.Default != nil {
				defVal = fmt.Sprintf("%v", p.Default)
			}
			sb.Linef("	cmd.Flags().StringVar(&%s, %q, %q, %q)", flagVar, p.FlagName, defVal, desc)
		case "int":
			defVal := 0
			if p.Default != nil {
				if f, ok := p.Default.(float64); ok {
					defVal = int(f)
				}
			}
			sb.Linef("	cmd.Flags().IntVar(&%s, %q, %d, %q)", flagVar, p.FlagName, defVal, desc)
		case "int64":
			defVal := int64(0)
			if p.Default != nil {
				if f, ok := p.Default.(float64); ok {
					defVal = int64(f)
				}
			}
			sb.Linef("	cmd.Flags().Int64Var(&%s, %q, %d, %q)", flagVar, p.FlagName, defVal, desc)
		case "bool":
			sb.Linef("	cmd.Flags().BoolVar(&%s, %q, false, %q)", flagVar, p.FlagName, desc)
		case "[]string":
			sb.Linef("	cmd.Flags().StringSliceVar(&%s, %q, nil, %q)", flagVar, p.FlagName, desc)
		case "float64":
			sb.Linef("	cmd.Flags().Float64Var(&%s, %q, 0, %q)", flagVar, p.FlagName, desc)
		}

		if p.Required {
			sb.Linef("	_ = cmd.MarkFlagRequired(%q)", p.FlagName)
		}
	}

	// Register body property flags (individual)
	if hasBodyProps {
		sb.Line("")
		// Build required set
		requiredSet := make(map[string]bool)
		for _, r := range op.RequestBody.Schema.Required {
			requiredSet[r] = true
		}
		for _, propName := range sortedProps {
			propSchema := op.RequestBody.Schema.Properties[propName]
			flagName := bodyPropFlagName(propName, existingParamFlags)
			varName := "bodyProp" + toPascalCase(propName)
			desc := propSchema.Description
			if len(propSchema.Enum) > 0 {
				enumDesc := strings.Join(enumStrings(propSchema.Enum), ", ")
				if desc == "" {
					desc = "One of: " + enumDesc
				} else {
					desc += " (" + enumDesc + ")"
				}
			}
			switch flagGoType(propSchema) {
			case "string":
				sb.Linef("	cmd.Flags().StringVar(&%s, %q, %q, %q)", varName, flagName, "", desc)
			case "int":
				sb.Linef("	cmd.Flags().IntVar(&%s, %q, 0, %q)", varName, flagName, desc)
			case "int64":
				sb.Linef("	cmd.Flags().Int64Var(&%s, %q, 0, %q)", varName, flagName, desc)
			case "bool":
				sb.Linef("	cmd.Flags().BoolVar(&%s, %q, false, %q)", varName, flagName, desc)
			case "[]string":
				sb.Linef("	cmd.Flags().StringSliceVar(&%s, %q, nil, %q)", varName, flagName, desc)
			case "float64":
				sb.Linef("	cmd.Flags().Float64Var(&%s, %q, 0, %q)", varName, flagName, desc)
			}
		}
		sb.Line(`	cmd.Flags().StringVar(&bodyJSON, "body", "", "Request body as JSON (overrides individual flags)")`)
	} else if op.RequestBody != nil {
		sb.Line(`	cmd.Flags().StringVar(&bodyJSON, "body", "", "Request body as JSON")`)
	}

	// Pagination flags for paginated operations
	if op.Pagination != nil {
		sb.Line("")
		sb.Line("	// Pagination flags")
		sb.Line(`	cmd.Flags().Bool("all", false, "Fetch all pages")`)
		sb.Line(`	cmd.Flags().Int("max-pages", 0, "Maximum pages to fetch (with --all, 0=unlimited)")`)
		switch op.Pagination.Type {
		case registry.PaginationCursor:
			sb.Linef("	cmd.Flags().String(%q, \"\", \"Pagination cursor for next page\")", op.Pagination.InputCursor.Name)
		case registry.PaginationOffset:
			sb.Linef("	cmd.Flags().Int(%q, 0, \"Offset for pagination\")", op.Pagination.InputCursor.Name)
		case registry.PaginationPage:
			sb.Linef("	cmd.Flags().Int(%q, 1, \"Page number\")", op.Pagination.InputCursor.Name)
		}
		if op.Pagination.InputLimit.Name != "" {
			sb.Linef("	cmd.Flags().Int(%q, %d, \"Number of items per page\")", op.Pagination.InputLimit.Name, op.Pagination.DefaultLimit)
		}
	}

	// Retry flags on all commands
	sb.Line("")
	sb.Line("	// Retry flags")
	sb.Line(`	cmd.Flags().Bool("no-retries", false, "Disable retries for this request")`)
	sb.Line(`	cmd.Flags().Int("retry-max-attempts", 0, "Override max retry attempts")`)
	sb.Line(`	cmd.Flags().String("retry-max-elapsed", "", "Override max elapsed retry time (e.g. 5m)")`)

	sb.Line("")
	sb.Line("	return cmd")
	sb.Line("}")
	sb.Line("")
}

// --- String builder helper ---

// StringBuilder is a convenience wrapper for building Go source code.
type StringBuilder struct {
	buf strings.Builder
}

func (s *StringBuilder) Line(line string) {
	s.buf.WriteString(line)
	s.buf.WriteByte('\n')
}

func (s *StringBuilder) Linef(format string, args ...any) {
	s.buf.WriteString(fmt.Sprintf(format, args...))
	s.buf.WriteByte('\n')
}

func (s *StringBuilder) String() string {
	return s.buf.String()
}

// --- Helpers ---

func toCamelCase(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool {
		return r == '-' || r == '_' || r == ' '
	})
	if len(parts) == 0 {
		return s
	}
	result := strings.ToLower(parts[0])
	for _, p := range parts[1:] {
		if len(p) > 0 {
			result += strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return result
}

func toPascalCase(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool {
		return r == '-' || r == '_' || r == ' '
	})
	var result string
	for _, p := range parts {
		if len(p) > 0 {
			result += strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return result
}

func flagGoType(s registry.SchemaMeta) string {
	switch s.Type {
	case "integer":
		if s.Format == "int64" {
			return "int64"
		}
		return "int"
	case "number":
		return "float64"
	case "boolean":
		return "bool"
	case "array":
		return "[]string"
	default:
		return "string"
	}
}

func quoteJoin(ss []string) string {
	var parts []string
	for _, s := range ss {
		parts = append(parts, fmt.Sprintf("%q", s))
	}
	return strings.Join(parts, ", ")
}

func writeFormatted(path string, content string) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("create dir %s: %w", dir, err)
	}

	// Try gofmt
	formatted, err := goformat.Source([]byte(content))
	if err != nil {
		// Write unformatted for debugging
		_ = os.WriteFile(path, []byte(content), 0o644)
		return fmt.Errorf("gofmt %s: %w", path, err)
	}

	return os.WriteFile(path, formatted, 0o644)
}

// RootData holds template data for the root command.
type RootData struct {
	AppName     string
	EnvPrefix   string
	Description string
	Servers     []registry.ServerConfig
}

// GroupData holds template data for a tag-group command file.
type GroupData struct {
	Tag        string
	AppName    string
	Operations []registry.OperationMeta
}

// bodyPropFlagName returns the CLI flag name for a body property,
// prefixing with "body-" only if the name collides with an existing param flag.
func bodyPropFlagName(propName string, existingParamFlags map[string]bool) string {
	name := toKebabCase(propName)
	if existingParamFlags[name] {
		return "body-" + name
	}
	return name
}

// toKebabCase converts camelCase or PascalCase to kebab-case.
func toKebabCase(s string) string {
	var result []byte
	for i, r := range s {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				result = append(result, '-')
			}
			result = append(result, byte(r+32))
		} else if r == '_' || r == ' ' {
			result = append(result, '-')
		} else {
			result = append(result, byte(r))
		}
	}
	return string(result)
}

// sortedSchemaKeys returns the keys of a schema properties map in sorted order.
func sortedSchemaKeys(m map[string]registry.SchemaMeta) []string {
	if m == nil {
		return nil
	}
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// enumStrings converts []any enum values to []string.
func enumStrings(enum []any) []string {
	result := make([]string, len(enum))
	for i, e := range enum {
		result[i] = fmt.Sprintf("%v", e)
	}
	return result
}

// wrapText wraps text at the given column width, preserving existing newlines.
func wrapText(text string, width int) string {
	if len(text) <= width {
		return text
	}
	var result strings.Builder
	for _, paragraph := range strings.Split(text, "\n") {
		if result.Len() > 0 {
			result.WriteByte('\n')
		}
		line := ""
		for _, word := range strings.Fields(paragraph) {
			if line == "" {
				line = word
			} else if len(line)+1+len(word) > width {
				result.WriteString(line)
				result.WriteByte('\n')
				line = word
			} else {
				line += " " + word
			}
		}
		result.WriteString(line)
	}
	return result.String()
}

func toSnakeCase(s string) string {
	var result []byte
	for i, r := range s {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				result = append(result, '_')
			}
			result = append(result, byte(r+32))
		} else if r == '-' || r == ' ' {
			result = append(result, '_')
		} else {
			result = append(result, byte(r))
		}
	}
	return string(result)
}

// sortedStringKeys returns the keys of any map[string]V sorted alphabetically.
// Used wherever we iterate over maps to produce deterministic generated output.
func sortedStringKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
