// Package distribution generates release and distribution configuration
// for apps produced by Cliford.
package distribution

import (
	"fmt"
	"os"
	"path/filepath"
)

// GoReleaserGenerator produces .goreleaser.yaml for cross-platform builds.
type GoReleaserGenerator struct {
	outputDir string
	appName   string
	pkgPath   string
	owner     string
}

// NewGoReleaserGenerator creates a GoReleaser config generator.
func NewGoReleaserGenerator(outputDir, appName, pkgPath string) *GoReleaserGenerator {
	return &GoReleaserGenerator{outputDir: outputDir, appName: appName, pkgPath: pkgPath, owner: appName}
}

// SetOwner sets the GitHub repo owner for release configuration.
func (g *GoReleaserGenerator) SetOwner(owner string) {
	if owner != "" {
		g.owner = owner
	}
}

// Generate produces .goreleaser.yaml and the GitHub Actions release workflow.
func (g *GoReleaserGenerator) Generate() error {
	if err := g.generateGoReleaser(); err != nil {
		return err
	}
	if err := g.generateReleaseWorkflow(); err != nil {
		return err
	}
	return nil
}

func (g *GoReleaserGenerator) generateGoReleaser() error {
	config := fmt.Sprintf(`# Generated by Cliford. Edit as needed.
version: 2

project_name: %s

builds:
  - id: %s
    main: ./cmd/%s/
    binary: %s
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.appTitle=%s

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

release:
  github:
    owner: %s
    name: %s
  draft: false
  prerelease: auto
`, g.appName, g.appName, g.appName, g.appName, g.appName, g.owner, g.appName)

	return os.WriteFile(filepath.Join(g.outputDir, ".goreleaser.yaml"), []byte(config), 0o644)
}

func (g *GoReleaserGenerator) generateReleaseWorkflow() error {
	workflowDir := filepath.Join(g.outputDir, ".github", "workflows")
	if err := os.MkdirAll(workflowDir, 0o755); err != nil {
		return err
	}

	workflow := fmt.Sprintf(`# Generated by Cliford. Edit as needed.
name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - uses: goreleaser/goreleaser-action@v6
        with:
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
`)

	return os.WriteFile(filepath.Join(workflowDir, "release.yaml"), []byte(workflow), 0o644)
}
