package distribution

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// HomebrewGenerator produces a Homebrew formula template for the generated app.
type HomebrewGenerator struct {
	outputDir string
	appName   string
	repoOwner string
	repoName  string
	desc      string
}

// NewHomebrewGenerator creates a Homebrew formula generator.
func NewHomebrewGenerator(outputDir, appName, desc string) *HomebrewGenerator {
	return &HomebrewGenerator{
		outputDir: outputDir,
		appName:   appName,
		repoOwner: "OWNER",
		repoName:  appName,
		desc:      desc,
	}
}

// Generate produces a Homebrew formula template file.
func (g *HomebrewGenerator) Generate() error {
	formulaDir := filepath.Join(g.outputDir, "homebrew")
	if err := os.MkdirAll(formulaDir, 0o755); err != nil {
		return err
	}

	className := toFormulaClass(g.appName)
	desc := g.desc
	if desc == "" {
		desc = "CLI tool generated by Cliford"
	}

	formula := fmt.Sprintf(`# Generated by Cliford. Publish to your Homebrew tap repository.
# Copy this file to your homebrew-tap repo as Formula/%s.rb

class %s < Formula
  desc "%s"
  homepage "https://github.com/%s/%s"
  version "VERSION"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/%s/%s/releases/download/vVERSION/%s_VERSION_darwin_arm64.tar.gz"
      sha256 "SHA256_DARWIN_ARM64"
    else
      url "https://github.com/%s/%s/releases/download/vVERSION/%s_VERSION_darwin_amd64.tar.gz"
      sha256 "SHA256_DARWIN_AMD64"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/%s/%s/releases/download/vVERSION/%s_VERSION_linux_arm64.tar.gz"
      sha256 "SHA256_LINUX_ARM64"
    else
      url "https://github.com/%s/%s/releases/download/vVERSION/%s_VERSION_linux_amd64.tar.gz"
      sha256 "SHA256_LINUX_AMD64"
    end
  end

  def install
    bin.install "%s"
  end

  test do
    assert_match "version", shell_output("#{bin}/%s --version")
  end
end
`,
		g.appName, className, desc,
		g.repoOwner, g.repoName,
		g.repoOwner, g.repoName, g.appName,
		g.repoOwner, g.repoName, g.appName,
		g.repoOwner, g.repoName, g.appName,
		g.repoOwner, g.repoName, g.appName,
		g.appName, g.appName)

	return os.WriteFile(filepath.Join(formulaDir, g.appName+".rb"), []byte(formula), 0o644)
}

func toFormulaClass(name string) string {
	parts := strings.FieldsFunc(name, func(r rune) bool {
		return r == '-' || r == '_'
	})
	var result string
	for _, p := range parts {
		if len(p) > 0 {
			result += strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return result
}
