package distribution

import (
	"fmt"
	"os"
	"path/filepath"
)

// InstallScriptGenerator produces install.sh and install.ps1 for the generated app.
type InstallScriptGenerator struct {
	outputDir string
	appName   string
	repoOwner string
	repoName  string
}

// NewInstallScriptGenerator creates an install script generator.
func NewInstallScriptGenerator(outputDir, appName string) *InstallScriptGenerator {
	return &InstallScriptGenerator{
		outputDir: outputDir,
		appName:   appName,
		repoOwner: "OWNER",
		repoName:  appName,
	}
}

// Generate produces both Unix and Windows install scripts.
func (g *InstallScriptGenerator) Generate() error {
	if err := g.generateUnix(); err != nil {
		return err
	}
	return g.generateWindows()
}

func (g *InstallScriptGenerator) generateUnix() error {
	script := fmt.Sprintf(`#!/bin/sh
# Generated by Cliford. Install script for %s.
set -e

REPO="%s/%s"
APP="%s"

# Detect OS and architecture
OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
ARCH="$(uname -m)"
case "$ARCH" in
    x86_64|amd64) ARCH="amd64" ;;
    aarch64|arm64) ARCH="arm64" ;;
    *) echo "Unsupported architecture: $ARCH" && exit 1 ;;
esac

# Get latest version
if [ -z "$VERSION" ]; then
    VERSION="$(curl -fsSL "https://api.github.com/repos/${REPO}/releases/latest" | grep '"tag_name"' | sed -E 's/.*"([^"]+)".*/\1/')"
fi

if [ -z "$VERSION" ]; then
    echo "Error: could not determine latest version"
    exit 1
fi

# Download
FILENAME="${APP}_${VERSION#v}_${OS}_${ARCH}.tar.gz"
URL="https://github.com/${REPO}/releases/download/${VERSION}/${FILENAME}"
CHECKSUM_URL="https://github.com/${REPO}/releases/download/${VERSION}/checksums.txt"

TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

echo "Downloading ${APP} ${VERSION} for ${OS}/${ARCH}..."
curl -fsSL -o "${TMPDIR}/${FILENAME}" "$URL"
curl -fsSL -o "${TMPDIR}/checksums.txt" "$CHECKSUM_URL"

# Verify checksum
cd "$TMPDIR"
if command -v sha256sum >/dev/null 2>&1; then
    grep "$FILENAME" checksums.txt | sha256sum -c --quiet
elif command -v shasum >/dev/null 2>&1; then
    grep "$FILENAME" checksums.txt | shasum -a 256 -c --quiet
else
    echo "Warning: could not verify checksum (sha256sum/shasum not found)"
fi

# Extract and install
tar xzf "$FILENAME"

INSTALL_DIR="${INSTALL_DIR:-/usr/local/bin}"
if [ -w "$INSTALL_DIR" ]; then
    mv "$APP" "$INSTALL_DIR/"
else
    sudo mv "$APP" "$INSTALL_DIR/"
fi

echo "Installed ${APP} ${VERSION} to ${INSTALL_DIR}/${APP}"
`, g.appName, g.repoOwner, g.repoName, g.appName)

	path := filepath.Join(g.outputDir, "install.sh")
	if err := os.WriteFile(path, []byte(script), 0o755); err != nil {
		return err
	}
	return nil
}

func (g *InstallScriptGenerator) generateWindows() error {
	script := fmt.Sprintf(`# Generated by Cliford. Install script for %s (Windows).
$ErrorActionPreference = "Stop"

$Repo = "%s/%s"
$App = "%s"

# Detect architecture
$Arch = if ([Environment]::Is64BitOperatingSystem) { "amd64" } else { "386" }

# Get latest version
if (-not $env:VERSION) {
    $Release = Invoke-RestMethod -Uri "https://api.github.com/repos/$Repo/releases/latest"
    $Version = $Release.tag_name
} else {
    $Version = $env:VERSION
}

$VersionClean = $Version -replace '^v', ''
$Filename = "${App}_${VersionClean}_windows_${Arch}.zip"
$Url = "https://github.com/$Repo/releases/download/$Version/$Filename"
$ChecksumUrl = "https://github.com/$Repo/releases/download/$Version/checksums.txt"

$TmpDir = Join-Path $env:TEMP ([System.Guid]::NewGuid().ToString())
New-Item -ItemType Directory -Path $TmpDir | Out-Null

try {
    Write-Host "Downloading $App $Version for windows/$Arch..."
    Invoke-WebRequest -Uri $Url -OutFile (Join-Path $TmpDir $Filename)
    Invoke-WebRequest -Uri $ChecksumUrl -OutFile (Join-Path $TmpDir "checksums.txt")

    # Verify checksum
    $ExpectedHash = (Get-Content (Join-Path $TmpDir "checksums.txt") | Select-String $Filename).ToString().Split(" ")[0]
    $ActualHash = (Get-FileHash (Join-Path $TmpDir $Filename) -Algorithm SHA256).Hash.ToLower()
    if ($ExpectedHash -ne $ActualHash) {
        throw "Checksum mismatch!"
    }

    # Extract and install
    Expand-Archive -Path (Join-Path $TmpDir $Filename) -DestinationPath $TmpDir
    $InstallDir = Join-Path $env:LOCALAPPDATA $App
    New-Item -ItemType Directory -Path $InstallDir -Force | Out-Null
    Move-Item (Join-Path $TmpDir "$App.exe") (Join-Path $InstallDir "$App.exe") -Force

    # Add to PATH if not already present
    $CurrentPath = [Environment]::GetEnvironmentVariable("Path", "User")
    if ($CurrentPath -notlike "*$InstallDir*") {
        [Environment]::SetEnvironmentVariable("Path", "$CurrentPath;$InstallDir", "User")
        Write-Host "Added $InstallDir to PATH (restart terminal to take effect)"
    }

    Write-Host "Installed $App $Version to $InstallDir"
} finally {
    Remove-Item -Path $TmpDir -Recurse -Force -ErrorAction SilentlyContinue
}
`, g.appName, g.repoOwner, g.repoName, g.appName)

	return os.WriteFile(filepath.Join(g.outputDir, "install.ps1"), []byte(script), 0o644)
}
