// Code generated by Cliford. DO NOT EDIT outside custom code regions.
package cli

import (
	"encoding/json"
	"net/http"
	"os"
	"strings"
	"time"

	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"
)

var (
	outputFormat  string
	serverURL     string
	debugMode     bool
	dryRunMode    bool
	yesMode       bool
	agentMode     bool
	noInteractive bool
	tuiMode       bool
	timeout       string

	// apiClient is the shared HTTP client with auth, retry, and verbose transports.
	// Set via SetAPIClient() from main.go; falls back to a default client if nil.
	apiClient *http.Client
)

// RootCmd returns the root Cobra command for petstore.
func RootCmd(appName string, version string) *cobra.Command {
	root := &cobra.Command{
		Use:           "petstore",
		Short:         "A sample API for managing pets and users",
		Version:       version,
		SilenceUsage:  true,
		SilenceErrors: true,
	}

	pf := root.PersistentFlags()
	pf.StringVarP(&outputFormat, "output-format", "o", "pretty", "Output format: pretty, json, yaml, table")
	pf.StringVar(&serverURL, "server", "", "Override API server URL")
	pf.StringVar(&timeout, "timeout", "30s", "Request timeout")
	pf.BoolVar(&debugMode, "debug", false, "Log request/response to stderr (secrets redacted)")
	pf.BoolVar(&dryRunMode, "dry-run", false, "Display HTTP request without executing")
	pf.BoolVarP(&yesMode, "yes", "y", false, "Skip all confirmations, use defaults")
	pf.BoolVar(&agentMode, "agent", false, "Force agent mode (structured JSON, no interactive)")
	pf.BoolVar(&noInteractive, "no-interactive", false, "Disable interactive prompts")
	pf.BoolVar(&tuiMode, "tui", false, "Launch full TUI mode")

	root.AddCommand(systemCmd())
	root.AddCommand(petsCmd())
	root.AddCommand(usersCmd())
	root.AddCommand(authCmd())
	root.AddCommand(configCmd())

	root.Long = root.Short + "\n\nAvailable servers:"
	root.Long += "\n  --server https://api.petstore.example.com/v1  (Production)"
	root.Long += "\n  --server https://staging.petstore.example.com/v1  (Staging)"
	root.Long += "\n  --server http://localhost:8080/v1  (Local development)"

	return root
}

// FormatOutput renders data in the requested output format.
func FormatOutput(data any, format string) error {
	switch strings.ToLower(format) {
	case "json":
		enc := json.NewEncoder(os.Stdout)
		enc.SetIndent("", "  ")
		return enc.Encode(data)
	case "yaml":
		enc := yaml.NewEncoder(os.Stdout)
		return enc.Encode(data)
	default:
		enc := json.NewEncoder(os.Stdout)
		enc.SetIndent("", "  ")
		return enc.Encode(data)
	}
}

// SetAPIClient sets the shared HTTP client used by all generated commands.
// The client should be pre-configured with auth, retry, and verbose transport layers.
func SetAPIClient(c *http.Client) {
	apiClient = c
}

// GetAPIClient returns the shared HTTP client, falling back to a default if not configured.
func GetAPIClient() *http.Client {
	if apiClient != nil {
		return apiClient
	}
	return &http.Client{Timeout: 30 * time.Second}
}
