// Code generated by Cliford. DO NOT EDIT outside custom code regions.
package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"sort"
	"strings"
	"text/tabwriter"
	"time"

	"github.com/charmbracelet/bubbles/progress"
	"github.com/itchyny/gojq"
	"github.com/spf13/cobra"
	toon "github.com/toon-format/toon-go"
	"gopkg.in/yaml.v3"
)

var (
	outputFormat   string
	jqFilter       string
	outputFile     string
	includeHeaders bool
	serverURL      string
	debugMode      bool
	dryRunMode     bool
	yesMode        bool
	agentMode      bool
	noInteractive  bool
	tuiMode        bool
	timeout        string

	// apiClient is the shared HTTP client with auth, retry, and verbose transports.
	// Set via SetAPIClient() from main.go; falls back to a default client if nil.
	apiClient *http.Client
)

// RootCmd returns the root Cobra command for petstore.
func RootCmd(appName string, version string) *cobra.Command {
	root := &cobra.Command{
		Use:           "petstore",
		Short:         "A sample API for managing pets and users",
		Version:       version,
		SilenceUsage:  true,
		SilenceErrors: true,
	}

	pf := root.PersistentFlags()
	pf.StringVarP(&outputFormat, "output-format", "o", "pretty", "Output format: pretty, json, yaml, table, toon")
	pf.StringVar(&jqFilter, "jq", "", "Filter JSON output with a jq expression (gojq syntax)")
	pf.StringVar(&outputFile, "output-file", "", "Write response body to a file instead of stdout")
	pf.BoolVar(&includeHeaders, "include-headers", false, "Print response headers alongside the body")
	pf.StringVar(&serverURL, "server", "", "Override API server URL")
	pf.StringVar(&timeout, "timeout", "30s", "Request timeout")
	pf.BoolVarP(&debugMode, "verbose", "v", false, "Log request/response to stderr (secrets redacted)")
	_ = pf.Bool("debug", false, "Alias for --verbose")
	_ = root.RegisterFlagCompletionFunc("debug", cobra.NoFileCompletions)
	pf.BoolVar(&dryRunMode, "dry-run", false, "Display HTTP request without executing")
	pf.BoolVarP(&yesMode, "yes", "y", false, "Skip all confirmations, use defaults")
	pf.BoolVar(&agentMode, "agent", false, "Force agent mode (structured JSON, no interactive)")
	pf.BoolVar(&noInteractive, "no-interactive", false, "Disable interactive prompts")
	pf.BoolVar(&tuiMode, "tui", false, "Launch full TUI mode")

	root.AddCommand(petsCmd())
	root.AddCommand(systemCmd())
	root.AddCommand(usersCmd())
	root.AddCommand(authCmd())
	root.AddCommand(configCmd())
	root.AddCommand(GenerateDocsCmd())

	root.Long = root.Short + "\n\nAvailable servers:"
	root.Long += "\n  --server https://api.petstore.example.com/v1  (Production)"
	root.Long += "\n  --server https://staging.petstore.example.com/v1  (Staging)"
	root.Long += "\n  --server http://localhost:8080/v1  (Local development)"

	return root
}

// FormatOutput renders data in the requested output format.
func FormatOutput(data any, format string) error {
	switch strings.ToLower(format) {
	case "json":
		enc := json.NewEncoder(os.Stdout)
		enc.SetIndent("", "  ")
		return enc.Encode(data)
	case "yaml":
		enc := yaml.NewEncoder(os.Stdout)
		return enc.Encode(data)
	case "table":
		return formatTable(data)
	case "toon":
		s, err := toon.MarshalString(data)
		if err != nil {
			// Fall back to JSON on encoding failure
			enc := json.NewEncoder(os.Stdout)
			enc.SetIndent("", "  ")
			return enc.Encode(data)
		}
		fmt.Println(s)
		return nil
	default:
		enc := json.NewEncoder(os.Stdout)
		enc.SetIndent("", "  ")
		return enc.Encode(data)
	}
}

// formatTable renders an array of objects as a text table.
func formatTable(data any) error {
	items, ok := data.([]any)
	if !ok {
		// Not an array — fall back to JSON
		enc := json.NewEncoder(os.Stdout)
		enc.SetIndent("", "  ")
		return enc.Encode(data)
	}
	if len(items) == 0 {
		fmt.Println("No results.")
		return nil
	}

	// Collect column headers from the first row
	firstRow, ok := items[0].(map[string]any)
	if !ok {
		enc := json.NewEncoder(os.Stdout)
		enc.SetIndent("", "  ")
		return enc.Encode(data)
	}
	var headers []string
	for k := range firstRow {
		headers = append(headers, k)
	}
	sort.Strings(headers)

	w := tabwriter.NewWriter(os.Stdout, 0, 0, 2, ' ', 0)
	// Print headers
	fmt.Fprintln(w, strings.Join(headers, "\t"))
	// Print separator
	seps := make([]string, len(headers))
	for i, h := range headers {
		seps[i] = strings.Repeat("-", len(h))
	}
	fmt.Fprintln(w, strings.Join(seps, "\t"))
	// Print rows
	for _, item := range items {
		row, ok := item.(map[string]any)
		if !ok {
			continue
		}
		vals := make([]string, len(headers))
		for i, h := range headers {
			vals[i] = fmt.Sprintf("%v", row[h])
		}
		fmt.Fprintln(w, strings.Join(vals, "\t"))
	}
	return w.Flush()
}

// applyJQ runs a jq expression against parsed JSON data.
// Returns a single value when the expression produces one result,
// a slice when it produces multiple, and nil when it produces none.
func applyJQ(input any, expr string) (any, error) {
	query, err := gojq.Parse(expr)
	if err != nil {
		return nil, fmt.Errorf("parse jq expression %q: %w", expr, err)
	}
	iter := query.Run(input)
	var results []any
	for {
		v, ok := iter.Next()
		if !ok {
			break
		}
		if jqErr, ok := v.(error); ok {
			return nil, jqErr
		}
		results = append(results, v)
	}
	switch len(results) {
	case 0:
		return nil, nil
	case 1:
		return results[0], nil
	default:
		return results, nil
	}
}

// isTTYStderr reports whether stderr is connected to a terminal.
func isTTYStderr() bool {
	fi, _ := os.Stderr.Stat()
	return fi != nil && (fi.Mode()&os.ModeCharDevice) != 0
}

// formatBytes formats a byte count as a human-readable string.
func formatBytes(n int64) string {
	const (
		KB = 1024
		MB = 1024 * KB
		GB = 1024 * MB
	)
	switch {
	case n >= GB:
		return fmt.Sprintf("%.1f GB", float64(n)/GB)
	case n >= MB:
		return fmt.Sprintf("%.1f MB", float64(n)/MB)
	case n >= KB:
		return fmt.Sprintf("%.1f KB", float64(n)/KB)
	default:
		return fmt.Sprintf("%d B", n)
	}
}

// progressWriter wraps an io.Writer and calls onWrite after each write with the total bytes written.
type progressWriter struct {
	w       io.Writer
	written int64
	onWrite func(int64)
}

func (pw *progressWriter) Write(p []byte) (int, error) {
	n, err := pw.w.Write(p)
	pw.written += int64(n)
	pw.onWrite(pw.written)
	return n, err
}

// writeFileWithProgress streams body to path and shows download progress on stderr.
// Progress display adapts to the execution context:
//   - Interactive TTY: bubbles/progress bar (percentage or byte counter)
//   - Headless/--no-interactive: silent write + summary to stderr
//   - Agent (--agent or AI env): silent write + JSON {"path","bytes","contentType"} to stdout
func writeFileWithProgress(body io.Reader, contentLength int64, contentType, path string) error {
	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("create %s: %w", path, err)
	}
	defer f.Close()

	isInteractive := !noInteractive && !agentMode && isTTYStderr()

	if !isInteractive {
		n, err := io.Copy(f, body)
		if err != nil {
			return fmt.Errorf("write %s: %w", path, err)
		}
		if agentMode {
			fmt.Printf("{\"path\":%q,\"bytes\":%d,\"contentType\":%q}\n", path, n, contentType)
		} else {
			fmt.Fprintf(os.Stderr, "Wrote %s (%s)\n", path, formatBytes(n))
		}
		return nil
	}

	// Interactive TTY: use bubbles/progress for visual feedback
	bar := progress.New(progress.WithDefaultGradient())
	const clearWidth = 80
	pw := &progressWriter{
		w: f,
		onWrite: func(written int64) {
			if contentLength > 0 {
				pct := float64(written) / float64(contentLength)
				fmt.Fprintf(os.Stderr, "\r%s", bar.ViewAs(pct))
			} else {
				fmt.Fprintf(os.Stderr, "\r%s written", formatBytes(written))
			}
		},
	}
	n, err := io.Copy(pw, body)
	fmt.Fprintf(os.Stderr, "\r%s\r", strings.Repeat(" ", clearWidth))
	if err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	fmt.Fprintf(os.Stderr, "Wrote %s (%s)\n", path, formatBytes(n))
	return nil
}

// SetAPIClient sets the shared HTTP client used by all generated commands.
// The client should be pre-configured with auth, retry, and verbose transport layers.
func SetAPIClient(c *http.Client) {
	apiClient = c
}

// GetAPIClient returns the shared HTTP client, falling back to a default if not configured.
func GetAPIClient() *http.Client {
	if apiClient != nil {
		return apiClient
	}
	return &http.Client{Timeout: 30 * time.Second}
}

// SetDefaultServerURL sets the server URL from config/env.
// This is overridden by the --server CLI flag if provided.
func SetDefaultServerURL(url string) {
	if serverURL == "" {
		serverURL = url
	}
}

// VerboseFlag returns a pointer to the verbose/debug mode flag.
// Pass this to client.Options.VerboseFlag to enable request/response logging.
func VerboseFlag() *bool {
	return &debugMode
}

// promptValue prompts the user for a value on stdin.
// Returns empty string if stdin is not a terminal.
func promptValue(label string) string {
	fi, _ := os.Stdin.Stat()
	if fi != nil && (fi.Mode()&os.ModeCharDevice) == 0 {
		return "" // not a TTY — skip prompt
	}
	fmt.Fprint(os.Stderr, label)
	var line string
	fmt.Scanln(&line)
	return strings.TrimSpace(line)
}

// withSpinner is a no-op when spinner is disabled in cliford.yaml.
func withSpinner[T any](_ string, fn func() (T, error)) (T, error) {
	return fn()
}
