// Code generated by Cliford. DO NOT EDIT outside custom code regions.
package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

// aliasEntry holds a single alias name and its expansion for structured output.
type aliasEntry struct {
	Name      string `json:"name" yaml:"name"`
	Expansion string `json:"expansion" yaml:"expansion"`
}

// ResolveAliases checks os.Args[1] against configured aliases and expands it.
// If args[1] matches a configured alias, its expansion tokens replace it and
// any extra user args are appended after. Returns args unchanged when no alias
// matches or when args has fewer than 2 elements.
// Call this with os.Args before rootCmd.Execute().
func ResolveAliases(args []string) []string {
	if len(args) < 2 {
		return args
	}
	aliases := viper.GetStringMapString("aliases")
	expansion, ok := aliases[args[1]]
	if !ok {
		return args
	}
	expanded := strings.Fields(expansion)
	if len(expanded) == 0 {
		return args
	}
	result := make([]string, 0, 1+len(expanded)+len(args[2:]))
	result = append(result, args[0])
	result = append(result, expanded...)
	result = append(result, args[2:]...)
	return result
}

// aliasCmd returns the alias management command.
func aliasCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "alias",
		Short: "Manage command aliases",
		Long:  "Create, list, and delete command aliases stored in your configuration file.\n\nAliases let you define short names for longer commands with default flags.\nThey are stored under the 'aliases' key in ~/.config/<app>/config.yaml.",
	}
	cmd.AddCommand(aliasSetCmd())
	cmd.AddCommand(aliasDeleteCmd())
	cmd.AddCommand(aliasListCmd())
	return cmd
}

// aliasSetCmd defines or updates an alias.
func aliasSetCmd() *cobra.Command {
	return &cobra.Command{
		Use:     "set <name> <expansion>",
		Short:   "Define or update an alias",
		Args:    cobra.ExactArgs(2),
		Example: "  alias set lp \"pets list --limit 10\"\n  alias set new-cat \"pets create --name Whiskers\"",
		RunE: func(cmd *cobra.Command, args []string) error {
			name, expansion := args[0], args[1]
			aliases := viper.GetStringMapString("aliases")
			if aliases == nil {
				aliases = map[string]string{}
			}
			aliases[name] = expansion
			viper.Set("aliases", aliases)
			configDir, err := os.UserConfigDir()
			if err != nil {
				return fmt.Errorf("find config directory: %w", err)
			}
			configPath := filepath.Join(configDir, "petstore", "config.yaml")
			if err := viper.WriteConfigAs(configPath); err != nil {
				return fmt.Errorf("write config: %w", err)
			}
			fmt.Fprintf(cmd.OutOrStdout(), "Alias %q = %q added.\n", name, expansion)
			return nil
		},
	}
}

// aliasDeleteCmd removes an alias.
func aliasDeleteCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "delete <name>",
		Short: "Remove an alias",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			name := args[0]
			aliases := viper.GetStringMapString("aliases")
			if _, ok := aliases[name]; !ok {
				return fmt.Errorf("alias %q not found", name)
			}
			delete(aliases, name)
			viper.Set("aliases", aliases)
			configDir, err := os.UserConfigDir()
			if err != nil {
				return fmt.Errorf("find config directory: %w", err)
			}
			configPath := filepath.Join(configDir, "petstore", "config.yaml")
			if err := viper.WriteConfigAs(configPath); err != nil {
				return fmt.Errorf("write config: %w", err)
			}
			fmt.Fprintf(cmd.OutOrStdout(), "Alias %q removed.\n", name)
			return nil
		},
	}
}

// aliasListCmd lists all configured aliases using the standard FormatOutput.
func aliasListCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "list",
		Short: "List all aliases",
		RunE: func(cmd *cobra.Command, args []string) error {
			raw := viper.GetStringMapString("aliases")
			if len(raw) == 0 {
				fmt.Fprintln(cmd.OutOrStdout(), "No aliases configured.")
				return nil
			}
			names := make([]string, 0, len(raw))
			for name := range raw {
				names = append(names, name)
			}
			sort.Strings(names)
			entries := make([]aliasEntry, 0, len(names))
			for _, name := range names {
				entries = append(entries, aliasEntry{Name: name, Expansion: raw[name]})
			}
			return FormatOutput(entries, outputFormat)
		},
	}
}
