// Code generated by Cliford. DO NOT EDIT outside custom code regions.
package cli

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

func petsCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "pets",
		Short: "pets operations",
	}

	cmd.AddCommand(petsListCmd())
	cmd.AddCommand(petsCreateCmd())
	cmd.AddCommand(petsDeleteCmd())
	cmd.AddCommand(petsGetCmd())

	return cmd
}

func petsListCmd() *cobra.Command {
	var flagLimit int
	var flagStatus string
	var flagSpecies string
	var flagXRequestID string

	cmd := &cobra.Command{
		Use:     "list",
		Short:   "List all pets",
		Long:    "Returns a list of pets with optional filtering",
		Example: "  pets list --limit 10 --species cat",
		RunE: func(cmd *cobra.Command, args []string) error {

			baseURL := "https://api.petstore.example.com/v1"
			if serverURL != "" {
				baseURL = serverURL
			} else {
			}

			reqPath := "/pets"

			reqURL, err := url.Parse(baseURL + reqPath)
			if err != nil {
				return fmt.Errorf("invalid URL: %w", err)
			}

			q := reqURL.Query()
			if cmd.Flags().Changed("limit") {
				q.Set("limit", fmt.Sprintf("%d", flagLimit))
			}
			if flagStatus != "" {
				q.Set("status", flagStatus)
			}
			if flagSpecies != "" {
				q.Set("species", flagSpecies)
			}
			reqURL.RawQuery = q.Encode()

			var reqBody io.Reader

			req, err := http.NewRequestWithContext(cmd.Context(), "GET", reqURL.String(), reqBody)
			if err != nil {
				return fmt.Errorf("create request: %w", err)
			}
			if flagXRequestID != "" {
				req.Header.Set("X-Request-ID", flagXRequestID)
			}

			if dryRunMode {
				fmt.Fprintf(os.Stdout, "%s %s\n", req.Method, req.URL.String())
				for k, v := range req.Header {
					fmt.Fprintf(os.Stdout, "%s: %s\n", k, strings.Join(v, ", "))
				}
				return nil
			}

			resp, err := withSpinner("Loading...", func() (*http.Response, error) {
				return GetAPIClient().Do(req)
			})
			if err != nil {
				return fmt.Errorf("request failed: %w", err)
			}
			defer resp.Body.Close()

			if outputFile != "" {
				if resp.StatusCode >= 400 {
					errBody, _ := io.ReadAll(resp.Body)
					return fmt.Errorf("HTTP %d: %s", resp.StatusCode, string(errBody))
				}
				if includeHeaders {
					for k, vs := range resp.Header {
						fmt.Fprintf(os.Stderr, "%s: %s\n", k, strings.Join(vs, ", "))
					}
					fmt.Fprintln(os.Stderr)
				}
				return writeFileWithProgress(resp.Body, resp.ContentLength, resp.Header.Get("Content-Type"), outputFile)
			}

			respBody, err := io.ReadAll(resp.Body)
			if err != nil {
				return fmt.Errorf("read response: %w", err)
			}

			if resp.StatusCode >= 400 {
				return fmt.Errorf("HTTP %d: %s", resp.StatusCode, string(respBody))
			}

			if resp.StatusCode == 204 || len(respBody) == 0 {
				fmt.Println("OK")
				return nil
			}

			var data any
			if err := json.Unmarshal(respBody, &data); err != nil {
				if includeHeaders {
					for k, vs := range resp.Header {
						fmt.Fprintf(os.Stdout, "%s: %s\n", k, strings.Join(vs, ", "))
					}
					fmt.Println()
				}
				fmt.Println(string(respBody))
				return nil
			}
			if jqFilter != "" {
				filtered, jqErr := applyJQ(data, jqFilter)
				if jqErr != nil {
					return fmt.Errorf("--jq: %w", jqErr)
				}
				data = filtered
			}
			if includeHeaders {
				hdrs := make(map[string]any)
				for k, vs := range resp.Header {
					if len(vs) == 1 {
						hdrs[k] = vs[0]
					} else {
						hdrs[k] = vs
					}
				}
				data = map[string]any{"headers": hdrs, "body": data}
			}
			return FormatOutput(data, outputFormat)
		},
	}

	cmd.Flags().IntVar(&flagLimit, "limit", 20, "Maximum number of pets to return (example: 10)")
	cmd.Flags().StringVar(&flagStatus, "status", "", "Filter by adoption status (available, pending, adopted)")
	cmd.Flags().StringVar(&flagSpecies, "species", "", "Filter by species (example: cat)")
	cmd.Flags().StringVar(&flagXRequestID, "x--request--i-d", "", "Optional request correlation ID")

	return cmd
}

func petsCreateCmd() *cobra.Command {
	var bodyPropName string
	var bodyPropSpecies string
	var bodyPropTags []string
	var bodyJSON string

	cmd := &cobra.Command{
		Use:     "create",
		Short:   "Create a new pet",
		Long:    "Add a new pet to the store",
		Example: "  pets create --body '{\"name\":\"Whiskers\",\"species\":\"cat\"}'",
		RunE: func(cmd *cobra.Command, args []string) error {

			baseURL := "https://api.petstore.example.com/v1"
			if serverURL != "" {
				baseURL = serverURL
			} else {
			}

			reqPath := "/pets"

			reqURL, err := url.Parse(baseURL + reqPath)
			if err != nil {
				return fmt.Errorf("invalid URL: %w", err)
			}

			var reqBody io.Reader
			{
				bodyFields := make(map[string]any)
				// stdin base layer
				{
					stat, _ := os.Stdin.Stat()
					if stat != nil && (stat.Mode()&os.ModeCharDevice) == 0 {
						if data, err := io.ReadAll(os.Stdin); err == nil && len(data) > 0 {
							_ = json.Unmarshal(data, &bodyFields)
						}
					}
				}
				// --body JSON override
				if bodyJSON != "" {
					var override map[string]any
					if err := json.Unmarshal([]byte(bodyJSON), &override); err != nil {
						return fmt.Errorf("invalid --body JSON: %w", err)
					}
					for k, v := range override {
						bodyFields[k] = v
					}
				}
				// individual flags (highest priority)
				if cmd.Flags().Changed("name") {
					bodyFields["name"] = bodyPropName
				}
				if cmd.Flags().Changed("species") {
					validSpecies := []string{"dog", "cat", "bird", "fish", "other"}
					found := false
					for _, v := range validSpecies {
						if v == bodyPropSpecies {
							found = true
							break
						}
					}
					if !found {
						return fmt.Errorf("species"+": must be one of: %s", strings.Join(validSpecies, ", "))
					}
					bodyFields["species"] = bodyPropSpecies
				}
				if cmd.Flags().Changed("tags") {
					bodyFields["tags"] = bodyPropTags
				}
				// validate required fields
				if _, ok := bodyFields["name"]; !ok {
					return fmt.Errorf("required field --name is missing; use --name or --body")
				}
				if _, ok := bodyFields["species"]; !ok {
					return fmt.Errorf("required field --species is missing; use --species or --body")
				}
				if len(bodyFields) > 0 {
					b, err := json.Marshal(bodyFields)
					if err != nil {
						return fmt.Errorf("marshal body: %w", err)
					}
					reqBody = bytes.NewReader(b)
				}
			}

			req, err := http.NewRequestWithContext(cmd.Context(), "POST", reqURL.String(), reqBody)
			if err != nil {
				return fmt.Errorf("create request: %w", err)
			}
			if reqBody != nil {
				req.Header.Set("Content-Type", "application/json")
			}

			if dryRunMode {
				fmt.Fprintf(os.Stdout, "%s %s\n", req.Method, req.URL.String())
				for k, v := range req.Header {
					fmt.Fprintf(os.Stdout, "%s: %s\n", k, strings.Join(v, ", "))
				}
				if req.Body != nil {
					fmt.Fprintln(os.Stdout)
					bodyBytes, _ := io.ReadAll(req.Body)
					req.Body.Close()
					os.Stdout.Write(bodyBytes)
					fmt.Fprintln(os.Stdout)
				}
				return nil
			}

			resp, err := withSpinner("Loading...", func() (*http.Response, error) {
				return GetAPIClient().Do(req)
			})
			if err != nil {
				return fmt.Errorf("request failed: %w", err)
			}
			defer resp.Body.Close()

			if outputFile != "" {
				if resp.StatusCode >= 400 {
					errBody, _ := io.ReadAll(resp.Body)
					return fmt.Errorf("HTTP %d: %s", resp.StatusCode, string(errBody))
				}
				if includeHeaders {
					for k, vs := range resp.Header {
						fmt.Fprintf(os.Stderr, "%s: %s\n", k, strings.Join(vs, ", "))
					}
					fmt.Fprintln(os.Stderr)
				}
				return writeFileWithProgress(resp.Body, resp.ContentLength, resp.Header.Get("Content-Type"), outputFile)
			}

			respBody, err := io.ReadAll(resp.Body)
			if err != nil {
				return fmt.Errorf("read response: %w", err)
			}

			if resp.StatusCode >= 400 {
				return fmt.Errorf("HTTP %d: %s", resp.StatusCode, string(respBody))
			}

			if resp.StatusCode == 204 || len(respBody) == 0 {
				fmt.Println("OK")
				return nil
			}

			var data any
			if err := json.Unmarshal(respBody, &data); err != nil {
				if includeHeaders {
					for k, vs := range resp.Header {
						fmt.Fprintf(os.Stdout, "%s: %s\n", k, strings.Join(vs, ", "))
					}
					fmt.Println()
				}
				fmt.Println(string(respBody))
				return nil
			}
			if jqFilter != "" {
				filtered, jqErr := applyJQ(data, jqFilter)
				if jqErr != nil {
					return fmt.Errorf("--jq: %w", jqErr)
				}
				data = filtered
			}
			if includeHeaders {
				hdrs := make(map[string]any)
				for k, vs := range resp.Header {
					if len(vs) == 1 {
						hdrs[k] = vs[0]
					} else {
						hdrs[k] = vs
					}
				}
				data = map[string]any{"headers": hdrs, "body": data}
			}
			return FormatOutput(data, outputFormat)
		},
	}

	cmd.Flags().StringVar(&bodyPropName, "name", "", "Name of the pet")
	cmd.Flags().StringVar(&bodyPropSpecies, "species", "", "One of: dog, cat, bird, fish, other")
	cmd.Flags().StringSliceVar(&bodyPropTags, "tags", nil, "")
	cmd.Flags().StringVar(&bodyJSON, "body", "", "Request body as JSON (overrides individual flags)")

	return cmd
}

func petsDeleteCmd() *cobra.Command {
	var flagPetId int64

	cmd := &cobra.Command{
		Use:   "delete",
		Short: "Delete a pet",
		RunE: func(cmd *cobra.Command, args []string) error {
			// Interactive prompts for missing required args
			if !noInteractive && !agentMode {
			}

			// Confirm destructive operation
			if !yesMode {
				answer := promptValue("Are you sure you want to delete? [y/N]: ")
				if answer != "y" && answer != "Y" && answer != "yes" {
					fmt.Fprintln(os.Stderr, "Aborted.")
					return nil
				}
			}

			baseURL := "https://api.petstore.example.com/v1"
			if serverURL != "" {
				baseURL = serverURL
			} else {
			}

			reqPath := "/pets/{petId}"
			reqPath = strings.Replace(reqPath, "{petId}", fmt.Sprintf("%v", flagPetId), 1)

			reqURL, err := url.Parse(baseURL + reqPath)
			if err != nil {
				return fmt.Errorf("invalid URL: %w", err)
			}

			var reqBody io.Reader

			req, err := http.NewRequestWithContext(cmd.Context(), "DELETE", reqURL.String(), reqBody)
			if err != nil {
				return fmt.Errorf("create request: %w", err)
			}

			if dryRunMode {
				fmt.Fprintf(os.Stdout, "%s %s\n", req.Method, req.URL.String())
				for k, v := range req.Header {
					fmt.Fprintf(os.Stdout, "%s: %s\n", k, strings.Join(v, ", "))
				}
				return nil
			}

			resp, err := withSpinner("Loading...", func() (*http.Response, error) {
				return GetAPIClient().Do(req)
			})
			if err != nil {
				return fmt.Errorf("request failed: %w", err)
			}
			defer resp.Body.Close()

			if outputFile != "" {
				if resp.StatusCode >= 400 {
					errBody, _ := io.ReadAll(resp.Body)
					return fmt.Errorf("HTTP %d: %s", resp.StatusCode, string(errBody))
				}
				if includeHeaders {
					for k, vs := range resp.Header {
						fmt.Fprintf(os.Stderr, "%s: %s\n", k, strings.Join(vs, ", "))
					}
					fmt.Fprintln(os.Stderr)
				}
				return writeFileWithProgress(resp.Body, resp.ContentLength, resp.Header.Get("Content-Type"), outputFile)
			}

			respBody, err := io.ReadAll(resp.Body)
			if err != nil {
				return fmt.Errorf("read response: %w", err)
			}

			if resp.StatusCode >= 400 {
				return fmt.Errorf("HTTP %d: %s", resp.StatusCode, string(respBody))
			}

			if resp.StatusCode == 204 || len(respBody) == 0 {
				fmt.Println("OK")
				return nil
			}

			var data any
			if err := json.Unmarshal(respBody, &data); err != nil {
				if includeHeaders {
					for k, vs := range resp.Header {
						fmt.Fprintf(os.Stdout, "%s: %s\n", k, strings.Join(vs, ", "))
					}
					fmt.Println()
				}
				fmt.Println(string(respBody))
				return nil
			}
			if jqFilter != "" {
				filtered, jqErr := applyJQ(data, jqFilter)
				if jqErr != nil {
					return fmt.Errorf("--jq: %w", jqErr)
				}
				data = filtered
			}
			if includeHeaders {
				hdrs := make(map[string]any)
				for k, vs := range resp.Header {
					if len(vs) == 1 {
						hdrs[k] = vs[0]
					} else {
						hdrs[k] = vs
					}
				}
				data = map[string]any{"headers": hdrs, "body": data}
			}
			return FormatOutput(data, outputFormat)
		},
	}

	cmd.Flags().Int64Var(&flagPetId, "pet-id", 0, "")
	_ = cmd.MarkFlagRequired("pet-id")

	return cmd
}

func petsGetCmd() *cobra.Command {
	var flagPetId int64

	cmd := &cobra.Command{
		Use:   "get",
		Short: "Get a pet by ID",
		RunE: func(cmd *cobra.Command, args []string) error {
			// Interactive prompts for missing required args
			if !noInteractive && !agentMode {
			}

			baseURL := "https://api.petstore.example.com/v1"
			if serverURL != "" {
				baseURL = serverURL
			} else {
			}

			reqPath := "/pets/{petId}"
			reqPath = strings.Replace(reqPath, "{petId}", fmt.Sprintf("%v", flagPetId), 1)

			reqURL, err := url.Parse(baseURL + reqPath)
			if err != nil {
				return fmt.Errorf("invalid URL: %w", err)
			}

			var reqBody io.Reader

			req, err := http.NewRequestWithContext(cmd.Context(), "GET", reqURL.String(), reqBody)
			if err != nil {
				return fmt.Errorf("create request: %w", err)
			}

			if dryRunMode {
				fmt.Fprintf(os.Stdout, "%s %s\n", req.Method, req.URL.String())
				for k, v := range req.Header {
					fmt.Fprintf(os.Stdout, "%s: %s\n", k, strings.Join(v, ", "))
				}
				return nil
			}

			resp, err := withSpinner("Loading...", func() (*http.Response, error) {
				return GetAPIClient().Do(req)
			})
			if err != nil {
				return fmt.Errorf("request failed: %w", err)
			}
			defer resp.Body.Close()

			if outputFile != "" {
				if resp.StatusCode >= 400 {
					errBody, _ := io.ReadAll(resp.Body)
					return fmt.Errorf("HTTP %d: %s", resp.StatusCode, string(errBody))
				}
				if includeHeaders {
					for k, vs := range resp.Header {
						fmt.Fprintf(os.Stderr, "%s: %s\n", k, strings.Join(vs, ", "))
					}
					fmt.Fprintln(os.Stderr)
				}
				return writeFileWithProgress(resp.Body, resp.ContentLength, resp.Header.Get("Content-Type"), outputFile)
			}

			respBody, err := io.ReadAll(resp.Body)
			if err != nil {
				return fmt.Errorf("read response: %w", err)
			}

			if resp.StatusCode >= 400 {
				return fmt.Errorf("HTTP %d: %s", resp.StatusCode, string(respBody))
			}

			if resp.StatusCode == 204 || len(respBody) == 0 {
				fmt.Println("OK")
				return nil
			}

			var data any
			if err := json.Unmarshal(respBody, &data); err != nil {
				if includeHeaders {
					for k, vs := range resp.Header {
						fmt.Fprintf(os.Stdout, "%s: %s\n", k, strings.Join(vs, ", "))
					}
					fmt.Println()
				}
				fmt.Println(string(respBody))
				return nil
			}
			if jqFilter != "" {
				filtered, jqErr := applyJQ(data, jqFilter)
				if jqErr != nil {
					return fmt.Errorf("--jq: %w", jqErr)
				}
				data = filtered
			}
			if includeHeaders {
				hdrs := make(map[string]any)
				for k, vs := range resp.Header {
					if len(vs) == 1 {
						hdrs[k] = vs[0]
					} else {
						hdrs[k] = vs
					}
				}
				data = map[string]any{"headers": hdrs, "body": data}
			}
			return FormatOutput(data, outputFormat)
		},
	}

	cmd.Flags().Int64Var(&flagPetId, "pet-id", 0, "ID of the pet to retrieve")
	_ = cmd.MarkFlagRequired("pet-id")

	return cmd
}
