package hybrid

import (
	"os"
	"path/filepath"
	"strings"
)

// AdapterGenerator produces the mode detection and adapter wiring for the generated app.
type AdapterGenerator struct {
	outputDir string
	envPrefix string
}

// NewAdapterGenerator creates an adapter generator.
func NewAdapterGenerator(outputDir, envPrefix string) *AdapterGenerator {
	return &AdapterGenerator{outputDir: outputDir, envPrefix: envPrefix}
}

// Generate produces the mode detection and adapter files.
func (g *AdapterGenerator) Generate() error {
	hybridDir := filepath.Join(g.outputDir, "internal", "hybrid")
	if err := os.MkdirAll(hybridDir, 0o755); err != nil {
		return err
	}

	if err := g.generateModeDetector(hybridDir); err != nil {
		return err
	}

	return nil
}

func (g *AdapterGenerator) generateModeDetector(hybridDir string) error {
	var sb strings.Builder
	w := func(s string) { sb.WriteString(s + "\n") }

	w("// Code generated by Cliford. DO NOT EDIT outside custom code regions.")
	w("package hybrid")
	w("")
	w("import (")
	w(`	"os"`)
	w(`	"strings"`)
	w(")")
	w("")
	w("// Mode represents the execution mode.")
	w("type Mode string")
	w("")
	w("const (")
	w(`	ModeCLI      Mode = "cli"`)
	w(`	ModeTUI      Mode = "tui"`)
	w(`	ModeHybrid   Mode = "hybrid"`)
	w(`	ModeHeadless Mode = "headless"`)
	w(")")
	w("")
	w("// agentEnvVars indicate an AI agent environment.")
	w("var agentEnvVars = []string{")
	w(`	"CLAUDE_CODE", "CURSOR_SESSION_ID", "CODEX_SESSION",`)
	w(`	"AIDER_MODEL", "CLINE_TASK", "WINDSURF_SESSION",`)
	w(`	"COPILOT_AGENT", "AMAZON_Q_SESSION", "GEMINI_CODE_ASSIST", "CODY_SESSION",`)
	w("}")
	w("")
	w("// DetectMode resolves the execution mode using the precedence chain:")
	w("//  1. Explicit flags (--tui, --no-interactive, -y, --agent)")
	w("//  2. Environment variable")
	w("//  3. Auto-detection (agent env, TTY)")
	w("func DetectMode(tuiFlag, noInteractive, yesFlag, agentFlag bool) Mode {")
	w("	if agentFlag {")
	w("		return ModeHeadless")
	w("	}")
	w("	if tuiFlag {")
	w("		return ModeTUI")
	w("	}")
	w("	if noInteractive || yesFlag {")
	w("		return ModeHeadless")
	w("	}")
	w("")
	w(strings.ReplaceAll(`	envMode := os.Getenv("PREFIX_MODE")`, "PREFIX", g.envPrefix))
	w("	switch strings.ToLower(envMode) {")
	w(`	case "tui":`)
	w("		return ModeTUI")
	w(`	case "cli":`)
	w("		return ModeCLI")
	w(`	case "headless":`)
	w("		return ModeHeadless")
	w("	}")
	w("")
	w("	if isAgentEnv() {")
	w("		return ModeHeadless")
	w("	}")
	w("	if !isTTY() {")
	w("		return ModeHeadless")
	w("	}")
	w("")
	w("	return ModeHybrid")
	w("}")
	w("")
	w("func isAgentEnv() bool {")
	w("	for _, v := range agentEnvVars {")
	w(`		if os.Getenv(v) != "" {`)
	w("			return true")
	w("		}")
	w("	}")
	w("	return false")
	w("}")
	w("")
	w("func isTTY() bool {")
	w("	fi, err := os.Stdin.Stat()")
	w("	if err != nil {")
	w("		return false")
	w("	}")
	w("	return fi.Mode()&os.ModeCharDevice != 0")
	w("}")

	return os.WriteFile(filepath.Join(hybridDir, "mode.go"), []byte(sb.String()), 0o644)
}
