package hybrid

import (
	"os"
	"path/filepath"
	"strings"
)

// PromptGenerator produces inline Bubbletea prompt utilities for the generated app.
type PromptGenerator struct {
	outputDir string
	pkgPath   string
}

// NewPromptGenerator creates a prompt generator.
func NewPromptGenerator(outputDir, pkgPath string) *PromptGenerator {
	return &PromptGenerator{outputDir: outputDir, pkgPath: pkgPath}
}

// Generate produces the prompt utility file for the generated app.
func (g *PromptGenerator) Generate() error {
	hybridDir := filepath.Join(g.outputDir, "internal", "hybrid")
	if err := os.MkdirAll(hybridDir, 0o755); err != nil {
		return err
	}

	var sb strings.Builder
	w := func(s string) { sb.WriteString(s + "\n") }

	w("// Code generated by Cliford. DO NOT EDIT outside custom code regions.")
	w("package hybrid")
	w("")
	w("import (")
	w(`	"fmt"`)
	w(`	"os"`)
	w("")
	w(`	"github.com/charmbracelet/bubbles/textinput"`)
	w(`	tea "github.com/charmbracelet/bubbletea"`)
	w(")")
	w("")
	w("// PromptText runs an inline Bubbletea text input and returns the entered value.")
	w("// Used in hybrid mode when a required parameter is missing.")
	w("func PromptText(label, placeholder string) (string, error) {")
	w("	m := promptModel{")
	w("		label: label,")
	w("	}")
	w("	m.input = textinput.New()")
	w("	m.input.Placeholder = placeholder")
	w("	m.input.Focus()")
	w("")
	w("	p := tea.NewProgram(m)")
	w("	result, err := p.Run()")
	w("	if err != nil {")
	w(`		return "", err`)
	w("	}")
	w("")
	w("	final := result.(promptModel)")
	w("	if final.cancelled {")
	w(`		return "", fmt.Errorf("cancelled")`)
	w("	}")
	w("	return final.input.Value(), nil")
	w("}")
	w("")
	w("// PromptConfirm runs an inline confirmation prompt. Returns true if confirmed.")
	w("func PromptConfirm(message string) (bool, error) {")
	w("	fmt.Fprintf(os.Stderr, \"%s [y/N] \", message)")
	w("	var response string")
	w("	fmt.Scanln(&response)")
	w(`	return response == "y" || response == "Y" || response == "yes", nil`)
	w("}")
	w("")
	w("type promptModel struct {")
	w("	label     string")
	w("	input     textinput.Model")
	w("	done      bool")
	w("	cancelled bool")
	w("}")
	w("")
	w("func (m promptModel) Init() tea.Cmd { return textinput.Blink }")
	w("")
	w("func (m promptModel) Update(msg tea.Msg) (tea.Model, tea.Cmd) {")
	w("	switch msg := msg.(type) {")
	w("	case tea.KeyMsg:")
	w("		switch msg.String() {")
	w(`		case "enter":`)
	w("			m.done = true")
	w("			return m, tea.Quit")
	w(`		case "ctrl+c", "esc":`)
	w("			m.cancelled = true")
	w("			return m, tea.Quit")
	w("		}")
	w("	}")
	w("	var cmd tea.Cmd")
	w("	m.input, cmd = m.input.Update(msg)")
	w("	return m, cmd")
	w("}")
	w("")
	w("func (m promptModel) View() string {")
	w(`	return fmt.Sprintf("%s\n%s\n", m.label, m.input.View())`)
	w("}")

	return os.WriteFile(filepath.Join(hybridDir, "prompt.go"), []byte(sb.String()), 0o644)
}
